bikeindex/bike_index

app/controllers/admin/bikes_controller.rb, app/controllers/admin/dashboard_controller.rb, app/models/b_param.rb, app/models/manufacturer.rb, app/views/bikes/edit_accessories.html.haml, app/views/locks/_form.html.haml, app/views/organizations/embed_sf_safe.html.haml, spec/controllers/bikes_controller_spec.rb, spec/models/b_param_spec.rb
Fix break when `manufacturer_id` is a random strings - probs due to disabled javascript
Also, make `Manufacturer.other` consistent with other models `other` method.
=> Never trust manufacturer_id on bike create

app/controllers/api/v1/bikes_controller.rb, spec/controllers/api/v1/bikes_controller_spec.rb
`stolen_ids` should respond with a hash that looks like `{ bikes: [] }`, not a raw array.
Fix the unintended issue caused by #261
=> Revert unintended API v1

app/controllers/welcome_controller.rb, app/views/welcome/bike_creation_graph.haml, app/views/welcome/creation_graph.haml, config/routes.rb, spec/controllers/welcome_controller_spec.rb
Initially did from when Bike Index was started, but decided to use from merger with SBR instead.
To get the graph of all time (in a terrible, non-performant way) I did:
```ruby
creation = DateTime.strptime('01-01-2013 0', '%m-%d-%Y %H')
merge_end = DateTime.strptime('07-01-2014 0', '%m-%d-%Y %H')
sbr_bikes = Bike.where(creation_organization_id: 36).where('created_at < ?', merge_end)
sbr_bikes_ids = sbr_bikes.pluck(:id)
sbr_bikes_count = sbr_bikes.count + Bike.unscoped.where('created_at < ?', creation).where.not(id: sbr_bikes_ids).count # Primarily Bike Portland ;)
pre_merge = Bike.unscoped.where('created_at < ?', merge_end).where('created_at > ?', creation).where.not(id: sbr_bikes_ids).group_by_month(:created_at).count
pre_merge[pre_merge.keys.last] = pre_merge[pre_merge.keys.last] + …
```
=> Create a cumulative graph of bikes

.gitignore, Cheffile, README.markdown, Vagrantfile
This commit adds Vagrantfile and Cheffile, which are used by Vagrant to
automatically set up a virtual development environment designed to be
used for local Bike Index development. Chef is used to automatically
provision the environment with all of the required dependencies and
configures PostgreSQL. This makes the process of setting up a local
development environment much quicker and straightforward. As long as
Vagrant/VirtualBox is installed with the required Vagrant plugins, the
environment can be brought up just by running `vagrant up`. After SSHing
in, the "Running Bike Index locally" intructions in the README can be
followed verbatim without any additional configuration.
This commit also updates README.markdown to acknowledge this feature.
=> Add support for Vagrant development environment

app/assets/javascripts/documentation/swagger_inlined.coffee
Clicking the links in the API docs nav wasn't scrolling to the corresponding page position. I updated `scrollToRef` to scroll using `window.scrollTo`. 
Additionally, I removed `$('#header').headroom()` to keep the API token header fixed and keep the offset consistent as sometimes it would appear with scrolling and other times it wouldn't.
Happy to make additional changes!
Note: Scroll animation works fine in Chrome and Mozilla but jumps to the position in Safari.
=> Updated nav scroll in the API docs page

app/views/bikes/edit_remove.html.haml
Without this statement, I assumed that the setting would be permanent.
=> Indicate that a hidden bike can be shown

app/views/layouts/application_updated.html.haml, app/views/news/show.html.haml, app/views/shared/_bikes_footer_ad.html.haml, app/views/shared/_content_footer_ad.html.haml, app/views/shared/_google_text_ad.html.erb, app/views/stolen/index.html.haml
Remove google ads to most comply with the [Ethical Ads](https://docs.readthedocs.io/en/latest/advertising/ethical-advertising.html) model - as brought up by @stevepiercy in #441
=> Remove google ads

app/models/bike.rb
Remove tsearch from standard bike search because searches keep timing out.
=> Remove tsearch from standard bike search

Gemfile, Vagrantfile
While setting up my dev environment, I ran into a few issues with Vagrant. The first is below:
```
default: there was an error installing gem bundler
default: .......................................................
default: ruby-2.2.5 - #generating global wrappers
default: .......
default: ruby-2.2.5 - #gemset created /usr/share/rvm/gems/ruby-2.2.5
default: ruby-2.2.5 - #importing gemsetfile /usr/share/rvm/gemsets/default.gems evaluated to empty gem list
default: ruby-2.2.5 - #generating default wrappers
default: .......
default: ERROR:  Error installing bundler:
default: 	bundler requires Ruby version >= 2.3.0.
default: Required ruby-2.5.1 is not installed.
default: To install do: 'rvm install "ruby-2.5.1"'
default: ./rubydevprovision.sh: line 10: bundle: command not found
default: rake …
```
=> Fix various issues with Vagrant

app/controllers/admin/bikes_controller.rb, app/controllers/admin/dashboard_controller.rb, app/controllers/admin/memberships_controller.rb, app/controllers/admin/users_controller.rb
* Eager load relations in some admin controllers to avoid n+1's and speed up the respective queries
* Remove unnecessary relations from existing `includes`
=> Eager load relations in admin controllers

lib/tasks/seed_tasks.rake
Seeding test users and bikes fails on master because `CycleType` was
refactored to no longer be an `ActiveRecord` model in 77479df97 (#591) but we're invoking `CycleType.find_by_name` in the seeds file. This patch removes the failing lines and passes the cycle type explicitly to `Bike.new`.
```
bike_index master % rake seed_test_users_and_bikes
. . .
Users added successfully
rake aborted!
NoMethodError: undefined method `find_by_name' for CycleType:Class
lib/tasks/seed_tasks.rake:33:in `block in <top (required)>'
ruby/2.5.1/bin/ruby_executable_hooks:24:in `eval'
ruby/2.5.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => seed_test_users_and_bikes
```
```
bike_index fix-cycletype-in-seeds % rake seed_test_users_and_bikes
Users added successfully
New bike made by FiberFix
New bike …
```
=> Fix CycleType.find_by_name in seed file

app/assets/javascripts/init.coffee, app/assets/javascripts/revised/pages/welcome/recovery_stories.coffee, app/assets/stylesheets/revised/pages/landing/_recoveries.scss, app/controllers/feedbacks_controller.rb, app/controllers/welcome_controller.rb, app/views/recovery_displays/_recovery_display.html.haml, app/views/welcome/index.html.haml, app/views/welcome/recovery_stories.html.haml, config/routes.rb, spec/controllers/welcome_controller_spec.rb, spec/factories/recovery_displays.rb
- Updates the home page to display 5 recovery displays
- Adds a link to `/recovery_stories`
- Displays 5 displays at a time, paginated, at `/recovery_stories`
Resolves #524
=> Add recovered bikes page

app/assets/javascripts/revised/pages/welcome/recovery_stories.coffee, app/assets/stylesheets/revised/pages/landing/_recoveries.scss, app/controllers/welcome_controller.rb, app/views/welcome/index.html.haml, app/views/welcome/recovery_stories.html.haml, config/sitemap.rb
- Moves the "read more recovery stories" link to the end of the slideshow
- Doubles the number of recovery stories displayed
- Displays recovery stories in two columns (past "xl" width breakpoint)
- Adds the recovery stories page to the sitemap
Full width
Narrow
Implements suggestions from https://github.com/bikeindex/bike_index/pull/668
=> Update UIs for Recovery Stories

app/assets/javascripts/revised/pages/welcome/recovery_stories.coffee, app/views/welcome/recovery_stories.html.haml
Currently `slick` isn't being initialized on recovery stories containers, so images aren't loading. This patch fixes that by correcting the dom query string to `.recovery-stories-container`. 
NB: There's an issue where the height of a container isn't computed correctly by slick if elements within it are missing images, but all the recovery stories on prod seem to have images, so this wouldn't be an issue in practice.
=> Fix bug in Slick initialization

Gemfile, Gemfile.lock, config/initializers/jazz_fingers.rb
@sethherr Any objection to using Pry? I noticed it was commented out in the Gemfile.
Adds some debugging enhancements for the rails console: [pry-rails](https://github.com/rweng/pry-rails), [pry-byebug](https://github.com/deivid-rodriguez/pry-byebug), [jazz_fingers](https://github.com/plribeiro3000/jazz_fingers)
```
2.5.1 (bikeindex)[42] » User.joins(:user_emails).where("users.email = ? OR user_emails.email = ?", owner_email, owner_email).select(:id).uniq
(45.2ms)  SELECT DISTINCT COUNT(DISTINCT "users"."id") FROM "users" INNER JOIN "user_emails" ON "user_emails"."user_id" = "users"."id" WHERE (users.email = 'dawnwind2014@gmail.com' OR user_emails.email = 'dawnwind2014@gmail.com')
User Load (44.4ms)  SELECT DISTINCT "users"."id" FROM "users" INNER JOIN "user_emails" ON …
```
=> Add jazz_fingers, pry-rails

app/controllers/admin/failed_bikes_controller.rb, app/javascript/stylesheets/_admin.scss, app/views/admin/failed_bikes/index.html.haml
Fixes #714:
- Replaces `each_key` invocation on Array with `each`
- Eliminates N+1 query by preloading associated creators
- Paginates failed bike output (otherwise the page loads extremely slowly)
**Screenshot**
=> Fix failed bikes page exception

spec/controllers/admin/bulk_imports_controller_spec.rb, spec/controllers/api/v1/manufacturers_controller_spec.rb, spec/controllers/organized/bulk_imports_controller_spec.rb, spec/requests/api/manufacturers_request_spec.rb, spec/requests/api/v2/bikes_request_spec.rb, spec/requests/api/v2/manufacturers_request_spec.rb, spec/requests/api/v2/swagger_request_spec.rb, spec/requests/api/v3/bikes_request_spec.rb, spec/requests/api/v3/swagger_request_spec.rb, spec/spec_helper.rb
For consistency, replaces `JSON.parse()` and `JSON()` invocations in specs with the `json_result` spec helpers.
=> Replace JSON.parse / JSON() in specs with `json_result`

app/controllers/api/v2/bikes.rb, app/models/b_param.rb, app/models/bike.rb, app/services/bike_finder.rb, spec/models/b_param_spec.rb, spec/requests/api/v2/bikes_request_spec.rb, spec/requests/api/v3/bikes_request_spec.rb, spec/services/bike_finder_spec.rb
When creating a bike, first [search for the record](https://github.com/bikeindex/bike_index/pull/715/files#diff-2a964c740a025559cefad2c1348689ba) being created by serial number and email address (tests [here](https://github.com/bikeindex/bike_index/pull/715/files#diff-9aa7bec756e779b03037858befd4f7ff)):
```rb
post "/", serializer: BikeV2ShowSerializer, root: "bike" do
bike_attrs = %w{serial owner_email}.map { |key| [key.to_sym, params[key]] }.to_h
found_bike = BikeFinder.find_matching(**bike_attrs)
```
<details>
<summary>BikeFinder generated SQL</summary>
```sql
-- BikeFinder.find_matching(serial: "serial-1", owner_email: "user@example.com")
-- Bike Load (12.4ms)
SELECT
"bikes".* 
FROM
"bikes" 
RIGHT JOIN
ownerships 
ON bikes.id = ownerships.bike_id 
WHERE
"bikes"."example" = false
AND …
```
=> Ensure bike creation API endpoint upserts

.circleci/config.yml, README.markdown
Integrates [CI with Cloud 66 deployments](https://help.cloud66.com/node/integrations/integration-with-circle-ci.html)
- Adds a deployment step to the CircleCI config
- Adds the deployment status to the README
TODO
- Requires adding a `CLOUD66_REDEPLOYMENT_PATH` env var on CircleCI
=> Add deployment step to CircleCI config

app/controllers/api/v2/bikes.rb, spec/requests/api/v3/bikes_request_spec.rb
Updates tests and implementation for the bike upsert endpoint to cover the following cases:
```
create
given a matching pre-existing bike record
if the POSTer is authorized to update
does not create a new record
updates the pre-existing record
if the matching bike is unclaimed
updates if the submitting org is the creation org
creates a new record if the submitting org isn't the creation org
if the matching bike is claimed
creates a new bike
given a bike with a pre-existing match by a normalized serial number
responds with the match instead of creating a duplicate
given a bike with a pre-existing match by a normalized email
responds with the match instead of creating a duplicate
given a bike with a pre-existing match by an owning user's secondary email
responds with the match instead of …
```
=> Define bike upsert behavior for pre-existing but claimed bikes

app/controllers/api/v3/organizations.rb, app/controllers/organizations_controller.rb, app/controllers/organized/ambassadors_controller.rb, app/controllers/organized/base_controller.rb, app/models/membership.rb, app/models/organization.rb, app/models/user.rb, app/views/bikes/_organized_access_panel.html.haml, app/views/bikes/edit_stolen.html.haml, app/views/landing_pages/ambassadors_current.haml, app/views/layouts/application_revised.html.haml, app/views/organizations/_new_form.html.haml, app/views/organized/ambassadors/index.html.haml, app/views/shared/_organized_skeleton.html.haml, config/routes.rb, spec/controllers/organizations_controller_spec.rb, spec/controllers/organized/ambassadors_controller_spec.rb, spec/controllers/organized/base_controller_spec.rb, spec/factories/memberships.rb, spec/factories/organizations.rb, spec/factories/users.rb, spec/models/membership_spec.rb, spec/models/user_spec.rb, spec/requests/api/v3/organizations_request_spec.rb, spec/routing/organizations_rounting_spec.rb, spec/support/request_spec_helpers.rb
- Introduces an "ambassador" organization type
- Adds an ambassador dashboard endpoint in the `organized` namespace
- Directs user to the either the ambassador dashboard or the bikes page based on whether the current org is an ambassador org
- Introduces `User.ambassadors` to list all ambassadors, optionally filtering by organization
- Introduces `User#ambassador?` 
- Allows ambassador users to edit bikes (and mark them as recovered)
=> Add ambassador organization type, ambassador dashboard

app/controllers/discourse_authentication_controller.rb, spec/controllers/discourse_authentication_controller_spec.rb
When authenticating via Discourse SSO, enable admin/moderator permissions for bike index superusers / ambassadors, respectively.
Resolves #764
=> Set admin/moderator discourse permisssions automatically

app/mailers/customer_mailer.rb, spec/mailers/customer_mailer_spec.rb, spec/workers/email_stolen_notification_worker_spec.rb
According to this [Stack Overflow answer](https://stackoverflow.com/questions/2421234/gmail-appearing-to-ignore-reply-to), it looks like we shouldn't include the from address in the to address, or it won't do reply-to correctly in gmail.
... Also, it looks like I wasn't setting reply_to at all 😢
=> fix reply_to in stolen_notification emails

app/assets/javascripts/revised/pages/organized/ambassador_dashboard_index.coffee, app/controllers/organized/admin_controller.rb, app/controllers/organized/ambassador_dashboard_controller.rb, app/controllers/organized/ambassador_task_assignments_controller.rb, app/controllers/organized/base_controller.rb, app/controllers/organized/bulk_imports_controller.rb, config/routes.rb, spec/controllers/organized/base_controller_spec.rb, spec/controllers/organized/bikes_controller_spec.rb, spec/controllers/organized/bulk_imports_controller_spec.rb, spec/controllers/organized/manage_controller_spec.rb, spec/controllers/organized/users_controller_spec.rb, spec/routing/organizations_rounting_spec.rb
- Adds `before_action`s prohibiting access to `organized` endpoints for ambassador organizations (exceptions for ambassador controllers and `Organized::BaseController#root`
=> Restrict ambassador access to non-ambassador endpoints

app/views/admin/ambassador_tasks/_form.html.haml, app/views/admin/ambassador_tasks/edit.html.haml, app/views/admin/ambassador_tasks/new.html.haml
- Adds some UI polish to the AmbassadorTask create/edit pages
- Extracts the ambassador task form to a partial
=> Extract form, add Markdown guide link to Admin AmbassadorTask

Gemfile, Gemfile.lock, app/controllers/bikes/recovery_controller.rb, app/decorators/bike_decorator.rb, app/mailers/customer_mailer.rb, app/models/stolen_record.rb, app/views/admin/stolen_bikes/edit.html.haml, app/views/bikes/_bike_show_overlays.html.haml, app/views/bikes/_organized_access_panel.html.haml, app/views/customer_mailer/recovered_from_link.html.haml, config/environments/development.rb, db/migrate/20190524191139_add_recovering_user_id_to_stolen_records.rb, db/structure.sql, spec/decorators/bike_decorator_spec.rb, spec/models/stolen_record_spec.rb
- Adds a "recover bike" link to the organized bike access panel for ambassador orgs
- Adds the letter_opener gem to view html emails in browser
- Introduces `BikeDecorator#creation_organization_name`
Email:
=> Ambassadors recovery flow

app/javascript/packs/pages/admin/binx_admin.js, app/javascript/packs/pages/admin/organization_form.js, app/javascript/packs/pages/initializer.js, app/models/organization.rb, app/views/admin/organizations/_form.html.haml, spec/factories/organizations.rb, spec/models/organization_spec.rb
- Adds a `before_save` that sets sensible defaults for ambassador organization records
- Adds client-side logic to toggle related input fields based on "ambassador" being selected as the organization type
=> Set attributes for ambassador organizations

app/controllers/admin/dashboard_controller.rb, app/views/admin/dashboard/invitations.html.haml, app/views/layouts/new_admin.html.haml, spec/controllers/admin/dashboard_controller_spec.rb
Current page is just rendered in prompt, not the active value in admin other select. The issue with it being the active value is that you can't use the prompt to switch back to the page you were viewing.
=> Better admin other prompt select

app/views/welcome/index.html.haml
Update "bikes recovered" figure to read more naturally
=> Fix homepage copy

app/views/landing_pages/_tweet.html.haml, app/views/landing_pages/for_cities.haml
The tweet currently persisted has an outdated avatar url. This patch updates the tweet
partial to use a newly fetched version of the same tweet.
=> Fix for cities tweet

app/assets/javascripts/init.coffee, app/assets/javascripts/revised/pages/organized/ambassador_dashboards_show.coffee
This patch updates the body class name for the ambassador dashboard, which was changed from `organized_ambassador_dashboard_index` to `organized_ambassador_dashboards_show`. 
This restores the ability to update the completion status of ambassador task assignments from the organized ambassador dashboard.
=> Update ambassador dashboard coffeescript class name

app/controllers/admin/tweets_controller.rb, app/models/tweet.rb, app/models/twitter_client.rb, app/views/admin/tweets/edit.html.haml, app/views/admin/tweets/index.html.haml, app/views/landing_pages/_tweet.html.haml, app/views/landing_pages/for_cities.haml, spec/controllers/admin/tweets_controller_spec.rb
Prompted by the expedient workaround in https://github.com/bikeindex/bike_index/pull/826:
- Updates the Twitter API ENV keys to match C66 config (possibly a long-standing bug)
- Navigate from admin tweets index to edit page using tweet id rather than twitter id
- Updates `friendly_find` to return the most recent version of a tweet
- Ensures duplicate records (by `twitter_id`) are disallowed (if this is undesirable, please advise)
- Adds ability to delete tweet records
Resolves #827
=> Add admin/tweets management facilities

Gemfile, Gemfile.lock
Eliminates deprecation warnings from outdated versions of omniauth, jazz_fingers.
```
% bin/rails c
W, [2019-06-02T10:15:34.073533 #83787]  WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at ~/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/omniauth-1.3.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
~/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jazz_fingers-5.0.0/lib/jazz_fingers/prompt.rb:40:
warning: method Pry#input_array is deprecated. Use Pry#input_ring instead
Loading development environment (Rails 4.2.11)
2.5.1 (bikeindex)[1] »
```
```
bike_index task-completion-feedback % bin/rails c
Loading development …
```
=> Update omniauth, jazz_fingers

app/controllers/organized/ambassador_dashboards_controller.rb, app/decorators/ambassador_decorator.rb, app/decorators/ambassador_task_decorator.rb, app/models/ambassador.rb, app/views/organized/ambassador_dashboards/show.html.haml, spec/requests/organized/ambassador_dashboards_request_spec.rb
Fixes a UninferrableDecoratorError  / NoMethodError exception that occurs when accessing the organized ambassador dashboard as a super admin who is not in the ambassador organization.
Fixes https://github.com/bikeindex/bike_index/issues/842
https://app.honeybadger.io/projects/35931/faults/50329990#notice-comments
=> Fix ambassador dashboard exception

Gemfile, app/controllers/admin/manufacturers_controller.rb, app/controllers/admin/organizations_controller.rb, app/controllers/admin/stolen_notifications_controller.rb, app/controllers/bikes_controller.rb, app/controllers/users_controller.rb, app/decorators/ambassador_decorator.rb, app/decorators/ambassador_task_assignment_decorator.rb, app/decorators/ambassador_task_decorator.rb, app/decorators/application_decorator.rb, app/decorators/bike_decorator.rb, app/decorators/component_decorator.rb, app/decorators/location_decorator.rb, app/decorators/lock_decorator.rb, app/decorators/manufacturer_decorator.rb, app/decorators/organization_decorator.rb, app/decorators/paginating_decorator.rb, app/decorators/stolen_notification_decorator.rb, app/decorators/stolen_record_decorator.rb, app/decorators/user_decorator.rb, app/helpers/application_helper.rb, app/views/admin/organizations/show.html.haml, app/views/bikes/pdf.html.haml, app/views/info/where.html.haml, app/views/users/show.html.haml, spec/decorators/application_decorator_spec.rb, spec/decorators/bike_decorator_spec.rb, spec/helpers/application_helper_spec.rb
- Removes empty decorators in `app/decorators`
- Move any cheap-to-refactor methods into helpers
- Add deprecation comment in any remaining decorators and to the Gemfile
Resolves #853
=> Deprecate Draper

config/initializers/time_parser.rb
This patch fixes a local timezone-based failure in `TimeParser`: `Time.strptime` parses time in the machine's timezone, not the Rails timezone, so this test can fail if it's not run in Central Time.
```rb
Time.zone.parse("2018-09-30").in_time_zone(ActiveSupport::TimeZone["Central Time (US & Canada)"])
Time.strptime("2018-09-30", "%Y-%m-%d").in_time_zone(ActiveSupport::TimeZone["Central Time (US & Canada)"])
```
Local runs
Before:
```
2) TimeParser parse with cray IE 11 time params parses it, resets the zone over and over again
Failure/Error: expect(subject.parse(time_str, "").to_i).to eq target_time
expected: 1538283600
got: 1538197200
(compared using ==)
```
After:
```
Finished in 6 minutes 32 seconds (files took 10.94 seconds to load)
1953 examples, 0 failures, 13 pending
Randomized …
```
=> Fix IE11 time parsing failure

app/controllers/admin/payments_controller.rb, app/views/admin/bike_codes/index.html.haml, app/views/admin/news/index.html.haml, app/views/admin/organizations/invoices/_table.html.haml, app/views/admin/payments/index.html.haml
This patch resolves some breakages in the admin templates that are showing up locally due to missing data.
- Refactors to check for the presence of the associated record, not just its
foreign key (+ `includes` to avoid an N+1 query)
```diff
- - if payment.organization_id.present?
+ - if payment.organization.present?
= link_to payment.organization.short_name, admin_organization_path(payment.organization)
```
```diff
- invoices.each do |invoice|
-        - organization = Organization.find(invoice.organization_id)
+        - organization = invoice.organization
```
```diff
-    @invoices = invoices.includes(:organization, :payments)
-      .reorder(sort_column + " " + sort_direction).page(page).per(per_page)
+    @invoices =
+      invoices
+        .includes(:organization, :payments, …
```
=> Fix some NoMethodError exceptions in admin templates

Gemfile, Gemfile.lock, app/models/ambassador_task.rb, app/models/membership.rb, app/services/ambassador_task_assignment_creator.rb, app/workers/ambassador_membership_after_create_worker.rb, app/workers/ambassador_task_after_create_worker.rb, spec/factories/amabassador_tasks.rb, spec/factories/memberships.rb, spec/models/ambassador_task_spec.rb, spec/models/membership_spec.rb, spec/services/ambassador_task_assignment_creator_spec.rb, spec/workers/ambassador_membership_after_create_worker_spec.rb, spec/workers/ambassador_task_after_create_worker_spec.rb
- Moves the logic for assigning a newly created `AmbassadorTask` to all existing `Ambassador`s from an AR callback in `AmbassadorTask` to `AmbassadorTaskAssignmentCreator.assign_task_to_all_ambassadors`, which is enqueued upon creation of a new task.
- Moves the logic for assigning existing tasks to a new `Ambassador` from an AR callback in `Membership` to `AmbassadorTaskAssignmentCreator.assign_all_ambassador_tasks_to`, which is enqueued upon creation of a new ambassador membership.
- Assignments are created in bulk (`activerecord-import` added in d1a469d)
```
2.5.1 (bikeindex)[5] » AmbassadorTaskAssignmentCreator.assign_task_to_all_ambassadors(AmbassadorTask.fifth)
...
AmbassadorTaskAssignment Create Many Without Validations Or Callbacks (8.2ms)
INSERT INTO "ambassador_task_assignments" …
```
=> Create ambassador task assignments on task / membership creation asynchronously

app/controllers/admin/organizations_controller.rb, app/models/organization.rb, app/views/admin/organizations/_form.html.haml, app/views/admin/organizations/show.html.haml, db/migrate/20190607174104_add_previous_slug_to_organizations.rb, db/structure.sql, spec/controllers/admin/organizations_controller_spec.rb, spec/models/organization_spec.rb
BikeEastBay changed their name from East Bay Bike Coalition. There are still some links and references around on their site to the previous slug they had (`ebbc`). I suspect we will run into this problem again in the future, so add a way to deal with it.
=> Add previous slug for organizations

spec/controllers/admin/bikes_controller_spec.rb, spec/controllers/admin/stolen_bikes_controller_spec.rb, spec/controllers/bikes_controller_spec.rb, spec/controllers/landing_pages_controller_spec.rb, spec/controllers/organized/bikes_controller_spec.rb, spec/controllers/registrations_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/controllers/welcome_controller_spec.rb, spec/rails_helper.rb
Re-enables rendering views in all controller specs, not just those
in which we're asserting against rendered templates. The performance
impact is minimal and we still get some value from potentially
triggering exceptions from rendered templates.
```
Randomized with seed 29268
1964 examples, 0 failures, 13 pendings
Took 24 seconds
```
=> Render views globally

app/models/creation_state.rb, app/models/invoice.rb, app/models/organization.rb, app/models/stolen_notification.rb, app/views/admin/organizations/_admin_organizations_table.html.haml, app/views/bikes/_organized_access_panel.html.haml, spec/controllers/stolen_notifications_controller_spec.rb, spec/models/organization_spec.rb, spec/models/stolen_notification_spec.rb, spec/models/user_spec.rb
Enables unstolen notifications for ambassador orgs, pre-populates the message based on the current user:
```haml
-# app/views/bikes/_organized_access_panel.html.haml L140-151 (b9998cf1)
.collapse#new_stolen_message{ class: ("in" if @contact_owner_open) }
- @stolen_notification ||= StolenNotification.new(bike: @bike, sender: current_user)
= form_for @stolen_notification do |f|
= f.hidden_field :bike_id, value: @bike.id
= f.text_field :reference_url, placeholder: 'Link url', class: "form-control additional-field"
- if current_user.ambassador?
= f.text_area :message, required: true, value: @stolen_notification.default_message, rows: 6, class: "form-control"
- else
= f.text_area :message, required: true, placeholder: "Where did you see this #{@bike.type}? If you're contacting about an ad you …
```
=> Add automatically generated unstolen notification messages

.gitignore, README.markdown, bin/spring, config/environments/development.rb, lib/tasks/dev_configuration.rake
I know people love spring!
I've spent a non-trivial chunk of time dealing with various Spring issues (previously in other projects), which makes me cautious. Spring also doesn't seem to speed up my personal development process of guard running tests for the files I'm changing (by much).
This PR adds a rake task to toggle spring disabled. I decided to do the same thing Rails 5 does for toggling caching in development, so I also added a rake task for `dev:cache` here as well, since it's nice to have, and why wait till rails 5!
=> Add easy path for disabling spring locally

app/controllers/organized/messages_controller.rb, app/views/organized/messages/index.html.haml, spec/controllers/organized/messages_controller_spec.rb
Follow up to #868 - specifically to [my message about plural variables](https://github.com/bikeindex/bike_index/pull/868/files#r292229758)
I thought, from a cursory look around the code, that we were only passing singular paid features to `paid_for?` - however, this `@kind` was actually an array some of the time.
This refactors it to _always_ be an array, which makes more sense to me.
=> Make Message kinds variable plural

app/controllers/organized/manage_controller.rb, app/models/organization.rb, spec/controllers/organized/manage_controller_spec.rb
I think there might need to be more interface around this, eventually.
We ran into a problem where people from an organization had independently created two organizations and weren't able to figure out why they couldn't see each other. This should be harder to do than it is right now.
=> Add uniqueness constraint on organization names

Gemfile, Gemfile.lock, app/controllers/api/v2/users.rb, spec/requests/api/v2/swagger_request_spec.rb
Resolves the following deprecations:
```
The route_xxx methods such as route_method have been deprecated, please use request_method.
The route_xxx methods such as route_path have been deprecated, please use path.
```
<details>
```
% bin/rails c
/Users/jmromer/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/grape-swagger-0.10.5/lib/grape-swagger.rb:26: The route_xxx methods such as route_path have been deprecated, please use path.
/Users/jmromer/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/grape-swagger-0.10.5/lib/grape-swagger.rb:27: The route_xxx methods such as route_prefix have been deprecated, please use prefix.
/Users/jmromer/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/grape-swagger-0.10.5/lib/grape-swagger.rb:34: The route_xxx methods such as route_path have been …
```
=> Update grape-swagger to 0.11

app/controllers/admin/bikes_controller.rb, app/controllers/admin/feedbacks_controller.rb, app/controllers/admin/users_controller.rb, app/controllers/api/v1/users_controller.rb, app/models/feedback.rb, app/models/user.rb, app/views/admin/bikes/edit.html.haml, app/views/admin/feedbacks/index.html.haml, app/views/admin_mailer/feedback_notification_email.html.haml, config/routes.rb, db/migrate/20190611203612_migrate_feedback_hash_to_jsonb.rb, db/structure.sql, spec/controllers/admin/feedbacks_controller_spec.rb, spec/controllers/api/v1/users_controller_spec.rb, spec/controllers/feedbacks_controller_spec.rb, spec/factories.rb, spec/factories/feedbacks.rb, spec/models/feedback_spec.rb
Add some stuff to make it easier to view messages about bikes
After shipping, need to migrate the existing records with:
```ruby
Feedback.find_each { |f| f.update_column :feedback_hash, f.feedback_hash_text }
```
And then create a separate PR that drops the legacy column
=> Feedbacks hash migration

app/controllers/concerns/controller_helpers.rb, spec/controllers/admin/dashboard_controller_spec.rb, spec/controllers/sessions_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/requests/organized/ambassador_dashboards_request_spec.rb
With #787 we replaced redirects to `organization_bikes_url` with `organization_root_url` in order to dispatch to the ambassador dashboard when in ambassador view or the organization bikes page otherwise. 
This patch updates `user_root_url` to do likewise:
```rb
def user_root_url
return root_url unless current_user.present?
return admin_root_url if current_user.superuser
return user_home_url(subdomain: false) unless current_user.default_organization.present?
organization_root_url(organization_id: current_user.default_organization.to_param)
end
```
```rb
def root
if current_organization.ambassador?
redirect_to organization_ambassador_dashboard_path
else
redirect_to organization_bikes_path
end
end
```
=> Fix redirect to org bikes path

Guardfile, Guardfile_parallel
Add `directories` statement to the Guardfiles (per [Guard's optimizing page](https://github.com/guard/guard/wiki/Optimizing-for-large-projects)) - this made a big difference for me. Enough of a difference that I'm no longer super concerned about this.
=> Add directories statement to guardfiles

db/migrate/20190617174200_add_unique_index_to_ambassador_task_assignments.rb, db/structure.sql, spec/models/ambassador_task_assignment_spec.rb
Adds a database-level uniqueness constraint to task assignments. Working on determining why dupes are being created, I'll add a fix for that in a follow-up PR.
Related: #908
=> Add db-level uniqueness constraint for task assignments

Gemfile, Gemfile.lock
No other current usage aside from the logic removed in #910.
=> Remove activerecord-import library

Gemfile, Gemfile.lock, app/controllers/admin/theft_alert_plans_controller.rb, app/controllers/admin/theft_alerts_controller.rb, app/models/theft_alert.rb, app/models/theft_alert_plan.rb, app/views/admin/theft_alert_plans/_form.html.haml, app/views/admin/theft_alert_plans/edit.html.haml, app/views/admin/theft_alert_plans/index.html.haml, app/views/admin/theft_alert_plans/new.html.haml, app/views/admin/theft_alerts/edit.html.haml, app/views/admin/theft_alerts/index.html.haml, app/views/layouts/new_admin.html.haml, config/routes.rb, db/migrate/20190617193251_add_theft_alert_plans.rb, db/migrate/20190617193255_add_theft_alerts.rb, db/structure.sql, spec/factories/theft_alert_plans.rb, spec/factories/theft_alerts.rb, spec/models/theft_alert_plan_spec.rb, spec/models/theft_alert_spec.rb, spec/requests/admin/theft_alert_plans_request_spec.rb, spec/requests/admin/theft_alerts_request_spec.rb
- Adds `TheftAlert` and `TheftAlertPlan` models (with a temporary seed method on the latter)
- Adds admin pages to manage these
Extracted from #915 to reduce diff size
=> Add TheftAlert, TheftAlertPlan models

spec/models/counts_spec.rb
```
1) Counts week_creation_chart saves the thing
Failure/Error: expect(Counts.week_creation_chart).to eq target
expected: {"2019-06-14"=>1, "2019-06-15"=>0, "2019-06-16"=>0, "2019-06-17"=>0, "2019-06-18"=>0, "2019-06-19"=>0, "2019-06-20"=>1}
got: {"2019-06-13"=>1, "2019-06-14"=>0, "2019-06-15"=>0, "2019-06-16"=>0, "2019-06-17"=>0, "2019-06-18"=>0, "2019-06-19"=>1}
(compared using ==)
Diff:
@@ -1,8 +1,8 @@
-"2019-06-14" => 1,
+"2019-06-13" => 1,
+"2019-06-14" => 0,
"2019-06-15" => 0,
"2019-06-16" => 0,
"2019-06-17" => 0,
"2019-06-18" => 0,
-"2019-06-19" => 0,
-"2019-06-20" => 1,
+"2019-06-19" => 1,
```
=> Fix TZ bug in counts_spec

app/models/bike_code.rb, app/models/organization.rb, db/migrate/20190620203854_add_code_integer_and_prefix_to_bike_codes.rb, db/structure.sql, spec/controllers/bikes_controller_spec.rb, spec/models/bike_code_spec.rb, spec/models/organization_spec.rb
After shipping this and updating all the existing stickers, we're going to remove the `code` column (or calculate it from `pretty_code`)
=> Add additional lookups for bike codes

app/assets/stylesheets/revised/sections/legal.scss, app/controllers/concerns/sessionable.rb, app/controllers/organized/base_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/layouts/new_admin.html.haml, app/views/users/accept_terms.html.haml, app/views/users/accept_vendor_terms.html.haml, spec/controllers/users_controller_spec.rb, spec/factories/users.rb, spec/requests/admin/invoices_request_spec.rb, spec/requests/admin/theft_alert_plans_request_spec.rb, spec/requests/admin/theft_alerts_request_spec.rb, spec/requests/organized/ambassador_dashboards_request_spec.rb, spec/requests/theft_alerts_request_spec.rb, spec/support/controller_spec_helpers.rb, spec/support/request_spec_helpers.rb
Also:
- Switch to using contexts rather than methods for the request spec `logged_in_as...`
- Make redirects to `user_root_url` more consistent
=> Require accepting vendor terms for organization view

app/assets/stylesheets/revised/sections/form_well_header.scss, app/views/bikes/_theft_alerts_table.html.haml, app/views/bikes/edit_alert.html.haml, app/views/bikes/edit_alert_purchase.html.haml, app/views/bikes/edit_alert_purchase_confirmation.html.haml, app/views/bikes/edit_drivetrain.html.haml, app/views/bikes/edit_publicize.html.haml, app/views/bikes/edit_remove.html.haml, app/views/bikes/edit_report_recovered.html.haml, app/views/users/_edit_password.html.haml, app/views/users/_edit_root.html.haml, app/views/users/_edit_sharing.html.haml
I worry people will miss it, because it's below the fold, and then buy a new alert because they think it didn't work.
Also, add the `is_disabled` local variable to the primary edit menus on pages where it should be added because it's super slick 😍 @jmromer 
(on the other pages "existing theft alerts" is still below the main section)
=> Move purchased theft alert table above purchasing new alerts

app/controllers/bikes_controller.rb, spec/controllers/bikes_controller_spec.rb
Fixes a case statement clause allowing invalid templates to be returned
from #target_edit_template
https://app.honeybadger.io/projects/35931/faults/51171400
=> Fix bikes_controller#target_edit_template

app/views/admin/theft_alerts/index.html.haml, spec/requests/admin/theft_alerts_request_spec.rb
Oopsie, I'm a fool. Add a spec to make sure something like this doesn't slip through again.
=> Fix admin/theft_alerts index typo

Gemfile, Gemfile.lock, app/assets/stylesheets/revised/sections/primary_footer.scss, app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/models/user.rb, app/views/shared/_footer_revised.html.haml, app/views/users/_edit_root.html.haml, app/views/welcome/index.html.haml, config/application.rb, config/locales/en.yml, config/locales/es.yml, config/locales/nl.yml, db/migrate/20190625151428_add_preferred_language_to_user.rb, db/structure.sql, spec/controllers/bikes_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/models/user_spec.rb, spec/rails_helper.rb, spec/requests/locale_detection_request_spec.rb
Provides localization toggling via, in order of precedence:
1. Query param (settable via the footer UI)
2. User preference (settable via the user#edit?root form)
3. The `ACCEPT_LANGUAGE` header (minimally. settable via browser options)
Adds stub localization files for Spanish (for testing) and Dutch with generated translations of models and attributes
- Externalize template strings to English localization files
- Set up a translation service (PhraseApp, CrowdIn, Transifex, Locale)
`/my_account` 
site footer
via browser preferences
=> Add user-configurable preferred language, locale detection

app/controllers/application_controller.rb, spec/rails_helper.rb
Setting I18n.locale is [not thread-safe](https://github.com/ruby-i18n/i18n/pull/382). This patch ensures per-request locale setting doesn't leak across threads.
=> Prevent leaking of locale between requests

app/helpers/money_helper.rb, app/models/counts.rb, config/application.rb, config/locales/en.yml, config/locales/nl.yml, spec/helpers/money_helper_spec.rb
Introduces `MoneyHelper` to format currency values and convert between localized currencies, to enable currency conversion in addition to localized currency formatting (see below).
- `Counts.week_creation_chart` seems to have a dupe definition, should we delete one?
- The `protected` access control in `Counts` is a no-op. Is the intent for it to apply to the methods defined below it? If so, I'll move those into the `class << self`.
=> Introduce MoneyHelper view helper module

app/assets/javascripts/init.coffee, app/controllers/application_controller.rb, app/helpers/application_helper.rb, app/views/layouts/application_revised.html.haml, app/views/layouts/new_admin.html.haml, config/application.rb, config/routes.rb, lib/i18n/middleware.rb, spec/rails_helper.rb, spec/requests/locale_detection_request_spec.rb
- Adds [middleware](https://github.com/ruby-i18n/i18n/blob/master/lib/i18n/middleware.rb) from a more recent (but incompatible, alas) version of i18n to make i18n configuration thread-safe. This resolved the locale-leaking bug locally.
- Refactors locale setting to use an `around_action` to more cleanly isolate I18n locale per-request
- Implements `default_url_options` to set the current locale param, if one is provided, in any Rails-generated links
- Updates the coffeescript setting the bike search query params on the welcome page to not strip the locale param in the link
- Updates the blog post link on the home page logo so it retains the locale param
- Adds a link to the feature flag dashboard to the admin dashboard dropdown menu
=> Forward locale param when provided, set locale in around_action

bin/setup, lib/tasks/dev_configuration.rake, lib/tasks/seed_tasks.rake
- Populates the counts on bike stats visualization on the home page
- Adds descriptions for other dev-namespaced tasks so they show up in
`rake -T`
=> Add rake task to seed Redis with Counts figures

app/models/b_param.rb, app/services/bike_updator.rb, config/initializers/grape_values.rb, spec/controllers/bikes_controller_spec.rb, spec/models/b_param_spec.rb, spec/requests/api/v3/bikes_request_spec.rb
Updates `BParam` so it doesn't choke on primary/secondary/tertiary frame color params.
This class and its specs could use some refactoring but this a minimal fix — more substantial changes would take more time to implement safely than is feasible at the moment.
Related: #955
=> Fix BParam handling of color values

app/controllers/application_controller.rb, spec/requests/locale_detection_request_spec.rb
Sets locale to english when requesting admin pages, since these will not be localized.
Resolves #968
=> Set locale to English when requesting admin pages

app/views/layouts/application_revised.html.haml, config/locales/en.yml
Fixes a clobbered translation key:
Before:
After:
=> Fix missing translation argument in mobile header

app/assets/javascripts/init.coffee
Refactors away from using `Object.fromEntries` since it's not supported in older browsers.
Resolves https://app.honeybadger.io/projects/61305/faults/51925696
=> Provide implementation of Object.fromEntries

app/controllers/api/v2/bikes.rb, spec/requests/api/v2/bikes_request_spec.rb, spec/requests/api/v3/bikes_request_spec.rb
We don't require `phone` or `city` for new stolen records, so we shouldn't through the API either.
We depend on people actually finishing the registration afterward.
=> Remove Bikes API stolen requirements

app/controllers/api/base.rb, app/controllers/application_controller.rb, app/controllers/concerns/controller_helpers.rb, app/controllers/concerns/sessionable.rb, config/initializers/forwarded_ip_address.rb, spec/controllers/bikes_controller_spec.rb, spec/controllers/sessions_controller_spec.rb, spec/controllers/users_controller_spec.rb
Follow up to #1013
Things this does:
- Switch to using `forwarded_ip_address` for what is appended to our logging payload
- Always fallback in the same way, in all the places ip addresses are checked
- Move the `forwarded_ip_address` and ip appending to payload into controller helpers, which is included in controllers that don't inherit from `ApplicationController` (ie Doorkeeper controllers)
- Pass `forwarded_ip_address` to user and test that it is passed to user
=> Access ip address in consistent manner

app/javascript/packs/pages/initializer.js, app/javascript/packs/utils/time_parser.js
This is also written in coffeescript in [init.coffee](https://github.com/bikeindex/bike_index/blob/master/app/assets/javascripts/init.coffee) - but we've deprecated the coffeescript, so I'm not touching that.
This can absolutely, 100% be refactored and improved. Just looking at it I see glaring ugliness. But when refactoring, I would like to add tests for it, and I don't think that's a priority right now.
=> Move time parsing to utils

.circleci/config.yml, Gemfile, Gemfile.lock
- Bumps the patch version to silence warnings from i18n-tasks.
~- Kills `FILTERED_PARAMS` setting in `Api::Base` to silence a warning~
=> Bump Ruby to 2.5.5

app/views/errors/not_found.html.erb, app/views/errors/server_error.html, app/views/errors/server_error.html.erb, app/views/errors/unauthorized.html.erb, app/views/errors/unprocessable_entity.html.erb, app/views/info/_terms_text.html.erb, config/locales/en.yml
Externalizes errors and TOS templates:
errors
bad_request.html.erb
not_found.html.erb
unauthorized.html.erb
unprocessable_entity.html.erb
info
_terms_text.html.erb
=> Externalize error, info/terms pages

app/assets/stylesheets/revised/pages/info/about.scss, app/views/info/_terms_text.html.erb, app/views/info/_vendor_terms_text.html.erb, app/views/info/about.html.haml, app/views/info/privacy.html.erb, config/locales/en.yml
Externalizes strings from the following templates:
-  app/views/info/_terms_text.html.erb
-  app/views/info/_vendor_terms_text.html.erb
-  app/views/info/privacy.html.erb
-  app/views/info/about.html.haml
=> Externalize legal, about pages

app/controllers/api/base.rb, config/initializers/filter_parameter_logging.rb
In #979 we started filtering out image params from the API, because attempting to stringify images for JSON logging was causing the server to 500.
Let's filter them out in a more consistent way.
From my own local tests, this appears to work
=> Filter file params out everywhere

app/views/organized/users/new.html.haml, config/locales/en.yml
- Remove duplicated translation key
- Fix email translation key (so it doesn't show up unescaped, and because it doesn't need to be)
=> Translation fixes

app/mailers/customer_mailer.rb, config/routes.rb
[@jmromer asked why we weren't using the url paths](https://github.com/bikeindex/bike_index/pull/1010#discussion_r303441100) for are token emails.
I said:
> I forget why I switched to doing this for the token emails, but I did, so I'm hesitant to switch back.
From PR #1010
=> Use url helpers in token emails

app/views/info/dev_and_design.html.haml, app/views/info/image_resources.html.haml, app/views/info/protect_your_bike.html.haml, config/locales/en.yml
Externalizes strings from `info/dev_and_design.html.haml`.
The high-priority templates are all done at this point, so I'm pivoting toward model attributes and translation service setup.
=> Externalize dev_and_design templates

app/controllers/admin/news_controller.rb, app/javascript/packs/application_css.scss, app/models/blog.rb, app/views/admin/news/index.html.haml, spec/models/blog_spec.rb
Currently the URL to one of our Blog posts "WE MADE IT ALL THE WAY TO OREGON AND BACK WITHOUT ONE DYSENTERY SCARE", https://bikeindex.org/news/we-made-it-all-the-way-to-oregon-and-back-without- 404s
This fixes that
=> Minor admin blog edits

app/views/bikes/show.html.haml
When displaying manufacturers, we default to the Simple name - which, for "Pure Cycles (Pure Fix)" is just "Pure Cycles".
We include _Pure Fix_ in parentheses to make the manufacturer easier to find if the manufacturer goes by other names - e.g. Pure Cycles [changed its name from Pure Fix](https://www.purecycles.com/).
While displaying the detailed view of the bike, we should display the full manufacturer name.
=> Bike Manufacturer fix

app/models/user.rb, app/workers/merge_additional_email_worker.rb, spec/workers/merge_additional_email_worker_spec.rb
Resolves the foreign key constraint violation that occurs when attempting to destroy a user record in `MergeAdditionalEmailWorker` without reassigning dependent theft alerts.
Fixes https://app.honeybadger.io/projects/35931/faults/52295768
=> Handle theft_alerts in MergeAdditionalEmailWorker

app/mailers/customer_mailer.rb, app/models/user.rb, app/workers/email_magic_login_link_worker.rb, app/workers/email_reset_password_worker.rb, config/locales/customer_mailer.en.yml, spec/mailers/customer_mailer_spec.rb, spec/models/user_spec.rb, spec/workers/email_magic_link_worker_spec.rb, spec/workers/email_reset_password_worker_spec.rb, spec/workers/process_membership_worker_spec.rb
Looks like https://github.com/bikeindex/bike_index/pull/1034#issuecomment-512509125 was a valid bug.
Investigating fixes - I believe it isn't the fault of the url helpers, but instead something to do with the database
=> Error if token is blank for emails requiring token

app/views/bikes/show.html.haml, config/locales/en.yml
Fixes an exception from a missing interpolation key.
```yml
please_email_support_html: >-
Please email %{support_email_link} if you don't understand why you're seeing
this message or if you need an exception made.
```
<sup>[[source](https://github.com/bikeindex/bike_index/blob/0e96aa29/config/locales/en.yml#L1283-L1285)]</sup>
Resolves https://app.honeybadger.io/projects/35931/faults/52442699
Also fixes a NoMethodError from `.manufacturer` returning `nil':
https://app.honeybadger.io/projects/35931/faults/52395156
=> Fix missing interpolation argument in bikes/show

Gemfile, README.markdown, lib/tasks/rake_tasks.rake
Include `translation:sync` in `bin/rake prepare_translations` task.
I think this is useful because running `translation:sync` radically alters the normalized output (since it overrides any changes the normalization makes to non-english translations) - so I think it should be run any time you run the prepare_translation task. Is there a time when we wouldn't want prepare_translations to include sync (provided the API key is available?)
=> Include sync in prepare_translations task

.env, Gemfile, Gemfile.lock, app/uploaders/application_uploader.rb, app/uploaders/avatar_uploader.rb, app/uploaders/bulk_import_uploader.rb, app/uploaders/circular_image_uploader.rb, app/uploaders/export_uploader.rb, app/uploaders/image_uploader.rb, app/uploaders/json_uploader.rb, app/uploaders/listicle_image_uploader.rb, app/uploaders/partner_uploader.rb, app/uploaders/pdf_uploader.rb, app/uploaders/tsv_uploader.rb, config/initializers/carrierwave.rb, spec/services/phonifyer_spec.rb, spec/services/slugify_spec.rb, spec/services/urlifyer_spec.rb
- Upgrade `fog-aws` (unblocking nokogiri upgrade for Rails 5 upgrade)
- Add an `ApplicationUploader` for all the other uploaders to inherit from (cleaning up some of the carrierwave stuff)
- remove legacy utf magic comments because Ruby 2 made them unnecessary
=> Upgrade fog

app/views/organized_mailer/finished_registration.html.haml
Fix so this doesn't say stolen
=> Fix non-stolen bikes being called stolen in finished_registration email

app/controllers/api/v2/bikes.rb, app/controllers/bikes_controller.rb, app/controllers/theft_alerts_controller.rb, app/models/bike.rb, spec/models/bike_spec.rb
Rename `Bike` method `authorize_for_user!` to `authorize_and_claim_for_user`, to follow Ruby conventions.
Reasoning: I just started to write another method in bike, and was about to make it a bang method, since it also modifies state - however, I feel like bang methods should raise errors if the fail, since that seems to be a convention.
historical context: I _think_ I originally made `authorize_for_user!` a bang method to distinguish it from the similarly named `authorized_for_user?` - but I think renaming does a better job explaining what is going on and distinguishing it.
=> Improve bike authorize_and_claim_for_user naming

app/controllers/admin/bike_codes_controller.rb, app/models/bike_code_batch.rb, app/views/admin/bike_codes/index.html.haml, db/migrate/20190725172835_add_prefix_to_bike_code_batch.rb, db/structure.sql, spec/factories/bike_code_batches.rb, spec/models/bike_code_batch_spec.rb
I made a mistake adding codes manually - so I decided it was time to add some more automation to bike code creation.
Now if you have a `BikeCodeBatch`, you can create the next bike_codes by specifying how many you want to create.
```ruby
BikeCodeBatch.find(9).create_codes(500)
```
n.b. BikeCodes are actually stickers, see #1080
=> Automate Bike Code creation

README.markdown, lib/tasks/rake_tasks.rake
We don't want to sync branches, we only want to sync master, so this isn't a good thing to run all the time.
Reverts some of #1073 - but we still want to skip adding the missing translation keys, because when we do sync that will be managed.
=> remove sync from prepare translations

app/views/organized_mailer/finished_registration.text.haml, config/locales/en.yml
Original:
```haml
- if @bike.stolen
- stolen_record = @bike.current_stolen_record
#{ @bike.recovered ? 'Found:' : 'Stolen from:' }#{ stolen_record.address(skip_default_country: true) }
Date: #{ l stolen_record.date_stolen, format: :dotted }
```
Resolves https://app.honeybadger.io/projects/35931/faults/52572238
=> Fix incorrect interpolation arg

config/initializers/carrierwave.rb, spec/rails_helper.rb
Hotfix -- `RSpec` isn't defined during deployment init, so this patch moves CarrierWave RSpec settings to rails_helper.
=> Move test-specific CarrierWave settings to rails_helper

app/services/stolen_record_updator.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/carrierwave.rb, spec/decorators/bike_decorator_spec.rb
#1091 Breaks asset loading -- the changes to the app asset_host were overkill. This patch reverts those changes and instead sets `config.asset_host = ENV["BASE_URL"]` for CarrierWave specifically.
=> Fix prod assets host config

.circleci/config.yml, README.markdown, bin/check_translations
To automate translation syncing and updating, this patch adds a build step which checks for translation updates and, if any are found, stops the build and creates a PR for those changes. 
This is meant to be run on `master` in order to stop deployments, but can be customized (see below).
- Added a read-write SSH key to CircleCI and GitHub
Public: https://github.com/bikeindex/bike_index/settings/keys
Private: https://circleci.com/gh/bikeindex/bike_index/edit#ssh
- Added a [personal access token](https://github.com/settings/tokens) to CircleCI and exposed to builds as the `GITHUB_TOKEN` env variable. Used by [Hub](https://hub.github.com/) to create PRs on GitHub.
- Checks for un-synced translations only when building `master`. The branch is customizable by setting the `TRANSLATION_BRANCH` …
=> Add translation sync build step

app/models/stolen_record.rb, app/uploaders/alert_image_uploader.rb, app/workers/email_stolen_bike_alert_worker.rb, config/initializers/carrierwave.rb, spec/factories/public_images.rb, spec/factories/stolen_records.rb, spec/models/stolen_record_spec.rb, spec/rails_helper.rb
Fixes a bug whereby alert images are removed prematurely because a bike's `current_stolen record` has `date_recovered` set.
```rb
irb(main):006:0> bike.current_stolen_record.date_recovered
=> Wed, 31 Jul 2019 20:00:00 CDT -05:00
irb(main):007:0> bike.current_stolen_record.current
=> true
irb(main):008:0> bike.stolen?
=> true
irb(main):009:0> bike.recovered?
=> false
```
Also fixes filename generation for alert images, which currently doesn't correctly handle bike images with hyphens in the name.
Resolves https://app.honeybadger.io/projects/35931/faults/52782138
=> Fix premature image removal bug

app/models/stolen_record.rb, app/services/alert_image_generator.rb, app/uploaders/alert_image_uploader.rb, spec/models/stolen_record_spec.rb, spec/services/alert_image_generator_spec.rb, spec/uploaders/alert_image_uploader_spec.rb
Fixes https://app.honeybadger.io/projects/35931/faults/52866327, stemming from a stolen record that no longer has an associated bike
Fixes https://app.honeybadger.io/projects/35931/faults/52866677, from an apostrophe in a bike location string
Makes filename parsing more robust (the current method assumes `-alert` may be present in the bike image filename only as a suffix)
=> Fix alert image exceptions

app/controllers/admin/stolen_bikes_controller.rb, app/models/stolen_record.rb, app/views/admin/stolen_bikes/edit.html.haml, config/routes.rb, spec/models/stolen_record_spec.rb
- Adds `StolenRecord#generate_alert_image!` to force regenerating the alert image
- Adds the premium alert image to the stolen bike UI with a button to trigger regenerating
=> Add generate_alert_image!, alert image to admin UI

Gemfile.lock
Bump for breadcrumbs 🥖🍞 
> Breadcrumbs are avaliable for our Honeybadger Ruby client, but it
> looks like you need to upgrade first.
> This notice was sent using version 4.3.1. We introduced Breadcrumbs
> in version 4.4.0. Be sure to upgrade and enable to send breadcrumb
> data along with your errors!
=> Update Honeybadger Ruby client

app/controllers/api/v3/search.rb, app/models/concerns/bike_searchable.rb, spec/support/shared_examples/bike_searchable.rb
Ensures chained ActiveRecord calls and pagination work as expected:
```rb
get "/close_serials" do
close_serials = Bike.search_close_serials(interpreted_params)
serialized_bikes_results(paginate(close_serials))
end
```
<sup>[[source](https://github.com/bikeindex/bike_index/blob/fad36f08/app/controllers/api/v3/search.rb#L97-L100)]</sup>
```rb
@close_serials = Bike.search_close_serials(@interpreted_params).limit(10).decorate
```
<sup>[[source](https://github.com/bikeindex/bike_index/blob/f3c38a9d/app/controllers/bikes_controller.rb#L24-L24)]</sup>
```js
// 20190802093507
// http://localhost:3001/api/v3/search/close_serials?page=1&per_page=25&serial=
{
"bikes": []
}
```
Resolves https://app.honeybadger.io/projects/35931/faults/52862785
=> Fall back to empty collection if Bike.search_close_serials returns nil

Gemfile, app/controllers/concerns/controller_helpers.rb, config/honeybadger.yml
Adds honeybadger.yml to enable breadcrumbs:
> You currently have Breadcrumbs disabled in your Honeybadger Ruby client.
> If you would like to send Breadcrumbs to Honeybadger you must update your configuration to enable Breadcrumbs.
> Consult our documentation to learn more about Breadcrumbs and specifically [how to enable them](http://docs.honeybadger.io/lib/ruby/getting-started/breadcrumbs.html#enabling-breadcrumbs).
=> Add honeybadger.yml, enable breadcrumbs

app/services/bike_creator_associator.rb
Ensures parent (bike) is saved before associated records are created:
```rb
def save_bike(bike)
bike.save
@bike = create_associations(bike)
validate_record(@bike)
if @bike.present? && @bike.id.present?
@bike.creation_states.create(creation_state_attributes)
```
<sup>[[source](https://github.com/bikeindex/bike_index/blob/9aceeb76/app/services/bike_creator.rb#L70-L75)]</sup>
```rb
def create_associations(bike)
@bike = BikeCreatorAssociator.new(@b_param).associate(bike)
end
```
<sup>[[source](https://github.com/bikeindex/bike_index/blob/9aceeb76/app/services/bike_creator.rb#L45-L47)]</sup>
```rb
def associate(bike)
begin
ownership = create_ownership(bike)
create_components(bike)
create_normalized_serial_segments(bike)
assign_user_attributes(bike, ownership&.user)
create_stolen_record(bike) …
```
=> Ensure bike is saved in BikeCreatorAssociator

app/models/ownership.rb, spec/models/ownership_spec.rb
OwnerEmail can be persisted with an invalid owner_email, leading to exceptions
downstream when triggering `OrganizedMailer.finished_registration`:
https://app.honeybadger.io/projects/35931/faults/52974853
```
Ownership.find(id).owner_email
```
```rb
Ownership.where("owner_email NOT LIKE '%@%'").count
```
=> Add Ownership#owner_email format validation

app/models/stolen_record.rb
`save` is already called outside #remove_alert_image
Resolves https://app.honeybadger.io/projects/35931/faults/53104780
=> Kill save in remove_alert_image

app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/views/shared/_footer_revised.html.haml, app/views/users/_edit_root.html.haml, config/locales/en.yml, spec/controllers/users_controller_spec.rb, spec/helpers/application_helper_spec.rb, spec/requests/locale_detection_request_spec.rb
First, because the translator wants to see it. But also because why not!
- Setting language automatically leads to weird edge cases, and I don't think it adds much value. I've added a link to the edit account page, if there is a mismatch, which I think makes things better.
- When selecting a language, include the language's name in it's own language
=> Show language selection to everyone

bin/check_translations
- Add check for existing branch (with parallelism, multiple update branches will be attempted to be created)
- Only add PR info for topic branches, not when running on master (not meaningful there)
=> Tweaks for translation sync CI step

app/controllers/admin/stolen_bikes_controller.rb, app/models/alert_image.rb, app/models/bike.rb, app/models/stolen_record.rb, app/uploaders/alert_image_uploader.rb, app/views/admin/stolen_bikes/edit.html.haml, db/migrate/20190806155914_create_alert_images.rb, db/migrate/20190806170520_drop_alert_image_from_stolen_records.rb, db/structure.sql, spec/factories/alert_images.rb, spec/factories/stolen_records.rb, spec/models/alert_image_spec.rb, spec/models/bike_spec.rb, spec/models/stolen_record_spec.rb
- Adds `AlertImage` model to back alert image versions
- Update stolen records admin to use the new model
- Updates specs so that image files are created on an opt-in basis with the inclusion of a trait: `:with_alert_image` `:with_image`, etc
=> Add AlertImage model, update stolen_bike admin, kill logging

config/initializers/carrierwave.rb
Silences fog warnings about s3 bucket names with dots:
```
[fog][WARNING] fog: the specified s3 bucket name(files.bikeindex.org) contains a '.' so is not accessible over https as a virtual hosted bucket, which will negatively impact performance.  For details see: http://docs.amazonwebservices.com/AmazonS3/latest/dev/BucketRestrictions.html
[fog][WARNING] fog: the specified s3 bucket name(files.bikeindex.org) contains a '.' so is not accessible over https as a virtual hosted bucket, which will negatively impact performance.  For details see: http://docs.amazonwebservices.com/AmazonS3/latest/dev/BucketRestrictions.html
[fog][WARNING] fog: the specified s3 bucket name(files.bikeindex.org) contains a '.' so is not accessible over https as a virtual hosted bucket, which will negatively impact …
```
=> Explicitly set fog path style to silence warnings

bin/check_translations
Looks like if there's only commit in a PR, GitHub's "squash and merge" feature just uses the commit message's subject line as the commit title, rather than the PR title.
As a result, the `[ci skip]` in the subject line prevents CI from running when the branch is merged into master, and a deployment isn't triggered.
This patch performs translation commits in two steps, retaining [ci skip]. GitHub's squash + merge should then use the PR's commit message, which won't have [ci skip].
=> Commit translation sync changes in steps

app/services/alert_image_generator.rb, spec/factories/public_images.rb, spec/services/alert_image_generator_spec.rb, spec/uploaders/alert_image_uploader_spec.rb
- Adds specs for `AlertImageUploader` documenting behavior when base image is invalid or empty
- Adds branching around absent bike_url, bike_location in `AlertImageGenerator`
=> Add AlertImageUploader specs, AlertImageGenerator branching

app/assets/javascripts/revised/pages/bikes/edit_alert.coffee, app/assets/stylesheets/revised/mixins/_colors.scss, app/assets/stylesheets/revised/pages/bikes/edit_alert.scss, app/controllers/bikes_controller.rb, app/models/stolen_record.rb, app/services/alert_image_generator.rb, app/views/bikes/edit_alert.html.haml, config/locales/en.yml, spec/uploaders/alert_image_uploader_spec.rb
- Provides a UI for a user to select one of their bike's public images to be used in the promoted alert image. 
- Provides a preview rendered using CSS
- Begins generating / processing the alert image when the first stage of the promoted alert form is submitted
=> Add user image selection to premium alert purchasing flow

app/assets/javascripts/revised/pages/bikes/edit_alert.coffee, app/assets/stylesheets/revised/pages/bikes/edit_alert.scss, app/views/bikes/edit_alert.html.haml
The current alert image preview CSS rules assume >100% font size. (which is what I have locally because because my eyes are trash). This updates the CSS rules to make them more robust to font size changes.
Before:
After:
=> Fix alert image css preview

app/assets/stylesheets/revised/pages/bikes/edit_alert.scss
Very high font magnification + very narrow viewport:
Before:
After:
=> Make caption more robust to weird width / font size combos

app/models/organization.rb
Fixes `NoMethodError` when `child_ids` is `nil`:
> NoMethodError in Welcome#user_home
> Showing app/views/layouts/application_revised.html.haml where line #38 raised:
> undefined method `any?' for nil:NilClass
```rb
2.5.5 (bikeindex)[1] » Organization.where(child_ids: nil).count
(1.6ms)  SELECT COUNT(*) FROM "organizations" WHERE "organizations"."deleted_at" IS NULL AND "organizations"."child_ids" IS NULL
724
```
=> Fix nil NoMethodError from Organization#parent?

app/workers/process_membership_worker.rb, spec/models/membership_spec.rb
Fix an exception that occurs when inviting an unregistered user to an ambassador organization:
Resolves https://app.honeybadger.io/projects/35931/faults/53420005
Continuation of #1183
=> Fix issue with ambassador membership assignment

app/models/organization.rb, app/views/organized/bikes/incompletes.html.haml, app/views/shared/_edit_bike_skeleton.html.haml, app/views/shared/_organized_skeleton.html.haml, config/locales/en.yml
- Refactors to fix exceptions from `Organization#child_ids` being nil.
- Externalizes strings from `_organized_skeleton.html.haml` and `_edit_bike_skeleton.html.haml`
Resolves #1185
=> Externalize organized skeleton templates

app/views/info/serials.html.haml, app/views/info/where.html.haml, config/locales/en.yml
Wraps up the last couple of `views/info` templates.
=> Externalize remaining info templates

app/helpers/application_helper.rb, app/javascript/packs/external_registry_search/components/ExternalRegistrySearch.js, app/javascript/packs/external_registry_search/components/ExternalRegistrySearchResult.js, app/serializers/bike_v2_serializer.rb, app/serializers/external_bike_v3_serializer.rb, app/views/bikes/index.html.haml, spec/requests/api/v3/search_request_spec.rb, spec/serializers/bike_v2_show_serializer_spec.rb, spec/workers/file_cache_maintenance_worker_spec.rb
- Assets aren't available from the API
- Sets bike_placeholder_image_path on the window object to fall back to it in the React code
=> Fix external registry search placeholder images

app/helpers/application_helper.rb, app/models/organization.rb, app/views/admin/bikes/_bike.html.haml, app/views/admin/bikes/edit.html.haml, app/views/admin/bulk_imports/show.html.haml, app/views/admin/ctypes/index.html.haml, app/views/admin/mail_snippets/index.html.haml, app/views/admin/manufacturers/index.html.haml, app/views/admin/memberships/_table.html.haml, app/views/admin/news/index.html.haml, app/views/admin/organizations/_table.html.haml, app/views/admin/organizations/custom_layouts/index.html.haml, app/views/admin/recoveries/_table.html.haml, app/views/admin/recovery_displays/index.html.haml, app/views/admin/stolen_bikes/index.html.haml, app/views/admin/stolen_notifications/index.html.haml, app/views/admin/theft_alert_plans/index.html.haml, app/views/admin/tweets/index.html.haml, app/views/admin/users/_table.html.haml, app/views/admin/users/edit.html.haml, app/views/bikes/_organized_access_panel.html.haml, app/views/manufacturers/index.html.haml, app/views/organized/bikes/_search.html.haml, app/views/organized/users/index.html.haml
Introduces `ApplicationHelper#check_mark` and replaces all instances of the entity code with it.
=> Replace entity code with check_mark

app/models/bike.rb, app/views/admin/bikes/missing_manufacturer.html.haml, spec/controllers/api/v1/bikes_controller_spec.rb, spec/controllers/bikes_controller_spec.rb, spec/controllers/organized/messages_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/models/bike_spec.rb, spec/models/organization_message_spec.rb, spec/rails_helper.rb, spec/requests/api/v2/bikes_request_spec.rb, spec/requests/api/v3/bikes_request_spec.rb, spec/requests/organized/messages_request_spec.rb, spec/support/geocoder_default_location.rb, spec/support/shared_examples/bike_searchable.rb, spec/workers/bulk_import_worker_spec.rb
Extracted from #1214, which adds reverse geocoding to `StolenRecord` (necessitating a default geocoder location be available more broadly in the test suite.)
=> Set default geocoder location globally

app/controllers/admin/users_controller.rb, app/views/admin/bikes/_bike.html.haml, app/views/admin/users/edit.html.haml, spec/requests/admin/users_request_spec.rb
Because of recent conversation.
Also, because we should use the helper method
=> Display phone for stolen_record consistently

app/javascript/packs/external_registry_search/components/ExternalRegistrySearchResult.js, config/locales/en.yml
- Removes "near" in "near-matches"
- Renders string form of the date
=> External registry UI fixes

app/models/external_registries/stop_heling_client.rb
Fixes the `StopHelingClient` `Honeybadger.notify` invocation — we're currently not getting context for these notifications because it's being passed [incorrectly](https://www.rubydoc.info/gems/honeybadger/Honeybadger/Agent#notify-instance_method).
=> Fix Honeybadger notify invocation

Gemfile, Gemfile.lock, bin/setup
Resolves the following error:
```
~/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:462: 
in `block in replace_bin_path': can't find executable terminal-notifier for gem terminal-notifier. 
terminal-notifier is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
```
Resolves the following error when starting sidekiq:
```
which: no growlnotify in (....)
Traceback (most recent call last):
4: from ~/.asdf/installs/ruby/2.5.5/bin/ruby_executable_hooks:24:in `<main>'
3: from ~/.asdf/installs/ruby/2.5.5/bin/ruby_executable_hooks:24:in `eval'
2: from ~/.asdf/installs/ruby/2.5.5/bin/terminal-notifier:23:in `<main>'
1: from ~/.asdf/installs/ruby/2.5.5/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bun …
```
=> Add terminal notifier, growlnotify

config/initializers/geocoder.rb
`ENV.fetch("xxxx")` errors if "xxxx" isn't defined. This breaks things (like the ability to run migrations locally).
I don't think it's a problem if we don't specify these geocoder env variables. When the geocoder is run it will error because a key isn't defined.
I suppose we could define a maxmind key stub, but it seems unnecessary?
=> Stop fetching env variables because it's blocking

app/controllers/bikes_controller.rb, app/views/bikes/edit_groups.html.haml, spec/controllers/bikes_controller_spec.rb
If no organizations were checked, the key wasn't present so it wouldn't update the organizations.
Fix that
=> Enable removing all organizations can edit

app/assets/stylesheets/revised/pages/landing/_packages.scss
=> Fix text breaking out of container at medium breakpoint

app/models/customer_contact.rb, db/migrate/20190916190441_add_info_hash_json_to_customer_contacts.rb, db/migrate/20190916190441_rename_info_hash_to_info_hash_text_on_customer_contacts.rb, db/structure.sql, lib/tasks/data_migrations.rake, spec/models/customer_contact_spec.rb
- Sets `creator` prior to saving, if `creator_email` is found
- Renames `info_hash` column to `info_hash_text`
- Adds a JSONB `info_hash` column to store any new entries as JSONB
- Adds temporary methods to customer_contact for backwards compatibility
- Adds a data migration task to copy `info_hash_text` (yaml) to `info_hash`
(follow-on work will drop in https://github.com/bikeindex/bike_index/pull/1265 `info_hash_text and kill backwards-compatibility code)
=> Refactor CustomerContact

app/models/customer_contact.rb, db/migrate/20190916190442_drop_info_hash_text_from_customer_contacts.rb, db/structure.sql
- Drop `info_hash_text`
- Kill temp methods and `serialize` invocation in `CustomerContact` 
```
jake6001@hawk:/var/deploy/bike_index/web_head/current$ bin/rake data:migrate_info_hash:up
Updating 46942 customer_contact records...
46942/46942 : 100.0%
Done!
```
=> Refactor CustomerContact (2)

app/controllers/admin/customer_contacts_controller.rb, app/controllers/api/v1/notifications_controller.rb, app/models/customer_contact.rb, app/views/admin/stolen_bikes/edit.html.haml, app/workers/approve_stolen_listing_worker.rb, config/locales/en.yml, db/migrate/20190918121951_add_kind_to_customer_contacts.rb, db/structure.sql, lib/tasks/data_migrations.rake, spec/controllers/admin/customer_contacts_controller_spec.rb, spec/factories.rb, spec/mailers/customer_mailer_spec.rb, spec/mailers/previews/customer_mailer_preview.rb
- Adds a `kind` enum to `CustomerContact`
- Adds a data migration to populate `kind` with an appropriate mapping from `contact_type`
- Adds logic to keep `contact_type` and `kind` in sync until the former is dropped
```
bin/rake data:migrate_customer_contact_types:up
```
=> Migrate customer_contacts.contact_type to kind enum

app/assets/stylesheets/revised/pages/news/index.scss, app/controllers/admin/news_controller.rb, app/controllers/news_controller.rb, app/helpers/application_helper.rb, app/models/blog.rb, app/views/admin/news/edit.html.haml, app/views/admin/news/index.html.haml, app/views/admin/news/new.html.haml, app/views/news/index.html.haml, db/migrate/20190919145324_add_language_to_blogs.rb, db/structure.sql, spec/controllers/admin/news_controller_spec.rb, spec/controllers/news_controller_spec.rb, spec/factories.rb
- Adds a `language` attribute to `Blog`, defaulting to English
- `blogs.language` enum includes only current locale languages
- Adds a drop-down to the public-facing blog index to select posts in other languages
- Current blog language defaults to the user's current locale
- Changing blog language doesn't change the user's current locale
=> Add language to blog posts

app/models/bike.rb, app/services/serial_normalizer.rb, spec/models/bike_spec.rb, spec/services/serial_normalizer_spec.rb, spec/workers/bulk_import_worker_spec.rb
- Sanitizes non-standardized forms of "made_without_serial"
- Adds a `before_save` hook to ensure the three components of "unknown" / "made_without_serial" / neither state are kept consistent with each other.
Resolves #1277
=> Add bike no-serial sanitizing

app/controllers/admin/twitter_accounts_controller.rb, app/models/twitter_account.rb, app/views/admin/twitter_accounts/_form.html.haml, spec/controllers/admin/twitter_accounts_controller_spec.rb
I'm not sure what to make of this line in [twitter_account.rb](https://github.com/bikeindex/bike_index/blob/master/app/models/twitter_account.rb#L83):
```ruby
clear_error if twitter_client.verify_credentials.present?
```
I would like to add a checkbox to the admin page to `check_credentials`, but I don't want to mess with this line because I'm not sure why it's there. I don't understand why we wouldn't always clear the error before running `check_credentials`
It doesn't seem like anything in the app calls `check_credentials` anyway though?
=> Twitter account remove error on update

app/models/customer_contact.rb, spec/factories.rb, spec/models/customer_contact_spec.rb
Adds lower-level tests for `CustomerContact.possibly_found_notification_sent?`, adds a guard clause. Used in `EmailBikePossiblyFoundNotificationWorker` to prevent re-sending notices:
```rb
Bike.possibly_found_with_match.each do |bike, match|
next if CustomerContact.possibly_found_notification_sent?(bike, match)
```
<sup>[[source](https://github.com/bikeindex/bike_index/blob/ad0842fd/app/workers/email_bike_possibly_found_notification_worker.rb#L13-L14)]</sup>
```rb
it "skips the bike if a notification for it has already been sent" do
bike = FactoryBot.create(:stolen_bike, abandoned: false, serial_number: "HELL0")
match = FactoryBot.create(:abandoned_bike, stolen: false, serial_number: "HE11O")
contact = CustomerContact.build_bike_possibly_found_notification(bike, match)
contact.email = …
```
=> Refactor CustomerContact.possibly_found_notification_sent?

app/models/bike.rb, spec/factories.rb, spec/factories/bikes.rb, spec/factories/countries.rb, spec/factories/stolen_records.rb, spec/mailers/customer_mailer_spec.rb, spec/models/bike_spec.rb, spec/workers/email_admin_contact_stolen_worker_spec.rb, spec/workers/email_stolen_bike_alert_worker_spec.rb
Introduces `Bike.currently_stolen_in` to query for bikes with currently stolen records in the given location (passed as city / state / country, matched conjointly).
Will be used to find currently stolen in NL to check against the VOG registry.
Extracted from #1280
=> Add Bike.currently_stolen_in

app/assets/stylesheets/revised/sections/bike_boxes.scss
Minimally fixes sizing of bike search listing images across browsers
=> Fix bike search listing images

app/models/external_registries/stop_heling_client.rb
- Uses today's date in Amsterdam when computing the HMAC hash for connecting 
Potential fix for https://app.honeybadger.io/projects/35931/faults/54723228
=> Use CEST+2 TZ in hmac date

app/workers/deactivate_expired_theft_alert_worker.rb, app/workers/email_bike_possibly_found_notification_worker.rb, app/workers/file_cache_maintenance_worker.rb, app/workers/scheduled_worker_recorder.rb, app/workers/update_counts_worker.rb, app/workers/update_expired_invoice_worker.rb, app/workers/update_organization_pos_kind_worker.rb
- Introduces `ScheduledWorkerRecorder`, which can be prepended to record start/stop of the worker's `perform` method
- `record_scheduler_started`/`record_scheduler_finished` can still be used where greater customization is needed
=> Add ScheduledWorkerRecorder

app/assets/javascripts/init.coffee, app/javascript/packs/external_registry_search/components/ExternalRegistrySearch.js, app/javascript/packs/external_registry_search/components/ExternalRegistrySearchResult.js, app/jest/setup.js, app/serializers/bike_v2_serializer.rb, app/serializers/external_bike_v3_serializer.rb, spec/requests/api/v3/search_request_spec.rb, spec/serializers/bike_v2_show_serializer_spec.rb, spec/workers/file_cache_maintenance_worker_spec.rb
- Drops `date_stolen_string` from bike serializers
- Uses `TimeParser` to convert times rendered using React (assuming `BikeIndex.Init` is vintage? Happy to update it to match if not)
=> Drop date_stolen_string from bike serializers

app/javascript/packs/external_registry_search/components/ExternalRegistrySearchResult.js, app/models/external_registries/verloren_of_gevonden_result.rb
Updates `image_url` for VOG bikes (VOG has changed the endpoint from which it renders bike images).
Before:
After:
Hotfixing since this is broken on prod
=> Update VOG image url

app/javascript/packs/external_registry_search/components/ExternalRegistrySearchResult.js
Fixes the fix in #1300 
`data-img-src` is used by the jQuery that runs on the page
=> Restore data-img-src for bike image expansion

app/assets/stylesheets/revised/sections/bike_boxes.scss, app/controllers/bikes_controller.rb, app/decorators/application_decorator.rb, app/javascript/packs/api.js, app/javascript/packs/external_registry_search/components/ExternalRegistrySearch.js, app/javascript/packs/external_registry_search/components/ExternalRegistrySearchResult.js, app/javascript/packs/partial_serial_search/components/PartialSerialSearch.js, app/javascript/packs/partial_serial_search/components/PartialSerialSearchResult.js, app/javascript/packs/partial_serial_search/index.js, app/models/stolen_record.rb, app/serializers/bike_v2_serializer.rb, app/serializers/stolen_record_v2_serializer.rb, app/views/bikes/_bike.html.haml, app/views/bikes/index.html.haml, app/views/welcome/user_home.html.haml, config/locales/en.yml, spec/controllers/bikes_controller_spec.rb, spec/factories/stolen_records.rb, spec/models/stolen_record_spec.rb, spec/serializers/bike_v2_show_serializer_spec.rb
Refactors close-serials search results to render asynchronously on page load
=> Render close serials asynchronously 

app/javascript/packs/external_registry_search/index.js, app/javascript/packs/partial_serial_search/index.js
Resolves https://app.honeybadger.io/projects/61305/faults/54294090
> Target container is not a DOM element.
=> Don't render search components if id not present

app/decorators/bike_decorator.rb, app/helpers/header_tag_helper.rb, spec/decorators/bike_decorator_spec.rb
- No externalizations needed for decorators — all methods with user-facing strings aren't called anywhere. 
- Externalizes one last string from header_tag_helper
Tracking #963
=> Kill unused decorator methods

app/javascript/packs/partial_serial_search/components/PartialSerialSearchResult.js
Replaces the alt text for partial serial search result images from `description` to `title`, which is more succinct. Some descriptions are very long. Also matches what we use on server-rendered bike templates.
=> Use title not description for alt text

app/controllers/application_controller.rb, app/controllers/bike_codes_controller.rb, app/controllers/bikes/recovery_controller.rb, app/controllers/bikes_controller.rb, app/controllers/concerns/controller_helpers.rb, app/controllers/feedbacks_controller.rb, app/controllers/integrations_controller.rb, app/controllers/locks_controller.rb, app/controllers/oauth/applications_controller.rb, app/controllers/organizations_controller.rb, app/controllers/public_images_controller.rb, app/controllers/sessions_controller.rb, app/controllers/stolen_notifications_controller.rb, app/controllers/theft_alerts_controller.rb, app/controllers/welcome_controller.rb, config/locales/en.yml
- Externalizes flash strings from ~half our controllers
- Deepens `ControllerHelpers#translation` so it infers the method invoking it rather than the controller action in which it's invoked. This is useful because a private helper method or before action can be invoked in the context of multiple controller actions but we need a 1:1 mapping from call site to translation file key. 
```rb
def translation(key, scope: nil, controller_method: nil, **kwargs)
if scope.blank? && controller_method.blank?
controller_method =
caller_locations
.slice(0, 2)
.map(&:label)
.reject { |label| label =~ /rescue in/ }
.first
end
scope ||= [:controllers, controller_namespace, controller_name, controller_method.to_sym]
I18n.t(key, kwargs, scope: scope.compact)
end
``` …
=> Externalize controller flash strings

app/controllers/admin/external_registry_bikes_controller.rb, app/helpers/admin_helper.rb, app/views/admin/external_registry_bikes/_table.html.haml, app/views/admin/external_registry_bikes/index.html.haml, app/views/admin/external_registry_bikes/show.html.haml, config/routes.rb
Adds admin views for external registry bikes (minimally, index and show)
=> Add admin management of external registry bikes

app/controllers/admin/external_registry_bikes_controller.rb, app/views/admin/external_registry_bikes/_table.html.haml, spec/controllers/users_controller_spec.rb
- Fixes sorting and filtering on external registry bikes admin dashboard.
- Fixes a test in the `nl` locale, which now renders flash messages in Dutch.
=> Fix sorting and filtering of admin external bikes

app/controllers/application_controller.rb, app/views/bikes/edit_alert.html.haml, app/views/bikes/index.html.haml, spec/requests/locale_detection_request_spec.rb
- Only forward the `:locale` param in form submissions if it's currently set
- For robustness, when detecting locale from params hash, prefer `params[:locale].to_s` to `params.fetch(:locale, "")`, since the latter will only fall back to the default value if the key is missing, not if the locale value is blank.
Resolves https://app.honeybadger.io/projects/35931/faults/55913724
=> Consistify locale param forwarding

app/mailers/customer_mailer.rb, app/views/customer_mailer/stolen_bike_alert_email.html.haml, app/views/customer_mailer/stolen_bike_alert_email.text.haml, config/locales/en.yml
Updates stolen bike alert email to account for `CustomerContact` records with no "tweet_string" stored in their info_hash.
When no tweet string is available, link directly to the tweet rather than displaying a preview:
Resolves: https://app.honeybadger.io/projects/35931/faults/54852624
=> Fix stolen bike alert email with no tweet string

app/controllers/admin/stolen_bikes_controller.rb, app/views/admin/bikes/_theft_alert_images.html.haml, app/views/admin/stolen_bikes/edit.html.haml, app/views/shared/_modal.html.haml
Adds a modal to the stolen bikes and theft alert admin dashboards to select an image to use for a theft alert.
Fixes #1285
=> Allow selection of bike photo for promoted alert image

yarn.lock
Ran `yarn upgrade` to address security vulnerability warnings.
```
16242 vulnerabilities found - Packages audited: 872307
Severity: 2 Low | 16238 High | 2 Critical
✨  Done in 32.15s.
```
```
3 vulnerabilities found - Packages audited: 897303
Severity: 2 Low | 1 High
✨  Done in 3.13s.
```
=> Bring yarn dependencies up-to-date

.babelrc, .circleci/config.yml
The builds on `master` are failing because assets built pre-#1339 are cached and the cache key is unaffected by changes to yarn.lock. 
This patch:
- Adds an env-settable `CACHE_VERSION` value to cache keys
- Resolves a warning about implicit core-js version in babelrc 42636e7
```
% bundle exec rake assets:precompile
Compiling…
Compilation failed:
WARNING: We noticed you're using the `useBuiltIns` option without declaring a
core-js version. Currently, we assume version 2.x when no version is passed.
Since this default version will likely change in future versions of Babel, we
recommend explicitly setting the core-js version you are using via the `corejs`
option.
You should also be sure that the version you pass to the `corejs` option matches
the version specified in your `package.json`'s …
```
=> Fix asset compilation on CircleCI 

Gemfile.lock
Addresses https://github.com/bikeindex/bike_index/network/alert/Gemfile.lock/rubyzip/open
```
Name: rubyzip
Version: 1.2.3
Advisory: CVE-2019-16892
Criticality: Unknown
URL: https://github.com/rubyzip/rubyzip/pull/403
Title: Denial of Service in rubyzip ("zip bombs")
Solution: upgrade to >= 1.3.0
```
=> Bump rubyzip to 1.3.0

app/assets/stylesheets/revised/pages/bikes/edit_alert.scss, app/views/bikes/edit_alert.html.haml, config/locales/en.yml
Since users will be channeled toward activating a promoted alert when reporting a bike as stolen, it's more likely they'll encounter the promoted alert preview before having set the stolen location on the theft_details page. 
This change displays the placeholder location to give a more accurate sense of what the promoted alert will look like.
=> Use placeholder location in promoted alert preview

app/models/external_registry_bike.rb, app/models/external_registry_client/project529_client.rb, app/models/external_registry_client/stop_heling_client.rb, app/models/external_registry_client/verloren_of_gevonden_client.rb, spec/models/external_registry_bike_spec.rb
Adds a presence validation for normalized serial number to `ExternalRegistryBike`.
Resolves https://app.honeybadger.io/projects/35931/faults/56107532
=> Add normalized serial presence validation

.gitignore, Gemfile, Gemfile.lock, app/javascript/packs/external_registry_search/components/ExternalRegistrySearchResult.js, app/javascript/packs/partial_serial_search/components/PartialSerialSearchResult.js, app/jest/setup.js, app/models/external_registry_bike.rb, app/views/layouts/application.html.haml, config/application.rb, config/i18n-js.yml, config/i18n-tasks.yml, config/initializers/assets.rb, config/locales/en.yml, config/locales/translation.nl.yml, lib/tasks/rake_tasks.rake, package.json, yarn.lock
Adds [i18n-js](https://github.com/fnando/i18n-js) ruby gem and npm package to generate client-side translations from the Rails translation file.
1. Initialize a `t()` translation helper function with the appropriate keyspace for the given module. For example, for `ExternalRegistrySearchResult`, we can either invoke `I18n.t` with a full scope or use the following:
```js
// app/javascript/packs/external_registry_search/components/ExternalRegistrySearchResult.js L9 (5364dea1)
const t = BikeIndex.translator("bikes_search");
```
<sup>[[source](https://github.com/bikeindex/bike_index/blob/5364dea1/app/javascript/packs/external_registry_search/components/ExternalRegistrySearchResult.js#L9-L9)]</sup>
```js
// app/javascript/packs/external_registry_search/components/ExternalRegistrySearchResult.js …
```
=> Add client-side translation facilities, localize Bike search components

Gemfile
Resolves deploy failure
```
[147.75.69.187] executing command
rake aborted!
NameError: uninitialized constant I18n::JS
/var/deploy/bike_index/web_head/releases/20191021230451/config/application.rb:48:in `'
/var/deploy/bike_index/web_head/releases/20191021230451/config/application.rb:11:in `'
/var/deploy/bike_index/web_head/releases/20191021230451/config/application.rb:10:in `'
/var/deploy/bike_index/web_head/releases/20191021230451/Rakefile:5:in `require'
/var/deploy/bike_index/web_head/releases/20191021230451/Rakefile:5:in `'
/var/deploy/bike_index/web_head/shared/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `'
(See full trace by running task with --trace)
command finished in 3207ms
*** [deploy:update_code] rolling …
```
=> Move i18n-js out of dev group

app/controllers/admin/paid_features_controller.rb, app/controllers/admin/payments_controller.rb, app/controllers/admin/theft_alert_plans_controller.rb, app/helpers/money_helper.rb, app/views/admin/paid_features/_form.html.haml, app/views/admin/payments/new.html.haml, app/views/admin/theft_alert_plans/_form.html.haml, app/views/admin/theft_alert_plans/index.html.haml
Adds form fields to allow setting / updated the currency column value from the admin dashboard.
=> Add currency form fields to admin dashboards

.env, app/controllers/concerns/controller_helpers.rb, app/controllers/concerns/sessionable.rb, app/views/users/new.html.haml
Extracts a `bikehub_url` helper with env-settable bikehub url. Allows for overriding with `localhost` when needed.
=> Extract bikehub_url helper, env var

app/controllers/bikes_controller.rb, app/views/bikes/edit_alert_purchase.html.haml, spec/controllers/bikes_controller_spec.rb
The exception in https://github.com/bikeindex/bike_index/pull/1372 was enabled by an oversight on my part — the second- and third-stage alert purchase templates aren't included in `BikesController#edit_templates`, so they weren't being exercised by tests. 
This line replaces the relevant line with 
```rb
templates = bc.edit_templates.keys.concat(["alert_purchase", "alert_purchase_confirmation"])
```
to reproduce https://github.com/bikeindex/bike_index/pull/1372.
=> Add tests for subsequent alert purchase stages

app/assets/stylesheets/revised/pages/landing/_home.scss, app/assets/stylesheets/revised/sections/primary_header_nav.scss
Fixes #1371 
Adds spacing to let the non-profit copy breathe when the nav bar is compressed:
=> Fix mobile layout to accommodate translated copy

app/models/organization.rb, app/views/bikes/bike_fields/_revised_colors.html.haml, app/views/bikes/new.html.haml, app/views/organizations/embed_extended.html.haml, config/locales/.translation_io, config/locales/en.yml, config/locales/translation.nl.yml
Translates some strings that were missed on a first pass because they're generated dynamically.
=> Add translations for new bike form

app/controllers/admin/external_registry_credentials_controller.rb, app/views/admin/external_registry_credentials/_form.html.haml, app/views/admin/external_registry_credentials/edit.html.haml
Hotfix to enable updating StopHeling creds
- Fixes a typo in the update form's url helper
- Sets the STI model key based on the `type` field
=> Fix external credentials updating 

app/views/organized/bikes/index.html.haml, app/views/organized/manage/index.html.haml, app/views/organized/stickers/index.html.haml
A few urls in organized pages used id rather than the slug. Update them!
=> Use to_param for organized links

app/controllers/admin/news_controller.rb, app/helpers/application_helper.rb, app/models/blog.rb, app/views/admin/news/edit.html.haml, app/views/layouts/application.html.haml, app/views/news/show.html.haml, db/migrate/20191028130015_add_canonical_url_to_blog.rb, db/structure.sql, spec/models/blog_spec.rb
- Adds `canonical_url` to blog model
- Renders canonical url in the header for blog posts
- Adds field to blog edit form
=> Add canonical_url to blog posts

app/controllers/admin/twitter_accounts_controller.rb, app/models/twitter_account.rb, app/views/admin/twitter_accounts/_errored.html.haml, app/views/admin/twitter_accounts/edit.html.haml, app/views/admin/twitter_accounts/show.html.haml, spec/factories/twitter_accounts.rb, spec/models/twitter_account_spec.rb
- Adds a "log in to refresh credentials" button to the admin/twitter_accounts#show template
- Updates the credentials on any pre-existing record and re-verifies credentials to clear errors
=> Automate twitter accounts credential refresh

app/javascript/packs/api.js, app/javascript/packs/close_serial_search/components/CloseSerialSearch.js, app/javascript/packs/close_serial_search/components/CloseSerialSearchResult.js, app/javascript/packs/close_serial_search/index.js, app/views/bikes/index.html.haml
- Renames what was formerly `PartialSerialSearch` to `CloseSerialSearch` so it mirrors the API endpoint name
Extracted from #1387
=> Rename PartialSerialSearch -> CloseSerialSearch

app/models/external_registry_client.rb, app/models/external_registry_client/stop_heling_client.rb, app/models/external_registry_client/verloren_of_gevonden_client.rb, spec/models/external_registry_client/stop_heling_client_spec.rb, spec/models/external_registry_client/verloren_of_gevonden_client_spec.rb
In order to minimize simultaneous database connections, this patch updates external registry querying logic to defer persistence of external registry results until after the threads searching those external registries are joined.
```rb
results =
registries
.flat_map { |registry| queries.map { |q| [registry, q] } }
.map { |registry, q| Thread.new { registry.new.search(q) } }
.flat_map(&:value)
.compact
.each(&:save)
.select(&:persisted?)
```
<sup>[[source](https://github.com/bikeindex/bike_index/blob/8afac065/app/models/external_registry_client.rb#L20-L27)]</sup>
Related:
https://app.honeybadger.io/projects/35931/faults/56518719
https://app.honeybadger.io/projects/35931/faults/55996932
https://app.honeybadger.io/projects/35931/faults/50925427
Closes: …
=> Defer persistence until after joining threads

app/assets/javascripts/application_revised.js, app/javascript/packs/bikes_search/components/BikeSearch.js, app/views/layouts/application.html.haml, config/application.rb
- Switches to using the asset pipeline for JS translations (in an attempt to work around what may be browser caching preventing updates of translations.js)
- Fixes coloring of results headers when no results found
=> Add JS translations

app/javascript/packs/bikes_search/components/BikeSearch.js
Fixes a stray semicolon in `BikesSearch.render`:
```js
<Loading />;
```
=> Kill stray semicolon in render call

app/models/external_registry_client/verloren_of_gevonden_client.rb
Fixes a bug whereby serial numbers with letters in them weren't being matched against bikes that by the VOG endpoint, which expects any letters in lower case.
=> Downcase VOG queries

app/models/organization.rb, app/views/organized/dashboard/index.html.haml
Adds counts of bikes within regional sub-organizations and within `search_radius` miles of the `Organization#search_location`
```rb
@bikes_in_region_count = {
in_organizations: bikes_in_orgs.count,	      
in_region: bikes_in_region.count,
in_region_unaffiliated: (bikes_in_region - bikes_in_orgs).count,	      
all: (bikes_in_orgs + bikes_unaffiliated).count,
}	    
```
=> Add regional organization data to organized dashboard

app/models/bike.rb, app/models/concerns/geocodeable.rb, app/models/location.rb, app/models/mail_snippet.rb, app/models/organization.rb, app/models/stolen_record.rb, app/models/twitter_account.rb, app/models/user.rb, app/workers/after_user_create_worker.rb, spec/factories/locations.rb, spec/factories/stolen_records.rb, spec/workers/after_user_create_worker_spec.rb
- Adds a `Geocodable` concern to reduce some duplication and consistify across geocoded models.  
- Expects `geocode_data` to be defined on the including model
=> Extract Geocodeable mixin

app/models/bike.rb
Hotfix to only make an API request when adding lat/long to a bike  record if `geocode_data` is present, otherwise a 400 error will be returned:
```
$ bin/rake data:set_bike_location_info
Geocoded bikes: 0
Un-geocoded bikes: 294,849
Setting coordinates on stolen bikes:
------------------------------------
Updated 69,774 stolen bikes
Geocoded bikes: 69,774
Un-geocoded bikes: 225,075
Setting coordinates on non-stolen bikes:
----------------------------------------
Geocoding API error: 400 Bad Request
Google Geocoding API error: invalid request.
Geocoding API error: 400 Bad Request
Google Geocoding API error: invalid request.
51,285/225,075 :    22.8%
```
=> Fix Bike#should_be_geocoded?

app/models/bike.rb, config/locales/en.yml, db/migrate/20191117123105_drop_stolen_lat_long_from_bikes.rb, db/structure.sql, spec/models/bike_spec.rb, spec/support/shared_examples/bike_searchable.rb
This patch drops `bikes.stolen_lat` and `bikes.stolen_long` — the values for these have been copied to the `latitude` and `longitude` columns.
=> Remove Bikes stolen lat/long fields

app/views/organized/dashboard/_regional_bike_counts.html.haml, app/views/organized/dashboard/index.html.haml
Also re-labels "associated organizations" "child organizations" for clarity:
=> Sort nearby organizations list

app/models/bike.rb, spec/models/bike_spec.rb
[Request geocoding](https://github.com/alexreisner/geocoder#custom-result-handling) exposes a `postal_code` attribute rather than `zipcode`.
Fixes https://app.honeybadger.io/projects/35931/faults/57560267
=> Fix request location zipcode access

config/locales/en.yml
Update UI to use "postal code" consistently instead of "zip code".
=> Use 'postal code' in UI

app/views/customer_mailer/bike_possibly_found_email.html.haml, app/views/customer_mailer/bike_possibly_found_email.text.haml, config/locales/en.yml
When notifying a bike owner of a potential match found in an external registry, link directly to the external registry url.
=> Link directly to external registry bike

app/assets/javascripts/revised/pages/info/payments.coffee, app/assets/javascripts/revised/pages/welcome/index.coffee, app/views/payments/_form.html.haml, app/views/welcome/index.html.haml, config/locales/.translation_io, config/locales/en.yml, config/locales/translation.nl.yml
This patch updates the donation modals and associated coffeescript with the following changes:
- Scales arbitrary amounts by 100 since Stripe expects cents (minimum possible Stripe purchase is $0.50)
- Externalizes strings and localizes currency
- Sets the arbitrary currency step size to 1 (which lets the browser do some validation)
Also fixes inconsistent indentation in welcome/index.coffee
Fixes https://app.honeybadger.io/projects/35931/faults/57750107#notice-params
=> Fix coffeescript indentation, donation modal bug

app/controllers/concerns/controller_helpers.rb, app/controllers/concerns/sessionable.rb, spec/controllers/sessions_controller_spec.rb
Testing not removing the `session[:partner]` because we aren't redirecting all the time.
After shipping, will need to uncomment the places where tests are commented out with
```ruby
```
=> Stop removing partner from session

.circleci/config.yml
Adds submodule support to the Git we use on CI. (Submodule support is needed when a gem fetch from GitHub contains submodules we also want to fetch.)
Extracted from #1428
=> Build CI Git with submodules

app/workers/email_admin_contact_stolen_worker.rb, app/workers/email_bike_possibly_found_notification_worker.rb, app/workers/email_confirmation_worker.rb, app/workers/email_invoice_worker.rb, app/workers/email_lightspeed_notification_worker.rb, app/workers/email_magic_login_link_worker.rb, app/workers/email_no_admins_notification_worker.rb, app/workers/email_organization_message_worker.rb, app/workers/email_ownership_invitation_worker.rb, app/workers/email_partial_registration_worker.rb, app/workers/email_reset_password_worker.rb, app/workers/email_stolen_notification_worker.rb, app/workers/email_updated_terms_worker.rb, app/workers/email_welcome_worker.rb
Notifications for possibly-found bikes are currently not being triggered (or so it seems). 
Stepping through the logic manually, we don't run into any failures, so the issue may be with enqueuing. 
What may be happening is that notifications just taking a long time to be triggered because their job is on the low priority queue. Most notifications are on "notify". 
This patch updates `EmailBikePossiblyFoundNotificationWorker` to be performed on the "notify" queue. (a53db84af0e00ffeb1e929061bfece39a25b9e1b)
=> Move BikePossiblyFound notification to the notifications queue

Gemfile, Gemfile.lock
Drops the "therubyracer" gem, since it's not needed anymore (since we ) and [consumes excess memory](https://devcenter.heroku.com/articles/rails-asset-pipeline#therubyracer). I'd like to see if this improves the asset compilation failures on `master` builds.
=> Drop therubyracer

app/mailers/admin_mailer.rb, app/mailers/application_mailer.rb, app/mailers/customer_mailer.rb, app/mailers/organized_mailer.rb
- Updates mailers to inherit from an `ApplicationMailer` base class
- Moves common macro-style methods to the base class
Extracted from #1426
=> Add ApplicationMailer base class

app/views/organized/exports/show.html.haml, config/locales/.translation_io, config/locales/translation.nl.yml
Update translation key `bike_code_kind` and sync translations
Fixes https://app.honeybadger.io/projects/35931/faults/59298881
Related #1460
=> Fix bike_code translation interpolation key

app/services/bike_creator.rb, app/workers/bike_book_update_worker.rb
`lib` directory is no longer autoloaded in Rails 5 (not thread-safe).
Repro locally with 
```diff
+++ b/config/environments/test.rb
@@ -10,7 +10,7 @@ Rails.application.configure do
-  config.eager_load = false
+  config.eager_load = true
```
This is a hotfix for bike creator
=> Hotfix: Fix bike creator require

app/workers/approve_stolen_listing_worker.rb
Manually require module in `lib`. Hotfixing for now.
=> Hotfix: Require twitter_tweeter_integration

app/views/bikes/_stolen_checklist.html.haml
The stolen bike checklist uses path helpers, which don't generate usable links in mailer views.
Rails 5 makes path helpers unavailable in mailer views altogether.
This patch updates the stolen bike checklist to use url helpers instead.
Resolves https://app.honeybadger.io/projects/35931/faults/60150754
There are no other occurrences in mailer views, so this also fixes https://github.com/bikeindex/bike_index/issues/1485
```
views % cd admin_mailer
admin_mailer % ag '_path'
admin_mailer % cd ../customer_mailer
customer_mailer Fix-edit_bike_path-in-mailer-view % ag '_path'
updated_terms_email.html.haml
13:        - if @organization.present? && controller_path == 'organized_mailer' && @organization.mail_snippet_body('header').present?
customer_mailer % cd ../organized_mailer
organized_mailer % …
```
=> Use url instead of path helper in mailer view

app/models/user.rb, config/initializers/admin_restriction.rb, config/initializers/cookies_serializer.rb
Attempting to access admin pages gated by `AdminRestriction` fails currently because newly created (post-upgrade) cookies need to be decoded with `Rack::Session::Cookie::Base64::JSON`. 
Fixes https://github.com/bikeindex/bike_index/issues/1489
=> Fix AdminRestriction#matches?

app/models/abandoned_record.rb, app/services/bike_creator_associator.rb, config/locales/en.yml, spec/models/abandoned_record_spec.rb, spec/requests/organized/abandoned_records_request_spec.rb
- Drops an unused key dropped in #1493 (reintroduced by a merge conflict resolution maybe?)
- Updates implementation code to pass tests failing on master
Note: this patch updates the abandoned record implementation code to return an address in a format normalized on what's pre-existing in the code (necessary since the model and request spec test have incompatible expectations of the address format — in particular, one expects a comma between a state and zip code, the other no comma).
=> Fix failing build on master

config/environments/production.rb
This patch sets the prod log level to `:info` — the Rails 5 upgrade overrode this setting.
```rb
config.lograge.enabled = true
config.log_level = :info
```
<sup>[[source](https://github.com/bikeindex/bike_index/blob/c3b29332/config/environments/production.rb#L5-L8)]</sup>
=> Set production log level to info

app/views/shared/_email_bike_box.html.haml
A stolen bike occasionally has no current_stolen_record—L33 will raise an exception in those cases. 
This patch adds a check for `@bike.current_stolen_record.present?` to the conditional guarding that invocation.
We could alternatively / additionally save the bike record to ensure an available CSR is set before checking `@bike.current_stolen_record.present?`
```haml
-# app/views/shared/_email_bike_box.html.haml L28-37 (5ec54ad6)
- if @bike.stolen && @bike.current_stolen_record.present?
- stolen_record = @bike.current_stolen_record
%li
%strong
= @bike.abandoned ? t(".found") : t(".stolen_from")
= stolen_record.address(skip_default_country: true)
%li
%strong
= t(".date")
= l stolen_record.date_stolen, format: :dotted
```
<sup>[[source](https://github.com/bikeindex/bike_index/blob/5ec54ad6/ap …
=> Fix nil method call exception in the bike box template

Gemfile.lock, app/javascript/packs/application_css.scss, app/models/user.rb, app/views/layouts/admin.html.haml, app/workers/after_user_create_worker.rb, spec/controllers/users_controller_spec.rb, spec/models/user_spec.rb, spec/workers/after_user_create_worker_spec.rb
Because of the calculations that were being done inline for users, signup was taking a _long_ time. This was causing a number of issues.
This PR moves some of the calculations to async jobs and simplifies others.
=> Improve signup speed

app/views/admin/bikes/_theft_alert_images.html.haml, db/structure.sql
This patch ensures `image_tag` receives a string if `image.url` isn't yet available.
Exception: https://app.honeybadger.io/projects/35931/faults/61449218
=> Fix nil image_tag url exception

app/models/blog.rb, app/models/user.rb, app/services/urlifyer.rb, spec/models/blog_spec.rb, spec/services/urlifyer_spec.rb
Validation failed for `https://www.usacycling.org/article/in-our-own-words-lily-williams-olympic-postponement` - and didn't give info as to why it was failing.
Rather than validate, coerce using existing `Urlifyer` method.
=> Better handling for canonical urls in blogs

app/models/country.rb, app/models/twitter_account.rb, app/views/admin/twitter_accounts/index.html.haml, db/migrate/20200414055431_drop_state_and_country_from_twitter_accounts.rb, db/structure.sql
Drops the `state` and `country` columns from `twitter_accounts`, which are replaced by foreign keys in PR #1546. 
The data migration in #1546 should be completed on prod before this PR is merged into master.
=> Drop twitter_accounts country and state fields

app/views/bikes/show.html.haml
This patch updates the bikes#show template to check for the presence of `image_url`s when rendering. `image_tag` raises an exception when passed `nil`, and until recently some image records (4) were missing an associated `image_url` (only one had an associated bike).
related: https://app.honeybadger.io/projects/35931/faults/62869392
=> Check for presence of an image before rendering

app/controllers/api/v3/search.rb, spec/requests/api/v3/manufacturers_request_spec.rb, spec/requests/api/v3/search_request_spec.rb
Thanks to @catdoch for the heads up that this was missing!
This will fix #1573 once merged
=> Add cors to v3 search

app/views/bikes/show.html.haml, app/views/sessions/new.html.haml
Fixes #1445
- On https://github.com/bikeindex/bike_index/blob/master/app/controllers/concerns/controller_helpers.rb#L117 it expects a string starting with `BASE_URL` or `/`.  So, just adding a `/` on the `data-redirect` attribute, already redirects the user without any other change.
- In order to redirect the user even when the password fails, I merged the `return_to` param on the login form path. So when the login fails, the `redirect_to` is not lost.
=> Redirect after sign in to bike for writing message

app/controllers/admin/exchange_rates_controller.rb, app/controllers/application_controller.rb, app/helpers/admin_helper.rb, app/helpers/money_helper.rb, app/models/exchange_rate.rb, app/models/exchange_rate_api_client.rb, app/services/exchange_rate_updator.rb, app/views/admin/exchange_rates/_form.html.haml, app/views/admin/exchange_rates/edit.html.haml, app/views/admin/exchange_rates/index.html.haml, app/views/admin/exchange_rates/new.html.haml, app/workers/scheduled_worker_runner.rb, app/workers/update_exchange_rates_worker.rb, config/routes.rb, db/migrate/20200517001632_create_exchange_rates.rb, db/structure.sql, lib/tasks/rake_tasks.rake, spec/factories.rb, spec/helpers/money_helper_spec.rb, spec/models/exchange_rate_api_client_spec.rb, spec/models/exchange_rate_spec.rb, spec/requests/admin/exchange_rates_request_spec.rb, spec/requests/locale_detection_request_spec.rb, spec/vcr_cassettes/ExchangeRateApiClient/_latest/returns_a_hash_with_base_and_rates_keys.yml
This patch implements a lingering `Money`-related `TODO` from `MoneyHelper`, adding a currency conversion backend that updates an `exchange_rates` table daily.
```rb
class UpdateExchangeRatesWorker < ScheduledWorker
prepend ScheduledWorkerRecorder
sidekiq_options queue: "low_priority", retry: false
def self.frequency
1.day
end
def perform
ExchangeRateUpdator.update
end
end
```
<sup>[[source](https://github.com/bikeindex/bike_index/blob/9e2c8b56/app/workers/update_exchange_rates_worker.rb#L3-L14)]</sup>
```rb
class ExchangeRateUpdator
def self.update
payload = ExchangeRateApiClient.new.latest
rates = payload.fetch(:rates)
base_iso = payload.fetch(:base)
results = rates.map do |target_iso, multiplier|
ExchangeRate.add_rate(base_iso, target_iso, multiplier)
end
results.none?(&:nil?)
end
end …
```
=> Add exchange rate model for currency conversions

app/controllers/sessions_controller.rb, app/views/sessions/magic_link.html.haml, config/locales/.translation_io, config/locales/en.yml, config/locales/translation.nl.yml, config/routes.rb, spec/controllers/sessions_controller_spec.rb
Turns out, some email clients visit the links prior to the user visiting them.
Since signing in expires the link, we need to make sure merely loading the link doesn't expire the URL.
This will probably need to be done for other links - e.g. abandoned bike recovery, graduated bikes, maybe even password reset
=> Use a form post JS submission

app/views/admin/bikes/edit.html.haml, app/views/admin/ownerships/edit.html.haml
- Remove delete button on deleted bikes (because it doesn't do anything)
- Add a way to view the ownership `send_email`
=> Minor admin bike display update

app/controllers/admin/dashboard_controller.rb, app/integrations/file_cache_maintainer.rb, app/integrations/tsv_creator.rb, app/models/export.rb, app/models/organization.rb, app/services/component_creator.rb, app/views/admin/dashboard/tsvs.html.haml, app/views/admin/organizations/_form.html.haml, app/views/admin/organizations/show.html.haml, app/views/organized/users/index.html.haml, app/views/organized/users/new.html.haml, app/views/shared/_content_skeleton.html.haml, app/workers/bike_book_update_worker.rb, config/environments/production.rb, config/locales/.translation_io, config/locales/en.yml, config/locales/translation.nl.yml, config/routes.rb, spec/controllers/admin/dashboard_controller_spec.rb, spec/lib/file_cache_maintainer_spec.rb, spec/models/export_spec.rb, spec/models/organization_spec.rb, spec/requests/api/v2/bikes_request_spec.rb, spec/requests/api/v3/bikes_request_spec.rb
Fix #1644 by removing blacklist and whitelist from code in Bike Index.
There are still some `white_list` methods, because they are calls to [Carrierwave](https://github.com/carrierwaveuploader/carrierwave) and references to master in git paths of other repositories, but at this point, I believe we've taken responsibility for the language we've written.
=> Additional racial language fixes

.circleci/config.yml
Try out returning to parallelism 2
In https://github.com/bikeindex/bike_index/pull/1642 I switched to parallelism 3, because I was worried that jobs were taking too long to process. Unfortunately, this means there is only space for 1 job at a time (with our 4 workers).
So I'm going to benchmark - rerunning this 10 times on CircleCI and posting the results here.
Related: #1648 (parallelism 4)
=> CircleCI 2 parallelism

.standard_todo.yml, Gemfile, app/controllers/bikes_controller.rb, app/controllers/concerns/controller_helpers.rb, app/controllers/oauth/applications_controller.rb, config/initializers/doorkeeper.rb, spec/controllers/locks_controller_spec.rb, spec/requests/authorizations_request_spec.rb, spec/support/controller_spec_helpers.rb
`unauthenticated_redirect=sign_up` redirects to `users/new` rather than `/session/new` - functionality for https://github.com/bikeindex/omniauth-bike-index/pull/5
=> Add unauthenticated redirect

app/assets/javascripts/init.coffee, app/controllers/organized/impound_records_controller.rb, app/controllers/organized/parking_notifications_controller.rb, app/javascript/packs/utils/time_parser.js, app/models/graduated_notification.rb, app/models/parking_notification.rb, app/views/admin/organizations/invoices/edit.html.haml, app/views/bikes/_bike_show_overlays.html.haml, app/views/bikes/show.html.haml, app/views/layouts/application.html.haml, app/views/shared/_modal.html.haml, config/locales/.translation_io, config/locales/en.yml, config/locales/translation.nl.yml, spec/models/graduated_notification_spec.rb, spec/requests/organized/parking_notifications_request_spec.rb
- Fix issue where marking a parking notification resolved would show "unable to mark that parking notification resolved because it's already resolved"
- Require clicking "mark resolved" to mark a bike retrieved for a parking notification
=> Parking notification update fixes

Gemfile, Gemfile.lock, spec/requests/api/v2/swagger_request_spec.rb
Replaces #1716, because additional changes were required.
Also, removing redcarpet, because maybe it isn't required anymore
=> Bump kramdown to 2.3

app/assets/javascripts/revised/pages/bikes/edit_remove.coffee, app/models/user.rb, app/views/bikes/edit_remove.html.haml, app/views/organized/bikes/_list.html.haml, spec/models/user_spec.rb
Also:
- Show actual email for organizations with `claimed_ownerships`
- Fix a bug where `with_locale` broke in sending ownership invitation emails
=> Redirect to user root url after bike delete

app/controllers/organized/dashboard_controller.rb, app/models/organization.rb, app/views/bikes/edit_theft_details.html.haml, app/views/layouts/application.html.haml, spec/requests/organized/dashboard_request_spec.rb
Only for `regional_bike_counts` & `claimmed_ownerships`
Also:
- Don't make bike search active, unless actually viewing bike search
- Don't render the promoted alert modal if they've already bought a promoted alert
=> No regional dashboard for parent organizations

Dockerfile
Per #1844 trying to address the docker build ruby version mismatch and the Gemfile.lock
Is possible this PR is a noop and the solution is the fix the Gemfile.lock to build built with the correct version of ruby. 
I'm assuming the current version of ruby is 2.7 but just was not been updated in the respective docker files.
=> Bump the ruby version in the docker image to match the Gemfile.lock

app/controllers/user_phones_controller.rb, app/integrations/twilio_integration.rb, app/models/manufacturer.rb, app/models/user_phone.rb, app/views/my_accounts/show.html.haml, spec/integrations/twilio_integration_spec.rb, spec/models/user_phone_spec.rb, spec/requests/user_phones_request_spec.rb
We text the code with spaces in it, we should actually accept what we send
=> Match confirmation codes with spaces

app/models/external_registry_client.rb
The request to their API is failing, so pause the searches for now.
=> pause StopHeling searches

.circleci/config.yml, Gemfile, Gemfile.lock, bin/update, db/structure.sql, lib/tasks/rake_tasks.rake
This is a hotfix. The new deployment accesses Redis through TLS, which the hiredis driver doesn't support.
https://github.com/sethherr/soulheart/pull/32
=> Non hiredis soulheart

app/controllers/api/v2/bikes.rb, app/models/b_param.rb, app/models/stolen_record.rb, app/services/stolen_record_updator.rb, app/views/admin/bikes/_bike.html.haml, app/views/bikes/bike_fields/_stolen_location.html.haml, config/locales/.translation_io, config/locales/en.yml, config/locales/translation.nl.yml, db/migrate/20210512162607_remove_show_address_from_stolen_records.rb, db/structure.sql, spec/controllers/bikes_controller_spec.rb, spec/models/stolen_record_spec.rb, spec/requests/api/v3/bikes_request_spec.rb, spec/requests/bikes_request_spec.rb
Ultimately, seems like nobody wants to show their exact address, and this keeps tripping people up
=> Remove Show address attribute from stolen records

spec/integrations/facebook_ads_integration_spec.rb, spec/workers/activate_theft_alert_worker_spec.rb
I found that I had a couple of test failures due to `Facebook::AdsIntegration` being an undefined constant. I think it makes sense to ignore these things when the configuration is not done to allow folks to have a green suite out of the gate. Let me know if you disagree and I'll jump through the hoops to get it set up.
=> Ignore facebook specs when the FB ads integration is not configured

app/models/external_registry_bike.rb, app/models/external_registry_bike/project529_bike.rb, app/models/external_registry_client/project529_client.rb, app/models/external_registry_credential/project529_credential.rb, app/models/stolen_record.rb, app/workers/fetch_project529_bikes_worker.rb, db/migrate/20210921181852_add_external_updated_at_to_external_bikes.rb, db/structure.sql, spec/models/external_registry_bike/project529_bike_spec.rb
```ruby
credential = ExternalRegistryCredential.find(2)
credential.update(access_token_expires_at: Time.current + 20.years)
```
=> Fix 529 integration issues

app/controllers/admin/mail_snippets_controller.rb, app/controllers/admin/twitter_accounts_controller.rb, app/models/tweet.rb, app/models/twitter_account.rb, app/views/admin/mail_snippets/_form.html.haml, app/views/admin/mail_snippets/edit.html.haml, app/views/admin/mail_snippets/index.html.haml, db/migrate/20211215163717_rename_twitter_account_address_attr.rb, db/structure.sql, spec/models/twitter_account_spec.rb, spec/requests/admin/mail_snippets_request_spec.rb
- `TwitterAccount` has an `address` string attribute - it's confusing because of the `address` method in `Geocodeable`. Rename the attribute to `address_string`
- `MailSnippet` has lingering fields for address, even though it doesn't actually include that attribute anymore. Fix that!
=> rename TwitterAccount and MailSnippet address attributes and 

app/workers/migrate_ownership_worker.rb
Follows #2110
There are a number of bikes without ownerships. Because this migration isn't updating the `updated_at` column, they were getting re-enqueued over and over.
I bumped their `updated_at` to post the `END_TIMESTAMP` time:
```ruby
Bike.unscoped.where(soon_current_ownership_id: nil).includes(:ownerships).where(ownerships: {id: nil}).update_all(updated_at: Time.at(1640292127))
```
=> Speed up ownership migration

app/assets/javascripts/revised/pages/bikes/edit_accessories.coffee, app/services/bike_creator.rb, app/views/admin/dashboard/maintenance.html.haml, app/views/bikes_edit/accessories.html.haml, config/locales/.translation_io, config/locales/en.yml, config/locales/translation.nl.yml, db/migrate/20220102153706_remove_handlebar_type_other.rb, db/structure.sql, spec/controllers/bikes_controller_spec.rb
There are currently no `propulsion_type_other` values in the database.
`handlebar_type_other` isn't really adding much.
The values that have been added in the past year
```ruby
Bike.where.not(handlebar_type_other: [nil, ""]).where("updated_at > ?", Time.current - 1.year).pluck(:handlebar_type_other).uniq`)
```
```
["Two side by side joystick style"
"Rack and pinion steering handles"
"Recumbent trike"
"Mounted below the seat"
"Recumbent upright"
"Comfort/Cruiser style"
"Underseat Steering"
"control handles"
"Split cargo bike handle bars"
"Orange Front Rack"
"Butterfly/Trekking handlebars"
"Aluminum handle bar / steering"
"Apehangers"
"Vertical Recumbent Trike "Tank" style steering"
"Bullhorn"
"Underseat Steering"
"Brompton - P-type"
"Brompton - M-type"
"Flat"
"Riser bars"]
```
... which …
=> remove handlebar_type_other and propulsion_type_other

app/controllers/concerns/controller_helpers.rb, app/controllers/sessions_controller.rb, spec/controllers/sessions_controller_spec.rb
By default, redirect back to `bikehub.com` so that folks won't then get immediately redirected back to the Bikehub login page.
=> Fix logout redirect for Bikehub

app/assets/stylesheets/revised/pages/my_accounts/_show.scss, app/helpers/bike_helper.rb, app/helpers/header_tag_helper.rb, app/models/bike.rb, app/models/impound_record.rb, app/models/parking_notification.rb, app/models/stolen_record.rb, app/serializers/bike_v2_serializer.rb, app/serializers/stolen_record_v2_serializer.rb, app/views/bikes/_bike.html.haml, app/views/bikes/_main_show_block.html.haml, app/views/my_accounts/show.html.haml, app/views/shared/_email_bike_box.html.haml, config/locales/.translation_io, config/locales/en.yml, config/locales/translation.nl.yml, spec/helpers/bike_helper_spec.rb, spec/helpers/header_tag_helper_spec.rb, spec/models/bike_spec.rb, spec/models/impound_record_spec.rb, spec/models/stolen_record_spec.rb, spec/serializers/bike_v2_serializer_spec.rb
- Add `current_record` and `current_record_date` to reduce some duplicate code.
- Make the `address` method consistent across stolen records, impound records and parking notifications
- Fix translation issue where #2125 updated some string interpolation and didn't fix the translated files
=> Minor account display improvements

app/controllers/my_accounts_controller.rb, app/helpers/application_helper.rb, app/views/my_accounts/_sharing.html.haml, app/views/users/show.html.haml, config/locales/en.yml, db/migrate/20220201213958_add_instragram_accounts_to_users.rb, db/structure.sql, spec/helpers/application_helper_spec.rb, spec/requests/my_accounts_request_spec.rb
I'll look at this again in the next day or two, but I think we are mostly there.
Let me know if there is anything that is wildly or mildly off.
I did a little bit of simplifying on `#show_twitter_and_website` but it ends up producing the same thing (I think) without having to manually handle the html string. Happy to add a basic `User` test too that checks for the new columns, but didn't see anything equivalent right now so wasn't sure if you generally skip these safety specs, ie `User.new(...); expect(user.instagram).to be_present` etc
This closes #813
=> Add Instagram accounts to user model, user edit/show pages

Gemfile, Guardfile, app/controllers/admin/theft_alerts_controller.rb, app/controllers/bikes/theft_alerts_controller.rb, app/models/theft_alert.rb, app/views/admin/theft_alerts/_table.html.haml, app/views/admin/theft_alerts/edit.html.haml, app/views/admin/theft_alerts/index.html.haml, app/views/admin/theft_alerts/new.html.haml, app/views/bikes/theft_alerts/_table.html.haml, app/views/shared/_pagination.html.haml, app/workers/activate_theft_alert_worker.rb, app/workers/after_user_change_worker.rb, config/locales/.translation_io, config/locales/en.yml, config/locales/translation.nl.yml, config/routes.rb, db/migrate/20220411165641_rename_theft_alerts_begin_at_to_start_at.rb, db/structure.sql, spec/factories/theft_alerts.rb, spec/models/theft_alert_spec.rb, spec/requests/admin/stolen_bikes_request_spec.rb, spec/requests/admin/theft_alerts_request_spec.rb, spec/requests/bikes/theft_alerts_request_spec.rb, spec/workers/activate_theft_alert_worker_spec.rb, spec/workers/deactivate_expired_theft_alert_worker_spec.rb, spec/workers/update_theft_alert_facebook_worker_spec.rb
- Allow admins to see all theft alerts in user bike view
- Rename `begin_at` to `start_at` for consistency with other attributes
- Admins can create new stolen alerts for arbitrary bikes
=> Admin theft alerts

app/workers/migrate_postal_code_worker.rb
Revert #2242 - shipped before the job had finished.
=> put migrate postal code worker back

app/workers/email_donation_worker.rb
```
DEPRECATION WARNING: Using `Range#include?` to check the inclusion of a value in a date time range is deprecated. It is recommended to use `Range#cover?` instead of `Range#include?` to check the inclusion of a value in a date time range. (called from block in matching_stolen_bikes at /home/circleci/bikeindex/bike_index/app/workers/email_donation_worker.rb:70)
```
=> range.include? to range.cover

app/controllers/organized/emails_controller.rb, app/helpers/organized_helper.rb, app/mailers/organized_mailer.rb, app/views/customer_mailer/additional_email_confirmation.html.haml, app/views/customer_mailer/confirmation_email.html.haml, app/views/customer_mailer/magic_login_link_email.html.haml, app/views/customer_mailer/password_reset_email.html.haml, app/views/layouts/application.html.haml, app/views/layouts/email.html.haml, app/views/organized/emails/edit.html.haml, app/views/organized/graduated_notifications/show.html.haml, app/views/organized/parking_notifications/_show_details.html.haml, app/views/organized_mailer/finished_registration.html.haml, app/views/organized_mailer/graduated_notification.html.haml, app/views/organized_mailer/organization_invitation.html.haml, app/views/organized_mailer/parking_notification.html.haml, app/views/organized_mailer/partial_registration.html.haml, app/views/shared/_email_bike_box.html.haml, spec/helpers/organized_helper_spec.rb, spec/requests/organized/emails_request_spec.rb
So organization members don't accidentally do actions that they shouldn't do.
Also adds an alert to the email to make it clear that it's a preview.
=> Prevent email previews from rendering links with tokens

app/controllers/bikes_controller.rb, spec/requests/bikes/create_request_spec.rb
Seems like it's mainly happening from illegitimate registrations, but still should protect
=> Protect from organization nils in embed bike create

app/assets/javascripts/revised/sections/bike_search_bar.coffee, app/assets/stylesheets/revised.scss, app/assets/stylesheets/revised/pages/organized/parking_notifications.scss, app/assets/stylesheets/revised/sections/bike_boxes.scss, app/helpers/bike_helper.rb, app/javascript/scripts/pages/binx_mapping.js, app/javascript/stylesheets/admin/_bikes.scss, app/mailers/customer_mailer.rb, app/mailers/organized_mailer.rb, app/views/admin/bikes/_bike_tabs.html.haml, app/views/bike_versions/index.html.haml, app/views/bikes/_bike.html.haml, app/views/bikes/_main_show_block.html.haml, app/views/bikes/index.html.haml, app/views/my_accounts/show.html.haml, app/views/org_public/impounded_bikes/index.html.haml, app/views/organized/bikes/_search.html.haml, app/views/organized/graduated_notifications/index.html.haml, app/views/organized/hot_sheets/show.html.haml, app/views/organized/impound_records/_table.html.haml, app/views/organized/impound_records/index.html.haml, app/views/organized/parking_notifications/index.html.haml, app/views/shared/_bike_search_form.html.haml, app/views/shared/_email_bike_box.html.haml, app/views/stolen_bike_listings/index.html.haml, config/i18n-tasks.yml, config/locales/.translation_io, config/locales/en.yml, config/locales/translation.nl.yml, spec/helpers/bike_helper_spec.rb
- Add `/shared/_bike_search_form.html.haml` and use it instead of the 7 separate versions of it.
- _Partially motivated by #2324, which added an alert for serial number search queries that are normalized to `unknown` or `made_without_serial` - rather than adding that alert on all 7 pages_
- Turned off `selectOnClose` in `bike_search_bar.coffee` - it prevented selecting nothing (unless you hit escape a lot, or were on a slow connection). Ideally it would be on for custom entries, not sure how to do that though.
- Added a `render_serial_display` to `BikeHelper` to make bike serials render better
=> Switch to a shared bike search form

app/serializers/application_serializer.rb, spec/serializers/bike_serializer_spec.rb
Fix #2326 
Serializers have been using a cache_key that doesn't include the `updated_at` timestamp for objects - [this honeybadger blog post](https://www.honeybadger.io/blog/rails-low-level-caching/) explains the difference between `cache_key` and `cache_key_with_version`.
=> use cache_key_with_version for serializers

app/helpers/organized_helper.rb, app/models/bike.rb, app/models/graduated_notification.rb, app/views/admin/graduated_notifications/index.html.haml, app/views/bikes/_organized_access_panel.html.haml, app/views/organized/graduated_notifications/_table.html.haml, app/views/organized/graduated_notifications/index.html.haml, app/views/organized/graduated_notifications/show.html.haml, spec/factories/graduated_notifications.rb, spec/helpers/organized_helper_spec.rb, spec/models/graduated_notification_spec.rb, spec/requests/bikes/show_request_spec.rb, spec/requests/bikes_request_spec.rb, spec/requests/organized/graduated_notifications_request_spec.rb, spec/workers/after_user_create_worker_spec.rb, spec/workers/create_graduated_notification_worker_spec.rb, spec/workers/process_graduated_notification_worker_spec.rb
"active" was confusing, since it actually meant that the bike was not accessible for the university. Switched to "bike graduated"
=> Graduated notification status improvement

app/helpers/organized_helper.rb, app/models/bike.rb, app/models/graduated_notification.rb, app/models/user_registration_organization.rb, app/views/bikes/_organized_access_panel.html.haml, app/views/organized/graduated_notifications/_table.html.haml, app/views/organized/graduated_notifications/show.html.haml, app/workers/after_bike_save_worker.rb, app/workers/after_user_change_worker.rb, spec/helpers/organized_helper_spec.rb, spec/models/graduated_notification_spec.rb
Follows #2343 - further attempts to clarify what it means when a bike is "graduated" and "marked not graduated"
Now it shows "remains registered" and additional clarification on the `organized_access_panel`.
This also fixes an issue where bikes with multiple graduated notifications weren't correctly disassociating from organizations.
=> Additional update to graduated_notification status

app/assets/javascripts/revised/pages/bikes/show.coffee, app/assets/stylesheets/revised/pages/bikes/show.scss, app/views/bikes/_organized_access_panel.html.haml, config/locales/.translation_io, config/locales/en.yml, config/locales/translation.nl.yml
The unstolen notification button was _very_ prominent, when in reality that shouldn't be something that is used frequently.
=> Improve organization panel unstolen notification button

app/services/bike_geojsoner.rb, spec/services/bike_geojsoner_spec.rb
Previously, GeoJSON had a `color` key to represent when the bike was stolen - which was opaque and not that precise. This switches to including date, because it clears up what is going on.
```ruby
> puts Benchmark.measure { 1000.times { time.to_date.to_s } }
> puts Benchmark.measure { 1000.times { time.strftime("%Y-%m-%d") } }
```
... so sticking with `.to_date.to_s`
=> Improve bike GeoJSON

Gemfile, app/controllers/admin/bulk_imports_controller.rb, app/models/bulk_import.rb, app/uploaders/bulk_import_uploader.rb, app/views/admin/bulk_imports/index.html.haml, spec/requests/organized/bulk_imports_request_spec.rb
Prior to this PR, to see file uploads that failed because of invalid file types required checking the logs.
To make this easier to investigate, create the import with an error (instead of blocking the creation with an error)
=> Create record for invalid file type bulk_imports

Gemfile, Gemfile.lock, app/assets/javascripts/application_revised.js, app/assets/javascripts/external_scripts/time_parser-coffeeimport.js, app/assets/javascripts/init.coffee, app/javascript/scripts/pages/initializer.js
Figured out a good enough solution!
Copy `time_parser.js` into a file in the rails asset pipeline - `time_parser-coffeeimport.js` !
Now rather than having a hacky script to do time localizing (a script which was the inspiration for `time_parser.js` but doesn't take advantage of a bunch of nice additions) we get have the same time localizing everywhere 😄
=> Update to use time_parser.js in coffeescript

config/environments/production.rb
#2370 caused an error on deploy:
```
Uglifier::Error: Unexpected token: name (TimeParser). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
```
=> Fix asset compilation error

app/assets/stylesheets/registrations.scss, app/assets/stylesheets/revised/pages/landing/_organizations.scss
- Scope `.org-landing-icon-list` styles, so that a sublist isn't styled by them
- Add princeton registration button color.
=> Updates for Princeton landing page

app/views/registrations/embed.html.haml, spec/requests/api/v2/bikes_search_request_spec.rb, spec/workers/organization_export_worker_spec.rb
Use `short_name` rather than `slug`
I have no idea why it was slug before, so I wanted to comment about it
(also, remove some unnecessary spec `pp`s)
=> Update partial registration email placeholder

app/views/doorkeeper/applications/show.html.haml
Per [comment on forum](https://discuss.bikeindex.org/t/dev-cannot-authorize-oauth-endpoint/4476) - missing the scope param causes this link to fail.
=> Include scope in authorize button from oauth applications page

app/services/autocomplete.rb, spec/services/autocomplete/matcher_spec.rb
There is a Redis key change in #2430
Before removing soulheart, we need to get all the correct data into Redis - so this needs to be merged and shipped first.
=> Update autocomplete keys

app/javascript/scripts/api.js, app/javascript/scripts/bikes_search/BikeSearch.jsx, app/javascript/scripts/bikes_search/SecondarySearches.jsx, app/models/concerns/bike_searchable.rb, spec/support/shared_examples/bike_searchable.rb
Given a bike with serial `"XXX XXX"`, searches for `"XXXXXX"` and `"XX XX XX"` should both match the bike.
=> Serial search matches with whitespace removed

app/models/bike.rb, app/models/concerns/bike_searchable.rb, app/services/owner_duplicate_bike_finder.rb, app/services/serial_normalizer.rb, app/workers/duplicate_bike_finder_worker.rb, app/workers/migrate_normalized_serial_segments_worker.rb, db/migrate/20231012212343_add_serial_segments_migrated_to_bikes.rb, db/primary_replica_structure.sql, db/structure.sql, spec/services/serial_normalizer_spec.rb, spec/workers/duplicate_bike_finder_worker_spec.rb, spec/workers/migrate_normalized_serial_segments_worker_spec.rb
- Remove orphaned Duplicate Bike Groups and Normalized Serial Segments
- Create normalized serial segments for `serial_normalized_no_space`
- Add Migration to create `serial_normalized_no_space` serial segments and remove orphaned duplicate bike groups
=> Update duplicate bike functionality

.circleci/config.yml, Gemfile.lock
- Update OJ gem to 3.16 (https://rubygems.org/gems/oj) to prepare for Ruby 3. 
- Update Bundler version for CircleCI.
The [`ruby3` branch](https://github.com/bikeindex/bike_index/tree/ruby3) on PR https://github.com/bikeindex/bike_index/pull/2374 prints a compatibility warning with the existing version of oj 3.13.
=> Update OJ gem to 3.16 to prepare for Ruby 3

app/workers/organization_export_worker.rb, app/workers/scheduled_worker_runner.rb, spec/workers/unused_ownership_removal_worker_spec.rb
Also, comment out `UnusedOwnershipRemovalWorker` scheduling, I think it's blocking up the queues
=> Move OrganizationExportWorker to med_priority queue

app/workers/scheduled_email_survey_worker.rb, spec/workers/scheduled_email_survey_worker_spec.rb
Send to stolen recipients.
Uses some of the functionality from `theft_survey_4_2022` (see [the worker](https://github.com/bikeindex/bike_index/blob/e5fde657080dc4e53c682fbae6ff1a154e0b9d88/app/workers/scheduled_email_survey_worker.rb) and [spec](https://github.com/bikeindex/bike_index/blob/e5fde657080dc4e53c682fbae6ff1a154e0b9d88/spec/workers/scheduled_email_survey_worker_spec.rb) from then)
=> Email survey update

app/views/shared/_footer_revised.html.haml
Add a Mastodon icon with the `rel=me` attribute set. This is what Mastodon will look for to show the green verification box, per our discussion on fedi.
I have not tested this as I don't know anything about Ruby or HAML, not having worked with them in years. I'm also not sure if the FontAwesome version is high enough for this icon to exist, so apologies for not finishing the job; if anyone who knows what they're doing wants to take a quick look to make sure this works before deploying, that would be great!
=> Add Mastodon/Fediverse to site footer icons

.circleci/config.yml, Gemfile, Gemfile.lock, spec/noenv_helper.rb, spec/rails_helper.rb
=> Re-Add Code Climate

Gemfile, Gemfile.lock
This PR fixes the following 'High' and 'Critical' security vulnerabilities found in the current version of `rack` (2.2.3):
```
Name: rack
Version: 2.2.3
CVE: CVE-2022-30123
GHSA: GHSA-wq4h-7r42-5hrr
Criticality: Critical
URL: https://groups.google.com/g/ruby-security-ann/c/LWB10kWzag8
Title: Possible shell escape sequence injection vulnerability in Rack
Solution: upgrade to '~> 2.0.9, >= 2.0.9.1', '~> 2.1.4, >= 2.1.4.1', '>= 2.2.3.1'
Name: rack
Version: 2.2.3
CVE: CVE-2022-30122
GHSA: GHSA-hxqx-xwvh-44m2
Criticality: High
URL: https://groups.google.com/g/ruby-security-ann/c/L2Axto442qk
Title: Denial of Service Vulnerability in Rack Multipart Parsing
Solution: upgrade to '~> 2.0.9, >= 2.0.9.1', '~> 2.1.4, >= 2.1.4.1', '>= 2.2.3.1'
Name: rack
Version: 2.2.3
CVE: CVE-2022-44570
GHSA: …
```
=> BIB-32: Upgrade rack to fix security vulnerabilities

app/controllers/organized/model_audits_controller.rb, app/models/cycle_type.rb, app/models/model_audit.rb, app/views/organized/model_audits/show.html.haml, app/workers/find_or_create_model_audit_worker.rb, app/workers/update_model_audit_worker.rb, config/locales/.translation_io, config/locales/en.yml, config/locales/translation.es.yml, config/locales/translation.nb.yml, config/locales/translation.nl.yml, spec/models/model_audit_spec.rb, spec/models/propulsion_type_spec.rb, spec/services/autocomplete/loader_spec.rb, spec/workers/find_or_create_model_audit_worker_spec.rb, spec/workers/update_model_audit_worker_spec.rb
- Verify that if there are no longer any matching models, the model audit is deleted
Also - reseed autocomplete hash after shipping
=> Improve unknown model matcher

app/controllers/admin/feedbacks_controller.rb, app/controllers/admin/impound_claims_controller.rb, app/controllers/admin/impound_records_controller.rb, app/controllers/admin/notifications_controller.rb, app/controllers/admin/organization_statuses_controller.rb, app/controllers/admin/superuser_abilities_controller.rb, app/controllers/admin/theft_alerts_controller.rb, app/controllers/admin/tweets_controller.rb, app/controllers/organized/graduated_notifications_controller.rb, app/controllers/organized/impound_claims_controller.rb, app/controllers/organized/impound_records_controller.rb
Brakeman was reporting 12 dangerous send vulnerabilities. The process here was to correct them using these practical strategies: https://brakemanscanner.org/docs/warning_types/dangerous_send/
After these changes, no more warnings were reported.
=> [Bib-40] Addressing send vulnerabilities

.config/brakeman.ignore
Brakeman is currently reporting 4 command injection vulnerabilities which we know are false positives. This PR merely adds a `.config/brakeman.ignore` ignoring these 4 warnings
=> Ignore false positives in brakeman security warnings

public/.well-known/apple-app-site-association, public/apple-app-site-association
- AASA = apple-app-site-association file, without extension, of type JSON
- Stored in `public/.well-known` for access in bikeindex.org/.well-known/apple-app-site-association URL
- Documentation for webcredentials: https://developer.apple.com/documentation/xcode/supporting-associated-domains
- Requires iOS app to acknowledge associated domains entitlement in PR https://github.com/bikeindex/bike_index_ios/pull/1
=> Add AASA file for web credential sharing with iOS app for easier auth

config/initializers/kramdown.rb
This PR fixes the following error:
```
Failure/Error: The Bike Index is open source. You can [view the source code on GitHub](https://github.com/bikeindex/bike_index)&mdash;the API is in [app/controllers/api/v2](https://github.com/bikeindex/bike_index/tree/main/app/controllers/api/v2) and the tests for it are in [spec/api/v2](https://github.com/bikeindex/bike_index/tree/main/spec/api/v2).
ActionView::Template::Error:
undefined method `valid_encoding?' for #<ActionView::OutputBuffer:0x000055c40084d950>
```
We were getting similar errors in `spec/requests/documentation_request_spec.rb`. 
We investigated this error and it's due to a [change in Rails 7.1 that allows ActionView to render non-strings](https://github.com/rails/rails/pull/51023). We tried to update `grape-swagger` and `grape` for …
=> BIB-67: ActionView::Template::Error:   undefined method `valid_encoding?'

config/environments/development.rb
Sorry for the random drive-by PR. I was searching for examples of FileUpdateChecker usage and saw yours and went "hmmmm".
I believe this code to be probably non-functional and definitely slowing down your development experience.
For the code being removed, every time a file in `app/controllers/api/*` is modified, it will:
- Do some logic on `app/api` which is a directory that doesn't exist
- Eager-load the entire application (which likely pauses everything for several seconds)
I say "probably non-functional" because I could imagine the situation where files in `app/controllers/api/*` need to be eager-loaded specifically (rather than lazy/auto loaded)... but I didn't see other logic in your application that would do that _at development boot_. 
So if your application currently has a weird …
=> Remove dev's nonfunctional file update checker for api

.circleci/config.yml, app/helpers/application_helper.rb, app/helpers/localization_helper.rb, app/mailers/customer_mailer.rb, app/mailers/donation_mailer.rb, app/mailers/organized_mailer.rb, config/initializers/translation.rb, spec/helpers/application_helper_spec.rb, spec/helpers/localization_helper_spec.rb, spec/i18n_spec.rb
Fixes changes from #2609
These are the updates that will need to be reverted after shipping Ruby 3.1 in #2605
=> Translation methods backward compatibility, part 2

.circleci/config.yml
Only required by the _Sync translations (only on main by default)_, `bin/check_translations` command
Which is commented out. It will be added back in with #2623
=> Circleci - comment out git install

app/controllers/admin/payments_controller.rb, app/controllers/bikes/theft_alerts_controller.rb, app/controllers/payments_controller.rb, app/models/payment.rb, app/models/theft_alert.rb, app/models/user.rb, app/views/admin/payments/_display.html.haml, app/views/admin/payments/_display_table.html.haml, app/views/admin/payments/_table.html.haml, app/views/customer_mailer/invoice_email.html.haml, config/locales/.translation_io, config/locales/en.yml, config/locales/translation.es.yml, config/locales/translation.it.yml, config/locales/translation.nb.yml, config/locales/translation.nl.yml, db/migrate/20250203011709_drop_deprecated_payment_columns.rb, db/primary_replica_structure.sql, db/structure.sql, spec/factories/payments.rb, spec/models/user_spec.rb, spec/rails_helper.rb, spec/requests/admin/payments_request_spec.rb, spec/requests/bikes/theft_alerts_request_spec.rb, spec/requests/payments_request_spec.rb
NOTE: the final Stripe charge was created on 2021-08-04 - after which only stripe sessions were created.
There were briefly both Sessions and Charges being created.
I don't know this actually could matter in the future, but this is removing the column that tracks that, so I figure it should be noted.
=> Remove and rename columns in payment model

app/controllers/admin/stolen_bikes_controller.rb, app/controllers/admin/theft_alerts_controller.rb, app/jobs/activate_theft_alert_job.rb, app/jobs/after_user_change_job.rb, app/jobs/scheduled_job_runner.rb, app/jobs/stolen_bike/activate_theft_alert_job.rb, app/jobs/stolen_bike/after_stolen_record_save_job.rb, app/jobs/stolen_bike/approve_stolen_listing_job.rb, app/jobs/stolen_bike/deactivate_expired_theft_alert_job.rb, app/jobs/stolen_bike/update_theft_alert_facebook_job.rb, app/models/stolen_record.rb, app/models/theft_alert.rb, app/views/admin/theft_alerts/edit.html.haml, app/views/admin/theft_alerts/index.html.haml, config/brakeman.ignore, spec/jobs/stolen_bike/activate_theft_alert_job_spec.rb, spec/jobs/stolen_bike/after_stolen_record_save_job_spec.rb, spec/jobs/stolen_bike/approve_stolen_listing_job_spec.rb, spec/jobs/stolen_bike/deactivate_expired_theft_alert_job_spec.rb, spec/jobs/stolen_bike/update_theft_alert_facebook_job_spec.rb, spec/models/bike_spec.rb, spec/models/theft_alert_spec.rb, spec/requests/admin/stolen_bikes_request_spec.rb, spec/requests/admin/theft_alerts_request_spec.rb, spec/requests/bikes/show_request_spec.rb, spec/requests/organized/bulk_imports_request_spec.rb
- Default view shows only paid (and admin activated)
- Create a `jobs/stolen_bike` subfolder and put jobs for stolen bikes in there
- Enable sorting by _failed to activate_
- Automatically retry activating _failed to activate_ alerts
=> Admin theft alert fixes

app/jobs/stolen_bike/update_theft_alert_facebook_job.rb, app/views/admin/theft_alerts/edit.html.haml
- Ensure failed to activate alerts actually get re-activated
- Fix a nil bug in admin theft alerts
=> Theft alert fixes

Gemfile, Gemfile.lock, app/views/layouts/application.html.haml, config/cable.yml
[hotwire-livereload](https://github.com/kirillplatonov/hotwire-livereload/) locked to version 1.4.1 - the last version prior to it auto injecting the code.
Specifically this is because it double renders lookbook and throws an error, but also other places in the app where Turbo isn't enabled.
See https://github.com/kirillplatonov/hotwire-livereload/issues/73 - hoping to figure out a way to disable for just some layouts.
=> Add hotwire-livereload

app/assets/javascripts/revised/components/optional_form_update.coffee, app/assets/javascripts/revised/embed_script.coffee, app/assets/stylesheets/revised.scss, app/components/pagination/component.rb
Something in tailwind or JS vendoring overrode hiding fields, and they stopped working.
This fixes it. In a terrible gross hacky way for `BikeIndex.OptionalFormUpdate`, but it works better than it not working.
=> Fix issues with hidden fields

app/models/concerns/friendly_slug_findable.rb, app/services/slugifyer.rb, spec/models/organization_spec.rb, spec/services/slugifyer_spec.rb, spec/support/shared_examples/friendly_slug_findable.rb
Strip parentheses from slugs by default (for consistency between different slugifyer formats)
=> slugifyer update

app/controllers/admin/dashboard_controller.rb, app/controllers/api/base.rb, app/controllers/concerns/controller_helpers.rb, app/helpers/admin_helper.rb, app/models/concerns/bike_searchable.rb, app/models/country.rb, app/views/admin/dashboard/ip_location.html.haml, config/initializers/ip_address_parser.rb, config/routes.rb, spec/requests/admin/dashboard_request_spec.rb
This will enable passing country id to address record building (to initialize with the correct country) and membership (for currency)
Also added `/admin/ip_location` to compare the results from Cloudflare against the results from Geocoder
=> Add location parsing from Cloudflare headers

public/.well-known/apple-app-site-association
Update app site association to add:
1. Defer to bikeindex.org for all URLs
2. **Except** `/bikes/scanned/:id` URLs _should_ open the app for the app to display.
- Guests (aka unauthenticated / new users) who have the app should be able to view the bike
- Guests who don't have the app yet _should_ be directed to the App Store to download it and then open the app to the bikes/scanned/:id deeplink automatically.
- QR code handling is not built in the app yet and will need to handle:
- Displaying a scanned bike for authenticated users
- Displaying a scanned bike for guest users and allow them to 
- View a bike
- Create an account and then continue to interact with that bike
- Public AASA file: https://bikeindex.org/.well-known/apple-app-site-association
- …
=> Feat: Add applinks for bikes/scanned/:id to support QR code scans

public/.well-known/apple-app-site-association
1. AASA file from PR https://github.com/bikeindex/bike_index/pull/2756 is propagated 
- See: https://app-site-association.cdn-apple.com/a/v1/bikeindex.org
2. Settings > Developer > Universal Links section > Associated Domains Development → ON
3. Settings > Developer > Universal Links section > Diagnostics > paste `https://bikeindex.org/bikes/scanned/A40340` URL for validation ✅ 
4. Branch.io's validator reports a misconfiguration https://branch.io/resources/aasa-validator/
- components declaring `bikes/scanned/*` should be sufficient alone
=> Fix: Remove overly-broad Universal Links exclusion

public/.well-known/apple-app-site-association
- Change `applinks > details > { appIDs, components }` to `[{ appIDs, components }]`
- Follow format at https://developer.apple.com/documentation/xcode/supporting-associated-domains
- https://github.com/bikeindex/bike_index/pull/2806
- https://github.com/bikeindex/bike_index/pull/2756
=> Fix: Universal Links > AASA > Details needs to be an array of objects

app/components/search/registration_fields/component.html.erb, app/components/search/registration_fields/component.rb, app/components/search/registration_fields/component_controller.js, app/javascript/utils/collapse_utils.js
Based on feedback, revert #2773. Once again, only show location fields when "stolen in search area" is selected
=> Show location only on search proximity

app/helpers/admin_helper.rb, app/jobs/merge_additional_email_job.rb, app/models/email_ban.rb, app/models/email_domain.rb, app/views/admin/email_domains/_data_details.html.haml, app/views/admin/email_domains/_table.html.haml, app/views/admin/email_domains/show.html.haml, app/views/admin/marketplace_listings/_table.html.haml, app/views/admin/marketplace_messages/show.html.haml, app/views/admin/users/edit.html.haml, db/migrate/20250519154506_remove_user_email_id_from_email_bans.rb, db/primary_replica_structure.sql, db/structure.sql, spec/jobs/merge_additional_email_job_spec.rb, spec/jobs/update_email_domain_job_spec.rb, spec/models/email_ban_spec.rb, spec/requests/api/v3/bikes_request_spec.rb
Follow up to #2751
users and multiple non-spammy bikes
In separate PR:
=> Update email domain spam score

Gemfile, Gemfile.lock, app/components/pagination/component.rb, app/jobs/bulk_import_job.rb, app/models/bulk_import.rb, app/models/user_registration_organization.rb, app/views/admin/bulk_imports/index.html.haml, app/views/organized/bulk_imports/_progress_display.html.haml, app/views/organized/bulk_imports/index.html.haml, app/views/organized/bulk_imports/show.html.haml, config/locales/.translation_io, config/locales/en.yml, config/locales/translation.es.yml, config/locales/translation.it.yml, config/locales/translation.nb.yml, config/locales/translation.nl.yml, spec/models/bulk_import_spec.rb, spec/vcr_cassettes/bulk_import-open_file.yml
For remote bulk import files, download and make a tempfile, instead of streaming the URL.
CSU imported a lot of bikes to their organization account. Because of a dumb thing in `UserRegistrationOrganization`, the import caused our job queues to backup. 
This update fixes it so that `Callbacks::AfterBikeSaveJob` doesn't halt and catch fire when a user has > 10k bikes.
Also makes some bulk import display improvements (following #2880)
=> Download tempfile when processing remote bulk import, fix a bug causing AfterBikeSaveJob to hang

.gitignore, Gemfile, Gemfile.lock, config/locales/.translation_io
`check_translations` [failed on main](https://github.com/bikeindex/bike_index/actions/runs/17139316413/job/48623017937)
The failure was that vendored gems made the git tree dirty.
So update to ignore vendored gems.
=> Fix check_translations failure
