bikeindex/bike_index

app/assets/stylesheets/application_styles/_vars.scss
app/controllers/bikes_controller.rb

Nothing special just thought I'd clean up a little. This will close out #71 and #72.
Also drop trailing white space for files touched.

Cleanup deprecations

---

app/models/ad.rb
app/models/bike.rb
app/models/bike_token.rb
app/models/blog.rb
app/models/color.rb
app/models/duplicate_bike_group.rb
app/models/frame_material.rb
app/models/front_gear_type.rb
app/models/location.rb
app/models/mail_snippet.rb
app/models/manufacturer.rb
app/models/organization.rb
app/models/organization_invitation.rb
app/models/ownership.rb
app/models/paint.rb
app/models/payment.rb
app/models/public_image.rb
app/models/rear_gear_type.rb
app/models/recovery_display.rb
app/models/state.rb
app/models/stolen_record.rb
app/models/wheel_size.rb

update scopes to have callable object for upgrading to rails4

---

app/models/bike.rb
app/services/bike_creator.rb
app/services/bike_creator_builder.rb
app/services/bike_creator_organizer.rb
app/services/bike_creator_tokenizer.rb
app/services/bike_creator_verifier.rb
app/services/bike_updator.rb
app/views/admin/bikes/_admin_bikes_table.html.haml
app/views/admin/bikes/_admin_bikes_table_multidelete.html.haml
app/views/admin/bikes/missing_manufacturer.html.haml
db/migrate/20160314144745_remove_verified_attribute_from_bikes.rb
db/structure.sql
spec/services/bike_creator_organizer_spec.rb
spec/services/bike_creator_spec.rb
spec/services/bike_creator_tokenizer_spec.rb
spec/services/bike_creator_verifier_spec.rb
spec/services/bike_updator_spec.rb

Remove `paid_for` and `payment_required` attrs from bike because we don't and haven't ever used them

Remove "verified" bike attribute

---

.env.development
.env.test
app/controllers/application_controller.rb
app/controllers/discourse_authentication_controller.rb
app/controllers/users_controller.rb
config/routes.rb
lib/single_sign_on.rb
spec/controllers/discourse_authentication_controller_spec.rb
spec/controllers/sessions_controller_spec.rb
spec/controllers/users_controller_spec.rb

Add SSO route for Discourse

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/models/user.rb
config/initializers/rack_profiler.rb
db/migrate/20160317183354_add_developer_to_users.rb
db/structure.sql

Because we need to improve performance

Add mini-profiler

---

app/assets/javascripts/bike_index.js.coffee
app/assets/javascripts/views/bikes/bikes_search.js.coffee
app/assets/javascripts/views/global.js.coffee
app/controllers/api/v2/bikes_search.rb
app/views/layouts/application_updated.html.haml
app/views/shared/_footer.html.haml
app/views/shared/_footer_updated.html.haml
spec/api/v2/bikes_search_spec.rb

- Ensure we're actually setting proximity
- Ensure we don't override proximity in API calls if proximity_radius is present
- Call views better in bike_index main backbone file. 
This brings up the fact that maybe it's time to make improvements to the way backbone is "implemented" in Bike Index.

Update proximity search

---

app/assets/javascripts/revised/components/form_well.coffee
app/assets/javascripts/revised/components/optional_form_update.coffee
app/assets/javascripts/revised/pages/bikes/new.coffee
app/assets/stylesheets/revised.scss
app/assets/stylesheets/revised/fonts.scss
app/assets/stylesheets/revised/mixins/_buttons.scss
app/assets/stylesheets/revised/mixins/_colors.scss
app/assets/stylesheets/revised/pages/bikes_new.scss
app/assets/stylesheets/revised/sections/form_well.scss
app/assets/stylesheets/revised/sections/horizontal_lines.scss
app/assets/stylesheets/revised/sections/modals.scss
app/assets/stylesheets/revised/sections/primary_header_nav.scss
app/controllers/bikes_controller.rb
app/helpers/application_helper.rb
app/models/b_param.rb
app/views/bikes/new_revised.html.haml
app/views/layouts/application_revised.html.haml
spec/controllers/bikes_controller_spec.rb
spec/helpers/application_helper_spec.rb
spec/models/b_param_spec.rb

Minor logic updates, finishing touches on styling

New bike revised update

---

Gemfile.lock
app/assets/stylesheets/revised/pages/support/faq.scss
app/controllers/feedbacks_controller.rb
app/helpers/application_helper.rb
lib/tasks/seed_tasks.rake
spec/controllers/feedbacks_controller_spec.rb
spec/helpers/application_helper_spec.rb

Feedback page revision

---

app/assets/javascripts/revised/pages/bikes/edit.coffee
app/assets/javascripts/revised/pages/bikes/edit_accessories.coffee
app/assets/javascripts/revised/pages/bikes/edit_drivetrain.coffee
app/assets/javascripts/revised/pages/bikes/edit_ownership.coffee
app/assets/javascripts/revised/pages/bikes/edit_photos.coffee
app/assets/javascripts/revised/pages/bikes/edit_root.coffee
app/assets/javascripts/revised/pages/bikes/edit_stolen.coffee
app/assets/javascripts/revised/pages/bikes/new.coffee
app/assets/javascripts/revised/pages/bikes/show.coffee
app/assets/javascripts/revised/pages/info/support_the_index.coffee
app/assets/javascripts/revised/pages/info/where.coffee
app/assets/javascripts/revised/pages/welcome/index.coffee
app/assets/javascripts/revised/sections/bike_search_bar.coffee.erb
app/controllers/admin/organizations_controller.rb
app/views/admin/organizations/show.html.haml
app/views/shared/_shops_map.html.erb

Use coffeescript's fat arrow, durp

Stop binding to pagespace in revised coffeescript

---

app/services/bike_searcher.rb
app/views/bikes/_revised_bike.html.haml
app/views/bikes/index_revised.html.haml
spec/controllers/bikes_controller_spec.rb
spec/services/bike_searcher_spec.rb

Minor fixes for bike search

---

app/assets/javascripts/revised/pages/bikes/show.coffee
app/assets/stylesheets/revised/fonts.scss
app/assets/stylesheets/revised/pages/bikes/show.scss
app/assets/stylesheets/revised/pages/bikes/show_photo.scss
app/assets/stylesheets/revised/sections/bike_boxes.scss
app/assets/stylesheets/revised/sections/bike_search_form.scss
app/assets/stylesheets/updated_styles/components/zoom.scss
app/decorators/bike_decorator.rb
app/models/concerns/phonifyerable.rb
app/models/stolen_record.rb
app/views/bikes/_revised_bike.html.haml
app/views/bikes/index_revised.html.haml
app/views/bikes/show_revised.html.haml
config/initializers/phonifyer.rb
spec/decorators/bike_decorator_spec.rb
spec/initializers/phonifyer_spec.rb
spec/models/stolen_record_spec.rb

Revisions to bike search and show

---

app/controllers/organizations_controller.rb
app/helpers/application_helper.rb
spec/controllers/organizations_controller_spec.rb
spec/helpers/application_helper_spec.rb

cherry-pick relevant commits from #201

Revised Lightspeed page

---

.env
app/assets/javascripts/revised/components/toggle_hidden_other.coffee
app/assets/javascripts/revised/pages/bikes/edit_stolen.coffee
app/assets/javascripts/revised/pages/bikes/new.coffee
app/assets/stylesheets/revised/fonts.scss
app/controllers/bikes_controller.rb
app/models/b_param.rb
app/views/bikes/bike_fields/_stolen_location.html.haml
app/views/bikes/edit_stolen.html.haml
app/views/bikes/new_revised.html.haml
db/structure.sql
spec/controllers/bikes_controller_spec.rb

Previously, revised new didn't like stolen bikes. Now it does!

Revised new stolen bikes!

---

Gemfile
Gemfile.lock
app/assets/javascripts/init.coffee
app/assets/javascripts/revised/pages/bikes/edit_accessories.coffee
app/assets/javascripts/revised/pages/legacy_stolen_index.coffee
app/assets/javascripts/revised/sections/nav_header.coffee
app/assets/stylesheets/revised.scss
app/assets/stylesheets/revised/pages/legacy_stolen.scss
app/assets/stylesheets/revised/sections/primary_header_nav.scss
app/views/stolen/index.html.haml

- reduce duplication and extension in BikeIndex coffeescript
- Fix issue with header_nav display on mobile phones
- Fix stolen index display and functionality
- Stop extending everything in Bike Index.
- remove even more things from extension
- turns out that one thing does needs to be on the window though

Frontend fixes

---

app/controllers/errors_controller.rb
app/controllers/feedbacks_controller.rb
app/views/errors/bad_request.xml
app/views/errors/not_found.xml
app/views/errors/server_error.xml
app/views/errors/unauthorized.xml
app/views/errors/unprocessable_entity.xml
config/routes.rb
spec/controllers/errors_controller_spec.rb

When someone/something requests help.txt, don't shit the bed. It's embarrassing.

Catch all errors and render

---

app/assets/stylesheets/legacy_includes/_dropdowns.scss
app/assets/stylesheets/revised/sections/legal.scss
app/controllers/bikes_controller.rb
app/controllers/concerns/authentication_helper.rb
app/controllers/welcome_controller.rb
app/views/users/accept_terms.html.haml
app/views/welcome/user_home.html.haml

Improve accept terms of service

---

app/assets/javascripts/revised/pages/locks/form.coffee

Reverts bikeindex/bike_index#248

Revert "remove stray console.log in the lock form coffeescript"

---

app/controllers/admin/customer_contacts_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/bikes_controller.rb
app/controllers/user_emails_controller.rb
app/models/customer_contact.rb
app/models/user.rb
app/views/admin/users/_form.html.haml
app/views/admin/users/index.html.haml
app/workers/merge_additional_email_worker.rb
db/migrate/20160901175004_change_user_confirmed_to_be_default_false.rb
db/structure.sql
spec/controllers/bikes_controller_spec.rb
spec/controllers/user_emails_controller_spec.rb
spec/models/user_email_spec.rb
spec/models/user_spec.rb

Fix a few issues with user emails

User emails improvements

---

app/controllers/api/v2/bikes.rb
app/models/b_param.rb
app/models/bike.rb
app/services/bike_creator.rb
db/migrate/20160913155615_add_pos_and_new_to_creation_state.rb
db/structure.sql
spec/api/v2/bikes_spec.rb
spec/controllers/api/v1/bikes_controller_spec.rb
spec/models/b_param_spec.rb

Added creation information booleans

---

app/assets/javascripts/revised/pages/bikes/show.coffee
app/assets/javascripts/views/locks/locks_form.js.coffee
app/controllers/bikes_controller.rb
app/views/bikes/show.html.haml
app/views/feedbacks/index.html.haml
app/views/organizations/_new_form.html.haml
spec/controllers/sessions_controller_spec.rb

Redirect instead of showing stolen message form for unsigned in users

---

app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/views/bikes/_revised_bike.html.haml
app/views/users/create.html.haml
spec/controllers/users_controller_spec.rb
spec/helpers/application_helper_spec.rb

Also add basic bike list caching

Fix Signup issue

---

app/mailers/organized_mailer.rb
app/views/admin/memberships/index.html.haml
app/workers/get_manufacturer_logo_worker.rb
config/locales/organized_mailer.en.yml
spec/mailers/organized_mailer_spec.rb
spec/workers/get_manufacturer_logo_worker_spec.rb

Fix mail title for self made bikes

---

app/assets/javascripts/revised/pages/info/payments.coffee
app/controllers/payments_controller.rb
app/models/payment.rb
app/views/customer_mailer/invoice_email.html.haml
app/views/customer_mailer/invoice_email.text.haml
app/views/layouts/admin.html.haml
app/views/layouts/payments_layout.html.haml
app/views/payments/_form.html.haml
app/views/payments/create.html.haml
db/migrate/20161222154603_add_is_payment_to_payments.rb
db/structure.sql
spec/controllers/payments_controller_spec.rb
spec/mailers/customer_mailer_spec.rb
spec/models/bike_spec.rb

We were only superficially doing it previously, now we can do it it a little bit better (and display things a little more accurately).

Differentiate between payments and donations

---

app/models/bike.rb
app/models/creation_state.rb
app/views/admin/bikes/_admin_bikes_table.html.haml
app/views/organized/bikes/index.html.haml
app/views/organized/bikes/search.html.haml
spec/models/bike_spec.rb
spec/models/creation_state_spec.rb

Make creation location more readable (and dry it out)

Add creation description

---

Rakefile

Found the fix in http://stackoverflow.com/a/35893941/3471954

fixes #312

---

app/assets/stylesheets/revised/fonts.scss
app/assets/stylesheets/revised/mixins/_colors.scss
app/assets/stylesheets/revised/pages/info/about.scss
app/assets/stylesheets/revised/pages/payments/payments.scss
app/views/info/about.html.haml
app/views/payments/_form.html.haml

We're a nonprofit, we should talk about it

Bike Index nonprofit

---

app/views/landing_pages/for_schools.haml

updated copy for_schools.haml

---

app/views/landing_pages/for_law_enforcement.haml

added tweet to law enforcement page

---

app/controllers/organizations_controller.rb
app/models/bike.rb
app/models/blog.rb
app/models/recovery_display.rb
app/models/stolen_record.rb
app/services/stolen_record_updator.rb
app/views/bikes/_bike.html.haml
app/views/bikes/_bike_u.html.haml
app/views/bikes/pdf.html.haml
app/views/organizations/embed.html.haml

fresh attempt to implement ISO8601 dates in Bike Index. This will need additional testing to make sure date sorting isn't negatively impacted along with updates for relevant spec tests. Resolves #326

ISO date standards are cool

---

app/views/admin/bikes/edit.html.haml
spec/api/v3/search_spec.rb
spec/controllers/api/v1/bikes_controller_spec.rb
spec/vcr_cassettes/v1_bikes_create-stolen.yml
spec/vcr_cassettes/v3_bike_search-count.yml

Unfortunately, this doesn't reproduce locally so it's difficult to solve, particularly with travis taking forever now that we've upgraded postgres.

Fix flaky test on travis

---

app/assets/javascripts/external_scripts/embed_script.js.coffee

I'm not familiar with Coffeescript, so please improve as needed. I'm uncertain about how to implement the `function` callable.

Prevent double submission of registrations

---

app/assets/stylesheets/revised/sections/partner_sign_in_up.scss
app/assets/stylesheets/revised/sections/sign_in_up.scss
app/controllers/concerns/authentication_helper.rb
app/helpers/application_helper.rb
app/views/layouts/application_revised_bikehub.html.haml
app/views/sessions/new.html.haml
app/views/users/new.html.haml
config/locales/doorkeeper.en.yml

Pulling styling changes from #479

Partner login improvements

---

app/controllers/admin/organizations/invoices_controller.rb
app/views/admin/organizations/invoices/_form.html.haml
db/migrate/20190201193608_add_notes_to_invoices_and_kind_to_organizations.rb
db/structure.sql
spec/controllers/admin/organizations/invoices_controller_spec.rb

Also, add the `kind` attribute for organizations so that we can switch to using an enum there.

Add notes to invoices

---

db/migrate/20190201214042_remove_org_type_from_organizations.rb
db/structure.sql

`org_type` is now the enum `kind`

follow up #526 - remove org_type from organizations

---

Gemfile
Gemfile.lock
app/models/bike.rb
app/models/user.rb
config/environments/development.rb
db/migrate/20190206044915_add_listing_order_index_to_bikes.rb
db/structure.sql

See: https://github.com/gadogado/bike_index/pull/1

Fixes n+1's and adds listing_order sort idx

---

app/controllers/api/v1/bikes_controller.rb
app/models/b_param.rb
app/models/bike.rb
app/models/frame_material.rb
spec/controllers/api/v1/bikes_controller_spec.rb
spec/models/frame_material_spec.rb

We stopped accepting the `frame_material_slug` parameter in api v1 in #552). This resolves that issue

Fix frame material slug

---

app/controllers/api/v2/selections.rb
app/models/bike.rb
app/models/deprecated/propulsion_type.rb
app/models/propulsion_type.rb
app/services/bike_creator_builder.rb
db/migrate/20190314182139_add_propulsion_type_to_bikes.rb
db/seeds/seed_bike_associations.rb
db/structure.sql
lib/tasks/seed_tasks.rake
spec/controllers/organizations_controller_spec.rb
spec/factories.rb
spec/factories/bikes.rb
spec/models/bike_spec.rb
spec/models/color_spec.rb
spec/models/propulsion_type_spec.rb
spec/requests/api/v2/bikes_request_spec.rb
spec/requests/api/v2/selections_request_spec.rb
spec/requests/api/v3/bikes_request_spec.rb
spec/requests/api/v3/selections_request_spec.rb
spec/services/bike_creator_builder_spec.rb
spec/services/bike_creator_spec.rb

* Reworks `PropulsionType` as an enum instead of a separate relation or string column

Refactors propulsion_type

---

app/serializers/bike_v2_show_serializer.rb
spec/factories.rb
spec/serializers/bike_serializer_spec.rb
spec/serializers/bike_v2_show_serializer_spec.rb

Just an add of additional_registration to the serializer

add additional_registration to get bike api

---

.circleci/config.yml
README.markdown

When researching the parallelized upload issue I've come accros this repo that seemed to have the same issue I was experiencing.
This PR creates a separate build step that aggregates all reports and then uploads to codeclimate.
Let me know if you have questions.

Update codeclimate to work with parallelized build

---

app/controllers/admin/bikes_controller.rb
app/views/admin/bikes/index.html.haml

Admin bikes index revision

---

app/controllers/api/v2/bikes.rb
app/models/b_param.rb
spec/models/b_param_spec.rb
spec/requests/api/v2/bikes_request_spec.rb
spec/requests/api/v3/bikes_request_spec.rb

Dedupe registration (seth work)

---

app/controllers/api/v2/bikes.rb
app/services/bike_finder.rb
spec/requests/api/v3/bikes_request_spec.rb
spec/services/bike_finder_spec.rb

- Adds request-spec test cases for matching criteria

Add match cases request specs

---

app/controllers/admin/organizations_controller.rb
app/helpers/application_helper.rb
app/javascript/packs/pages/binx_org_bikes.js
app/views/admin/organizations/_admin_organizations_table.html.haml
app/views/admin/organizations/index.html.haml

Also fix organized view bikes table

Display admin organizations counts

---

app/assets/stylesheets/revised/fonts.scss
app/assets/stylesheets/revised/pages/bikes/show.scss
app/controllers/admin/partial_bikes_controller.rb
app/javascript/packs/application_css.scss
app/javascript/packs/pages/admin/binx_admin.js
app/javascript/packs/utils/LoadFancySelects.js
app/javascript/stylesheets/_admin.scss
app/views/admin/bikes/_bike.html.haml
app/views/bikes/_organized_access_panel.html.haml
app/views/bikes/show.html.haml
app/views/layouts/new_admin.html.haml
spec/services/webhook_runner_spec.rb

Almost certainly shouldn't have spent the past hour on this, but it brought me pleasure.

Additional niceities for admin bikes

---

app/views/welcome/index.html.haml

Update homepage bikes recovered value

---

app/views/admin/stolen_bikes/index.html.haml
spec/controllers/admin/stolen_bikes_controller_spec.rb

Fixes the bug in 615d4ec (a nil-invocation / NoMethodError bug)

Fix bug in admin stolen bikes index template

---

app/controllers/bikes/recovery_controller.rb
app/models/stolen_record.rb
app/views/admin/bikes/_bike.html.haml
app/views/admin/recoveries/edit.html.haml
app/views/admin/recoveries/index.html.haml
spec/controllers/bikes/recovery_controller_spec.rb
spec/models/stolen_record_spec.rb

Some additional functionality for recovering_user, which was added in #790
- Specs
- Admin display

Add additional recovering_user functionality

---

app/assets/javascripts/revised/sections/nav_header.coffee
app/assets/stylesheets/revised/sections/primary_header_nav.scss
app/views/layouts/application_revised.html.haml

Mobile topbar improvements

---

app/controllers/welcome_controller.rb
app/views/welcome/recovery_stories.html.haml

Craig wants more recovery stories, so I added some more to the page.
He also thought it would be impressive if we displayed the total number of pages in the pagination. I don't remember exactly why we switched to window 0, but [I complimented @jmromer on doing it](https://github.com/bikeindex/bike_index/pull/710#discussion_r277741239), so there was definitely a reason.

Add more recovery stories

---

app/controllers/admin/organizations_controller.rb
spec/controllers/admin/organizations_controller_spec.rb

Admin organizations 404

---

README.markdown
bin/spring
lib/tasks/dev_configuration.rake

From @jmromer in [#875](https://github.com/bikeindex/bike_index/pull/875#issuecomment-500925425)
> if you're not familiar with spring and end up in a situation where it's causing the app or tests to hang, I can see that being really frustrating.

Switch default to disabled for spring

---

app/models/feedback.rb
app/views/admin/feedbacks/index.html.haml
db/migrate/20190611223723_drop_freedback_hash_text.rb
db/structure.sql

Remove feedback_hash_text

---

app/assets/javascripts/revised/pages/bikes/edit.coffee
app/assets/javascripts/revised/pages/bikes/edit_groups.coffee

Correct js initialization for bike edit groups

---

README.markdown
bin/setup

As per https://github.com/bikeindex/bike_index/pull/888#issuecomment-501927822

use bin/setup in readme

---

app/models/recovery_display.rb
spec/factories/recovery_displays.rb
spec/models/recovery_display_spec.rb

Admin recoveries update after display

---

app/controllers/bikes_controller.rb
spec/controllers/bikes_controller_spec.rb

Remove publicize_theft feature flag

---

README.markdown
config/environments/development.rb
lib/tasks/dev_configuration.rake

Most of the time it's great! But when I'm creating a bunch of new accounts to test sign in, it's frustrating.

Toggle for letter opener

---

app/services/ambassador_task_assignment_creator.rb

I'm still unclear on why these insertions aren't idempotent when run from Sidekiq jobs -- the queries look good, after re-checking them — but as an expedient fix this patch reverts to iterative insertion as a safeguard. Model-layer validation should prevent any dupes from being created.
Closes #908

Use find_each to insert task assignments

---

Gemfile
Gemfile.lock
config/application.rb
config/initializers/flipper.rb
spec/rails_helper.rb
spec/support/controller_spec_helpers.rb
spec/support/json_helpers.rb
spec/support/request_spec_helpers.rb

- Adds [timecop](https://github.com/travisjeffery/timecop) gem for freezing time
- Adds a flipper superusers group
- Separates helpers for request and controller specs, and extracts json-request-related helpers 
Extracted from #915

Add timecop. flipper group, separated request spec helpers

---

app/assets/javascripts/revised/pages/bikes/edit.coffee
app/assets/javascripts/revised/pages/bikes/edit_alert.coffee
app/assets/javascripts/revised/pages/bikes/edit_alert_purchase.coffee
app/assets/stylesheets/revised/mixins/_colors.scss
app/assets/stylesheets/revised/pages/bikes/edit_alert.scss
app/controllers/bikes_controller.rb
app/controllers/theft_alerts_controller.rb
app/mailers/admin_mailer.rb
app/models/stolen_record.rb
app/models/theft_alert.rb
app/views/admin_mailer/theft_alert_purchased.html.haml
app/views/admin_mailer/theft_alert_purchased.text.haml
app/views/bikes/_edit_primary_menu.html.haml
app/views/bikes/_theft_alerts_table.html.haml
app/views/bikes/edit_alert.html.haml
app/views/bikes/edit_alert_purchase.html.haml
app/views/bikes/edit_alert_purchase_confirmation.html.haml
app/views/bikes/edit_publicize.html.haml
app/views/theft_alert_plans/_theft_alert_plan.html.haml
app/workers/deactivate_expired_theft_alert_worker.rb
app/workers/theft_alert_purchase_notification_worker.rb
spec/factories/theft_alerts.rb
spec/mailers/admin_mailer_spec.rb
spec/mailers/previews/admin_mailer_preview.rb
spec/requests/theft_alerts_request_spec.rb
spec/vcr_cassettes/TheftAlertsController/POST_/bikes/_bike_id/theft_alerts/given_the_creation_request_fails/redirects_to_the_bike_edit_page_with_a_flash_message.yml
spec/vcr_cassettes/TheftAlertsController/POST_/bikes/_bike_id/theft_alerts/given_the_payment_request_fails/redirects_to_the_bike_edit_page_with_a_flash_message.yml
spec/vcr_cassettes/TheftAlertsController/POST_/bikes/_bike_id/theft_alerts/given_the_theft_alert_and_payment_both_succeed/redirects_to_purchase_confirmation_template.yml
spec/workers/deactivate_expired_theft_alert_worker_spec.rb
spec/workers/theft_alert_purchase_notification_worker_spec.rb

Continued from #921, which was accidentally closed automatically

Add alert purchasing background jobs, update plan selection UI

---

app/controllers/theft_alerts_controller.rb

Kills manual honeybadger notifications in `TheftAlertsController`.
Resolves #935

Kill manual honeybadger notifications

---

app/controllers/admin/theft_alerts_controller.rb
app/controllers/bikes_controller.rb
app/mailers/admin_mailer.rb
app/models/theft_alert.rb
app/views/admin/theft_alerts/edit.html.haml
app/views/admin/theft_alerts/index.html.haml
app/views/bikes/_edit_primary_menu.html.haml
db/migrate/20190624171627_add_theft_alerts_notes.rb
db/structure.sql
spec/controllers/bikes_controller_spec.rb
spec/factories/theft_alerts.rb
spec/mailers/admin_mailer_spec.rb
spec/models/theft_alert_spec.rb
spec/requests/admin/theft_alerts_request_spec.rb

So that we can track updates and changes to the add, and any additional information

Add notes field to theft alerts

---

app/controllers/admin/theft_alerts_controller.rb
app/javascript/stylesheets/_admin.scss
app/models/payment.rb
app/views/admin/ambassador_tasks/edit.html.haml
app/views/admin/bikes/_bike.html.haml
app/views/admin/bikes/edit.html.haml
app/views/admin/ctypes/edit.html.haml
app/views/admin/manufacturers/show.html.haml
app/views/admin/memberships/show.html.haml
app/views/admin/news/edit.html.haml
app/views/admin/organizations/show.html.haml
app/views/admin/ownerships/edit.html.haml
app/views/admin/payments/edit.html.haml
app/views/admin/recoveries/edit.html.haml
app/views/admin/recovery_displays/edit.html.haml
app/views/admin/stolen_bikes/edit.html.haml
app/views/admin/theft_alerts/_table.html.haml
app/views/admin/theft_alerts/edit.html.haml
app/views/admin/theft_alerts/index.html.haml
app/views/admin/tweets/edit.html.haml
app/views/admin/users/edit.html.haml
app/views/bikes/show.html.haml
app/views/memberships/edit.html.haml
app/views/organized/manage/index.html.haml
app/views/organized/users/edit.html.haml
app/views/users/organization_show.html.haml

Also, `confirm: "Are you sure"` in `link_to` needs to be `data: { confirm: "are you sure?" }` to trigger the alert dialog now. Oops!

Frontend updates to admin to improve theft alert flow

---

app/views/welcome/index.html.haml
config/environments/development.rb
config/environments/test.rb
config/locales/en.yml
config/locales/es.yml

- Adds welcome#index translations to en.yml
- Updates config to raise error when translations are missing (in dev and test environments only)
Related:  #963

Externalize welcome#index 

---

app/controllers/admin/bikes_controller.rb
app/controllers/admin/organizations_controller.rb
app/controllers/admin/partial_bikes_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/bikes_controller.rb
app/controllers/concerns/sessionable.rb
app/controllers/organized/bulk_imports_controller.rb
app/controllers/organized/exports_controller.rb
app/controllers/registrations_controller.rb
app/controllers/users_controller.rb
app/models/b_param.rb
app/models/user.rb
config/initializers/params_normalizer.rb
spec/initializers/params_normalizer_spec.rb

To enable replacing all the places we're doing:
```ruby
ActiveRecord::Type::Boolean.new.type_cast_from_database(whatever)
```

Add ParamsNormalizer for boolean normalization

---

app/assets/stylesheets/revised/pages/landing/_home.scss
app/javascript/packs/application_css.scss
app/views/admin/bikes/_bike.html.haml
app/views/admin/bikes/edit.html.haml
app/views/layouts/new_admin.html.haml

More frontend nudges

---

app/assets/stylesheets/documentation_v2.scss
app/assets/stylesheets/revised/sections/_tables.scss
app/controllers/api/base.rb
app/controllers/api/v2/bikes.rb
app/controllers/documentation_controller.rb
app/javascript/packs/pages/admin/bikes_edit.js
app/javascript/packs/pages/admin/binx_admin.js
app/javascript/packs/pages/admin/recovery_display_form.js
app/javascript/packs/pages/binx_org_bikes.js
app/views/bikes/new.html.haml
app/views/documentation/authorize.html.haml
app/views/doorkeeper/applications/_admin_applications.html.haml
app/views/doorkeeper/applications/_delete_form.html.haml
app/views/doorkeeper/applications/_form.html.haml
app/views/doorkeeper/applications/index.html.haml
app/views/doorkeeper/applications/show.html.haml
app/views/doorkeeper/authorized_applications/_delete_form.html.haml
app/views/doorkeeper/authorized_applications/index.html.haml
app/views/organized/bikes/_search.html.haml
spec/controllers/documentation_controller_spec.rb

I tried to figure out how to pass the correct version (the is inherited one) into the desc field for `post ":id/image"` - but couldn't figure it out.
Some things I found that were moderately useful: from within the desc field you can access `local_constants` and `namespace` - but neither of these got me what I needed.
I gave up because we can just always show v3, people reading the documentation should use v3 😉

Improvements for posting bike images

---

app/decorators/bike_decorator.rb
app/models/bike.rb
app/models/user.rb
app/views/admin/users/edit.html.haml
app/views/bikes/_organized_access_panel.html.haml
app/views/bikes/show.html.haml
app/views/users/_edit_root.html.haml
spec/decorators/bike_decorator_spec.rb
spec/models/bike_spec.rb

Move `phoneable_by?` method from decorator to bike itself

Display phones for unstolen notification bikes

---

app/controllers/application_controller.rb

Make request locale logging json, to reduce number of log lines and make it fit with our other logs that are json.

Request locale logging

---

app/assets/stylesheets/revised/pages/organized/messages.scss
app/controllers/organized/messages_controller.rb
app/javascript/packs/pages/binx_org_messages.js
app/views/organized/messages/index.html.haml
app/views/organized/messages/show.html.haml
app/views/organized/stickers/edit.html.haml
app/views/organized/stickers/index.html.haml
app/views/organized/users/edit.html.haml
app/views/organized/users/index.html.haml
app/views/organized/users/new.html.haml
config/locales/en.yml

Externalizes strings from the following templates:
-  stickers/edit.html.haml
-   stickers/index.html.haml
-   users/edit.html.haml
-   users/index.html.haml
-   users/new.html.haml

Externalize remaining organized templates

---

app/controllers/concerns/sessionable.rb
app/models/user.rb
app/views/admin/users/edit.html.haml
db/migrate/20190710230727_add_last_login_ip_to_users.rb
db/structure.sql
spec/controllers/sessions_controller_spec.rb
spec/models/user_spec.rb

There is no reason to include this in the Magic Link PR (#1010).
Doing it here.

Add user last login information

---

app/views/bikes/scanned.html.haml

Fixes a typo in bikes/scanned
Resolves https://app.honeybadger.io/projects/35931/faults/52131516

Fix scanned_bike url helper

---

app/views/bikes/scanned.html.haml

Fixes https://app.honeybadger.io/projects/35931/faults/52132474

Fix typo in bikes/scanned template

---

app/assets/stylesheets/revised/pages/news/show.scss
app/assets/stylesheets/revised/sections/legacy_content.scss
app/views/info/lightspeed.html.haml
app/views/shared/_organized_skeleton.html.haml

- Add additional POS links to organized display panel
- Add Lightspeed instruction video to lightspeed page

POS integration display improvements

---

app/models/recovery_display.rb
app/views/admin/recovery_displays/_form.html.haml
spec/models/recovery_display_spec.rb

If image is currently processing, display that.

Recovery display processing

---

app/models/b_param.rb
app/models/bike.rb
app/models/export.rb
app/views/bikes/_organized_access_panel.html.haml
app/workers/averyable_bike_worker.rb
spec/models/b_param_spec.rb
spec/vcr_cassettes/b_param-fetch_formatted_address-fail.yml

The process of checking to figure out if a bike can be exported is inefficient.
So use a job to check them all quickly.

Add a job to collect the bikes that aren't avery exportable

---

app/models/paid_feature.rb
app/models/user.rb
app/views/admin/paid_features/_form.html.haml
app/views/organized/users/new.html.haml
app/workers/process_membership_worker.rb
config/locales/en.yml
config/locales/nl.yml
spec/controllers/organized/users_controller_spec.rb
spec/i18n_spec.rb
spec/workers/bike_deleter_worker_spec.rb
spec/workers/process_membership_worker_spec.rb

Because law enforcement wants the ability to add users who don't have passwords, who never see passwords, because passwords are bad or whatever.

Automatically generate users

---

README.markdown
app/assets/javascripts/init.coffee
app/assets/javascripts/revised/pages/bikes/edit_accessories.coffee
app/assets/javascripts/revised/pages/bikes/edit_groups.coffee
app/assets/javascripts/revised/pages/organized/manage_locations.coffee
app/models/bike.rb
app/views/bikes/edit_bike_details.html.haml
app/views/bikes/edit_groups.html.haml
config/locales/en.yml
config/locales/nl.yml
lib/tasks/rake_tasks.rake
spec/models/bike_spec.rb

It will help with Edmonton's flow

Always display sticker for editing bikes

---

lib/tasks/rake_tasks.rake
spec/i18n_spec.rb

It would be really cool if we still got the colors from the `i18n-tasks`

Prepare translations rake task

---

app/controllers/application_controller.rb
app/controllers/users_controller.rb
app/mailers/customer_mailer.rb
app/mailers/organized_mailer.rb
app/models/organization_message.rb
app/models/stolen_notification.rb
app/views/organized/messages/show.html.haml
app/views/sessions/magic_link.html.haml
app/views/sessions/new.html.haml
config/i18n-tasks.yml
config/locales/customer_mailer.en.yml
config/locales/customer_mailer.nl.yml
config/locales/doorkeeper.en.yml
config/locales/doorkeeper.nl.yml
config/locales/en.yml
config/locales/gflash.en.yml
config/locales/gflash.nl.yml
config/locales/organized_mailer.en.yml
config/locales/organized_mailer.nl.yml
spec/mailers/customer_mailer_spec.rb
spec/mailers/organized_mailer_spec.rb

Deliver emails localized

---

app/controllers/bikes_controller.rb
app/views/bikes/_stolen_checklist.html.haml
config/locales/en.yml
config/locales/nl.yml
spec/controllers/bikes_controller_spec.rb

- Rename Premium to Promoted
- Remove flipper (promoted alerts are fully on)

Switch to Promoted alerts

---

app/controllers/integrations_controller.rb
app/models/user.rb
spec/controllers/integrations_controller_spec.rb
spec/models/user_spec.rb

https://app.honeybadger.io/projects/35931/faults/52333305
Seems like we're running into an issue where the user isn't creating, let's see what the error is!

Add descriptive error to update_last_login failure

---

app/services/time_parser.rb
spec/services/time_parser_spec.rb

If passed a time, it should just return the time

Time parser parses times

---

Gemfile
Gemfile.lock
config/initializers/carrierwave.rb

After #1071, unable to deploy because of fog issue. Fix that issue

Fix carrierwave

---

app/views/organized/users/edit.html.haml

Resolves https://app.honeybadger.io/projects/35931/faults/52633795

Fix nil NoMethodError in organized/users/edit

---

app/controllers/api/v1/users_controller.rb
app/controllers/api/v2/bikes.rb
app/models/bike.rb
app/models/user.rb
app/services/bike_updator.rb
app/views/bikes/_bike_show_overlays.html.haml
spec/controllers/bikes_controller_spec.rb
spec/models/bike_code_spec.rb
spec/models/bike_spec.rb
spec/models/user_spec.rb
spec/requests/api/v3/bikes_request_spec.rb

We have two other `authorized?` methods

Rename authorized_for_user? to authorized? for consistency

---

config/locales/.translation_io
config/locales/en.yml

Adds changes from `bin/rake translations:sync` on master

Sync translations

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 5934: https://circleci.com/gh/bikeindex/bike_index/5934
Related: PR

[i18n] Translation update

---

Vagrantfile

Looks like I overlooked this line in the Gemfile in #1020:
```rb
ruby "2.5.5"
```

Update Ruby version in Vagrantfile

---

app/uploaders/alert_image_uploader.rb

Kill logging in AlertImageUploader

---

app/services/alert_image_generator.rb

Add fallback font, use `caption_font`

---

app/views/layouts/application_revised.html.haml

https://stackoverflow.com/questions/49627037/bootstrap-4-navbar-dropdown-not-working-on-ios-devices-safari

Fix Dropdowns on iOS

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 6232: https://circleci.com/gh/bikeindex/bike_index/6232

[i18n] Translation update: Build 6232

---

.circleci/config.yml
bin/check_translations

Adds another step in the automated translation sync script to normalize translation files after pulling new translations.

Normalize when syncing translations

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 6267: https://circleci.com/gh/bikeindex/bike_index/6267

[i18n] Translation update: Build 6267

---

app/controllers/admin/organizations/invoices_controller.rb
app/models/invoice.rb
app/models/organization.rb
app/views/admin/organizations/invoices/_form.html.haml
app/views/admin/organizations/invoices/_table.html.haml
app/views/admin/organizations/show.html.haml
db/migrate/20190809200257_add_child_paid_features_to_invoices.rb
db/structure.sql
spec/controllers/admin/organizations/invoices_controller_spec.rb
spec/controllers/organized/users_controller_spec.rb
spec/models/invoice_spec.rb
spec/models/organization_spec.rb
spec/models/paid_feature_spec.rb

Example:
Edmonton has paid for QR stickers. All the shops in Edmonton need access to the QR sticker interface.
The shops in Edmonton _should not_ be forced to use passwordless log in.

Specify which paid features are shared with child organizations

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 6381: https://circleci.com/gh/bikeindex/bike_index/6381

[i18n] Translation update: Build 6381

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 6393: https://circleci.com/gh/bikeindex/bike_index/6393

[i18n] Translation update: Build 6393

---

app/models/user.rb
spec/models/user_spec.rb

Use outer join, so that we match users without user_emails :/

Fix admin text search

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 6453: https://circleci.com/gh/bikeindex/bike_index/6453

[i18n] Translation update: Build 6453

---

config/locales/.translation_io
config/locales/translation.nl.yml

Translation sync and purge

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 6614: https://circleci.com/gh/bikeindex/bike_index/6614

[i18n] Translation update: Build 6614

---

app/views/shared/_organized_skeleton.html.haml
config/locales/en.yml

Fixes interpolation argument name in organized skeleton template.
Fixes https://app.honeybadger.io/projects/35931/faults/53835752

Fix interpolation arg name

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 6649: https://circleci.com/gh/bikeindex/bike_index/6649

[i18n] Translation update: Build 6649

---

app/views/locks/_form.html.haml
app/views/locks/_lock_home.html.haml
app/views/locks/edit.html.haml
app/views/locks/new.html.haml
config/locales/en.yml

Externalize locks templates

---

app/views/organization_invitations/not_available.html.haml
app/views/payments/_form.html.haml
app/views/payments/create.html.haml
app/views/payments/new.html.haml
app/views/registrations/create.html.haml
app/views/registrations/embed.html.haml
app/views/shared/_errors.html.haml
config/locales/en.yml

Externalize organization_invitations, payments, registrations templates

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 6796: https://circleci.com/gh/bikeindex/bike_index/6796

[i18n] Translation update: Build 6796

---

app/views/organizations/_new_form.html.haml
app/views/organizations/embed.html.haml
app/views/organizations/embed_create_success.html.haml
app/views/organizations/embed_extended.html.haml
app/views/organizations/new.html.haml
config/locales/en.yml

Externalize organizations templates

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 6798: https://circleci.com/gh/bikeindex/bike_index/6798

[i18n] Translation update: Build 6798

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 6806: https://circleci.com/gh/bikeindex/bike_index/6806

[i18n] Translation update: Build 6806

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 6818: https://circleci.com/gh/bikeindex/bike_index/6818

[i18n] Translation update: Build 6818

---

app/serializers/bike_v2_serializer.rb

Resolves https://app.honeybadger.io/projects/35931/faults/54294084

Fix placeholder image in bike serializer

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 6915: https://circleci.com/gh/bikeindex/bike_index/6915

[i18n] Translation update: Build 6915

---

app/views/welcome/user_home.html.haml
config/locales/en.yml

Change key to see if translation updates

---

app/views/welcome/user_home.html.haml
bin/check_translations
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.nl.yml

Merge to unblock CI job 6952: https://circleci.com/gh/bikeindex/bike_index/6952

[i18n] Translation update: Build 6952

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 6957: https://circleci.com/gh/bikeindex/bike_index/6957

[i18n] Translation update: Build 6957

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 6976: https://circleci.com/gh/bikeindex/bike_index/6976

[i18n] Translation update: Build 6976

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 7004: https://circleci.com/gh/bikeindex/bike_index/7004

[i18n] Translation update: Build 7004

---

app/views/public_images/_form.html.haml
app/views/public_images/_new_form.html.erb
app/views/public_images/_public_image.html.erb
app/views/public_images/_revised_public_image.html.haml
app/views/public_images/edit.html.erb
app/views/public_images/new.html.erb
app/views/public_images/show.html.erb
config/locales/en.yml

Tracking: https://github.com/bikeindex/bike_index/issues/963

Externalize public images templates

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 7039: https://circleci.com/gh/bikeindex/bike_index/7039

[i18n] Translation update: Build 7039

---

app/controllers/admin/bikes_controller.rb
app/controllers/admin/graphs_controller.rb
app/controllers/admin/recoveries_controller.rb
app/controllers/admin/recovery_displays_controller.rb
app/controllers/bikes/recovery_controller.rb
app/controllers/organized/bikes_controller.rb
app/models/counts.rb
app/models/recovery_display.rb
app/models/stolen_record.rb
app/views/admin/bikes/_bike.html.haml
app/views/admin/graphs/tables.html.haml
app/views/admin/recoveries/_table.html.haml
app/views/admin/recovery_displays/_form.html.haml
app/views/admin/recovery_displays/index.html.haml
app/views/bikes/_bike_show_overlays.html.haml
app/views/organized/bikes/recoveries.html.haml
app/views/recovery_displays/_recovery_display.html.haml
config/locales/en.yml
config/locales/translation.nl.yml
db/migrate/20190909190050_rename_stolen_record_date_recovered_to_recovered_at.rb
db/structure.sql
spec/controllers/api/v1/users_controller_spec.rb
spec/controllers/bikes/recovery_controller_spec.rb
spec/controllers/organized/bikes_controller_spec.rb
spec/factories/stolen_records.rb
spec/mailers/previews/customer_mailer_preview.rb
spec/models/bike_spec.rb
spec/models/counts_spec.rb
spec/models/recovery_display_spec.rb
spec/models/stolen_record_spec.rb

Because it isn't a date, it's a time. Also because consistency.

rename date_recovered to recovered_at

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 7056: https://circleci.com/gh/bikeindex/bike_index/7056

[i18n] Translation update: Build 7056

---

lib/integrations/twitter_tweeter_integration.rb

Adds more context to stolen bike alert tweet failure exceptions so we can tell which accounts have outdated credentials or have been suspended:
Related:
https://app.honeybadger.io/projects/35931/faults/54742393
https://app.honeybadger.io/projects/35931/faults/54742441

Add context to tweet failure exceptions

---

lib/integrations/twitter_tweeter_integration.rb

Fix Twitter exceptions: `to_s` is not defined on these

---

app/views/admin/twitter_accounts/_form.html.haml
app/views/admin/twitter_accounts/edit.html.haml
app/views/admin/twitter_accounts/new.html.haml

Minor update to the form display for the twitter accounts - addition to #1246

Update the form display

---

app/controllers/admin/twitter_accounts_controller.rb
app/models/twitter_account.rb
app/views/admin/stolen_bikes/edit.html.haml
app/views/admin/stolen_bikes/index.html.haml
app/views/admin/twitter_accounts/_errored.html.haml
app/views/admin/twitter_accounts/_form.html.haml
app/views/admin/twitter_accounts/edit.html.haml
app/views/admin/twitter_accounts/index.html.haml
app/views/admin/twitter_accounts/show.html.haml
db/migrate/20190916191514_add_last_error_at_to_twitter_accounts.rb
db/structure.sql
spec/models/twitter_account_spec.rb

Display twitter API errors!
- show on the page when doing stolen bike
- show the error on the twitter page
- Sort twitter accounts

Admin twitter accounts frontend improvements

---

lib/integrations/twitter_tweeter_integration.rb

Resolve https://app.honeybadger.io/projects/35931/faults/54852612

Fix tweet image size error

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 7315: https://circleci.com/gh/bikeindex/bike_index/7315

[i18n] Translation update: Build 7315

---

app/controllers/admin/customer_contacts_controller.rb
app/controllers/api/v1/notifications_controller.rb
app/models/customer_contact.rb
app/views/admin/stolen_bikes/edit.html.haml
app/workers/approve_stolen_listing_worker.rb
config/locales/en.yml
db/migrate/20190918143646_remove_contact_type_from_customer_contacts.rb
db/structure.sql
spec/controllers/admin/customer_contacts_controller_spec.rb
spec/factories.rb
spec/mailers/customer_mailer_spec.rb
spec/models/customer_contact_spec.rb

Merge after data migration in #1268 is run
```
jake6001@hawk:/var/deploy/bike_index/web_head/current$ bundle exec rake data:migrate_customer_contact_types:up
Updating 47017 customer_contact records...
47017/47017 : 100.0%
Done!
```

Complete contact_type data migration

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 7324: https://circleci.com/gh/bikeindex/bike_index/7324

[i18n] Translation update: Build 7324

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 7356: https://circleci.com/gh/bikeindex/bike_index/7356

[i18n] Translation update: Build 7356

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 7419: https://circleci.com/gh/bikeindex/bike_index/7419

[i18n] Translation update: Build 7419

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 7435: https://circleci.com/gh/bikeindex/bike_index/7435

[i18n] Translation update: Build 7435

---

config/locales/.translation_io
config/locales/en.yml

Merge to unblock CI job 7512: https://circleci.com/gh/bikeindex/bike_index/7512

[i18n] Translation update: Build 7512

---

app/workers/get_manufacturer_logo_worker.rb
app/workers/scheduled_worker_recorder.rb
app/workers/tsv_creator_worker.rb
app/workers/unused_ownership_removal_worker.rb

Adds conditional branching to bypass recording when arguments are passed

Extend ScheduledWorkerRecorder

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 7816: https://circleci.com/gh/bikeindex/bike_index/7816

[i18n] Translation update: Build 7816

---

app/controllers/bikes_controller.rb
app/controllers/concerns/controller_helpers.rb
config/locales/en.yml

Externalize strings for BikeController
Tracking: https://github.com/bikeindex/bike_index/issues/963

Externalize strings for BikeController

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 7825: https://circleci.com/gh/bikeindex/bike_index/7825

[i18n] Translation update: Build 7825

---

config/locales/.translation_io
config/locales/en.yml

Merge to unblock CI job 7837: https://circleci.com/gh/bikeindex/bike_index/7837

[i18n] Translation update: Build 7837

---

app/assets/stylesheets/revised/sections/bike_boxes.scss

Fix stretched hover previews

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 7863: https://circleci.com/gh/bikeindex/bike_index/7863

[i18n] Translation update: Build 7863

---

app/models/bike.rb
app/models/bike_code.rb
app/models/export.rb
app/models/manufacturer.rb
app/models/organization_message.rb
app/models/payment.rb
app/models/recovery_display.rb
app/models/theft_alert.rb
app/models/user.rb
config/locales/en.yml
spec/controllers/organized/messages_controller_spec.rb
spec/models/bike_spec.rb
spec/models/organization_message_spec.rb
spec/models/user_spec.rb

Externalizes custom error message strings from models
Tracking #963

Externalize model error messages

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 7875: https://circleci.com/gh/bikeindex/bike_index/7875

[i18n] Translation update: Build 7875

---

app/models/country.rb
app/services/stolen_record_updator.rb
app/views/admin/graphs/stolen_locations.html.haml
spec/controllers/api/v1/bikes_controller_spec.rb
spec/models/country_spec.rb

- Optimizes `fuzzy_find` by performing the search in a single query
- Increases module depth
- There are only two call sites for `fuzzy_iso_find`

Consolidate Country.fuzzy find and Country.fuzzy_iso_find

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 7969: https://circleci.com/gh/bikeindex/bike_index/7969

[i18n] Translation update: Build 7969

---

app/controllers/ownerships_controller.rb
app/controllers/user_emails_controller.rb
app/controllers/users_controller.rb
config/locales/en.yml

I18n: Externalize strings from users, user_emails, ownerships controllers

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8028: https://circleci.com/gh/bikeindex/bike_index/8028

[i18n] Translation update: Build 8028

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8027: https://circleci.com/gh/bikeindex/bike_index/8027

[i18n] Translation update: Build 8027

---

app/views/bikes/index.html.haml
config/locales/en.yml

Fix locale loss when submitting bike search form

---

config/locales/.translation_io
config/locales/translation.nl.yml

Update NL translations to reflect changes in `en.yml`, updated via the translation.io dashboard.

Sync Dutch translations

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8185: https://circleci.com/gh/bikeindex/bike_index/8185

[i18n] Translation update: Build 8185

---

app/controllers/bikes_controller.rb
app/controllers/concerns/controller_helpers.rb
app/controllers/concerns/sessionable.rb
app/controllers/oauth/applications_controller.rb
app/controllers/organized/ambassador_task_assignments_controller.rb
app/controllers/organized/base_controller.rb
app/controllers/organized/bikes_controller.rb
app/controllers/organized/bulk_imports_controller.rb
app/controllers/organized/exports_controller.rb
app/controllers/organized/manage_controller.rb
app/controllers/organized/messages_controller.rb
app/controllers/organized/stickers_controller.rb
app/controllers/organized/users_controller.rb
app/controllers/ownerships_controller.rb
app/controllers/welcome_controller.rb
config/locales/en.yml

Externalize remaining controllers

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8203: https://circleci.com/gh/bikeindex/bike_index/8203

[i18n] Translation update: Build 8203

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8228: https://circleci.com/gh/bikeindex/bike_index/8228

[i18n] Translation update: Build 8228

---

app/views/shared/_content_skeleton.html.haml
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.nl.yml

Translate content sidebar

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8280: https://circleci.com/gh/bikeindex/bike_index/8280

[i18n] Translation update: Build 8280

---

lib/integrations/twitter_tweeter_integration.rb

Fixes https://app.honeybadger.io/projects/35931/faults/56142114

Fix NoMethodError when no manufacturer present

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8298: https://circleci.com/gh/bikeindex/bike_index/8298

[i18n] Translation update: Build 8298

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8299: https://circleci.com/gh/bikeindex/bike_index/8299

[i18n] Translation update: Build 8299

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8361: https://circleci.com/gh/bikeindex/bike_index/8361

[i18n] Translation update: Build 8361

---

app/views/welcome/user_home.html.haml
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.nl.yml

Externalizes strings from the Register New Items / Next Steps sidebar

Externalize sidebar strings

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8397: https://circleci.com/gh/bikeindex/bike_index/8397

[i18n] Translation update: Build 8397

---

app/views/bikes/edit_alert_purchase.html.haml

Fixes https://app.honeybadger.io/projects/35931/faults/56314792

Fix undefined variable currency

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8433: https://circleci.com/gh/bikeindex/bike_index/8433

[i18n] Translation update: Build 8433

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8464: https://circleci.com/gh/bikeindex/bike_index/8464

[i18n] Translation update: Build 8464

---

app/models/external_registry_client/stop_heling_client.rb

Resolves https://app.honeybadger.io/projects/35931/faults/56419235

Fix typo in HoneyBadger invocation

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8505: https://circleci.com/gh/bikeindex/bike_index/8505

[i18n] Translation update: Build 8505

---

app/views/bikes/_organized_access_panel.html.haml
config/locales/en.yml

Add some extra visibility into bike registration for bikes registered by parent organizations

Child organization visibility

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8650: https://circleci.com/gh/bikeindex/bike_index/8650

[i18n] Translation update: Build 8650

---

app/views/organized_mailer/finished_registration.html.haml
app/views/organized_mailer/finished_registration.text.haml

- Fixes a bug whereby the text version of this email erroneously stated that the
bike registered was stolen.

Consistify finished_registration bike type logic

---

config/locales/.translation_io
config/locales/translation.nl.yml

Fixes https://app.honeybadger.io/projects/35931/faults/57320139

Fix missing interpolation argument exceptions

---

config/locales/.translation_io
config/locales/en.yml
config/locales/translation.nl.yml

Merge to unblock CI job 8883: https://circleci.com/gh/bikeindex/bike_index/8883

[i18n] Translation update: Build 8883

---

lib/tasks/data_migrations.rake

Removes the data migration used to set location info on bikes

Kill bikes location data migration

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8907: https://circleci.com/gh/bikeindex/bike_index/8907

[i18n] Translation update: Build 8907

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 8973: https://circleci.com/gh/bikeindex/bike_index/8973

[i18n] Translation update: Build 8973

---

app/controllers/admin/dashboard_controller.rb
app/controllers/organized/dashboard_controller.rb
app/helpers/application_helper.rb
app/helpers/cache_helper.rb
app/helpers/graphing_helper.rb
app/models/organization.rb
app/views/admin/dashboard/index.html.haml
app/views/organized/dashboard/index.html.haml
spec/controllers/bikes_controller_spec.rb
spec/helpers/application_helper_spec.rb
spec/helpers/graphing_helper_spec.rb
spec/models/organization_spec.rb
spec/support/geocoder_default_location.rb
spec/support/shared_examples/bike_searchable.rb

Include current_organization in organization dashboard counts

---

app/assets/stylesheets/og_application.css

We're having some trouble with asset compilation. Try this, since we want it anyway

unminify og_application.css

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 9573: https://circleci.com/gh/bikeindex/bike_index/9573

[i18n] Translation update: Build 9573

---

app/models/payment.rb
db/migrate/20200108232256_remove_is_payments_boolean.rb
db/structure.sql

Remove is_payment from payments

---

app/controllers/concerns/controller_helpers.rb
app/controllers/payments_controller.rb
app/views/admin/payments/index.html.haml

Small fixes

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 10137: https://circleci.com/gh/bikeindex/bike_index/10137

[i18n] Translation update: Build 10137

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 10171: https://circleci.com/gh/bikeindex/bike_index/10171

[i18n] Translation update: Build 10171

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 10248: https://circleci.com/gh/bikeindex/bike_index/10248

[i18n] Translation update: Build 10248

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 10358: https://circleci.com/gh/bikeindex/bike_index/10358

[i18n] Translation update: Build 10358

---

app/services/bike_creator.rb
app/views/organized/bikes/recoveries.html.haml

- Fix issue causing null value in stolen [honeybadger](https://app.honeybadger.io/projects/35931/faults/60203106)
- Null bike on recoveries display

Null fixes

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 10415: https://circleci.com/gh/bikeindex/bike_index/10415

[i18n] Translation update: Build 10415

---

app/workers/temporary_set_location_worker.rb

Add temporary worker for setting location

---

app/models/bike.rb
app/views/admin/organizations/show.html.haml
app/workers/temporary_set_location_worker.rb

Fix temporary worker for setting address on Bike

---

app/models/paid_feature.rb
app/views/bikes/_organized_access_panel.html.haml
app/views/organized/bikes/_search.html.haml
app/workers/temporary_set_location_worker.rb
config/locales/en.yml
spec/models/paid_feature_spec.rb

Better handling for additional reg fields

---

app/controllers/organized/bikes_controller.rb
app/helpers/organized_helper.rb
app/javascript/packs/pages/binx_org_bikes.js
app/views/admin/paid_features/_form.html.haml
app/views/organized/bikes/_search.html.haml
app/views/organized/bikes/recoveries.html.haml
app/views/organized/exports/show.html.haml
app/views/organized/messages/index.html.haml
app/views/organized/parking_notifications/index.html.haml
app/views/organized/users/new.html.haml
app/views/shared/_organized_skeleton.html.haml
spec/helpers/organized_helper_spec.rb

Immediate merges from Location Appointments

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 10639: https://circleci.com/gh/bikeindex/bike_index/10639

[i18n] Translation update: Build 10639

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 10663: https://circleci.com/gh/bikeindex/bike_index/10663

[i18n] Translation update: Build 10663

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 10835: https://circleci.com/gh/bikeindex/bike_index/10835

[i18n] Translation update: Build 10835

---

app/models/b_param.rb
app/models/bike.rb
app/models/concerns/geocodeable.rb
app/models/organization.rb
app/models/stolen_record.rb
app/services/alert_image_generator.rb
app/services/bike_creator.rb
app/services/bike_updator.rb
app/services/geohelper.rb
app/views/bikes/edit_bike_details.html.haml
app/workers/after_user_create_worker.rb
db/migrate/20200420181614_add_manually_set_address_to_bike.rb
db/structure.sql
spec/controllers/bikes_controller_spec.rb
spec/models/bike_spec.rb
spec/models/organization_spec.rb
spec/requests/bikes_request_spec.rb
spec/services/alert_image_generator_spec.rb
spec/services/bike_updator_spec.rb
spec/services/geohelper_spec.rb
spec/vcr_cassettes/bike_request-set_manual_address.yml
spec/vcr_cassettes/geohelper-formatted_address_hash.yml
spec/vcr_cassettes/geohelper-formatted_address_hash2.yml
spec/workers/after_user_create_worker_spec.rb
spec/workers/bulk_import_worker_spec.rb
spec/workers/organization_export_worker_spec.rb

Additional handling for bike locations

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 10920: https://circleci.com/gh/bikeindex/bike_index/10920

[i18n] Translation update: Build 10920

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 11012: https://circleci.com/gh/bikeindex/bike_index/11012

[i18n] Translation update: Build 11012

---

db/migrate/20200429004612_remove_has_stolen_bikes_without_locations_from_users.rb
db/structure.sql
spec/controllers/api/v1/users_controller_spec.rb

Follow along to #1576, which added general_alerts

Remove has_stolen_bikes_without_locations

---

app/controllers/api/v1/organizations_controller.rb
app/models/stolen_record.rb
app/serializers/membership_serializer.rb
app/services/stolen_record_updator.rb
spec/models/bike_spec.rb
spec/requests/api/v1/organizations_request_spec.rb
spec/requests/bikes_request_spec.rb

Also, fix a few things in API V1, because mixing things together is fun (shoulda been part of #1580)

Ensure alert regenerates with new location

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 11207: https://circleci.com/gh/bikeindex/bike_index/11207

[i18n] Translation update: Build 11207

---

app/controllers/sessions_controller.rb
app/models/membership.rb
app/models/user.rb
app/workers/after_user_create_worker.rb
app/workers/email_magic_login_link_worker.rb
app/workers/email_reset_password_worker.rb
app/workers/process_membership_worker.rb
spec/controllers/users_controller_spec.rb
spec/requests/sessions_request_spec.rb
spec/workers/after_user_create_worker_spec.rb
spec/workers/email_magic_link_worker_spec.rb
spec/workers/email_reset_password_worker_spec.rb

Users create with autogenerated whitelisted domain

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 11343: https://circleci.com/gh/bikeindex/bike_index/11343

[i18n] Translation update: Build 11343

---

app/controllers/bikes_controller.rb
app/models/bike.rb
app/models/graduated_notification.rb
app/views/organized/graduated_notifications/_table.html.haml
app/workers/create_graduated_notification_worker.rb
app/workers/process_graduated_notification_worker.rb
app/workers/scheduled_worker_runner.rb
spec/requests/bikes_request_spec.rb
spec/requests/organized/graduated_notifications_request_spec.rb
spec/workers/create_graduated_notification_worker_spec.rb
spec/workers/process_graduated_notification_worker_spec.rb

Graduated notification followup

---

app/controllers/admin/graduated_notifications_controller.rb
app/models/graduated_notification.rb
app/views/admin/graduated_notifications/index.html.haml
app/views/organized/graduated_notifications/_table.html.haml
app/views/organized_mailer/graduated_notification.html.haml
config/routes.rb
spec/requests/admin/graduated_notifications_request_spec.rb

Also, reset pending period to be 24 hours (follows #1612)

Add graduated notifications admin display

---

app/controllers/bikes_controller.rb
app/controllers/organized/emails_controller.rb
app/controllers/organized/graduated_notifications_controller.rb
app/controllers/organized/parking_notifications_controller.rb
app/mailers/organized_mailer.rb
app/models/graduated_notification.rb
app/models/mail_snippet.rb
app/views/admin/graduated_notifications/index.html.haml
app/views/bikes/_bike_show_overlays.html.haml
app/views/bikes/_organized_access_panel.html.haml
app/views/bikes/show.html.haml
app/views/organized/emails/edit.html.haml
app/views/organized/graduated_notifications/_table.html.haml
app/views/organized/graduated_notifications/index.html.haml
app/views/organized/graduated_notifications/show.html.haml
app/views/organized/parking_notifications/_show_details.html.haml
app/views/organized_mailer/graduated_notification.html.haml
app/views/organized_mailer/graduated_notification.text.haml
app/views/organized_mailer/parking_notification.html.haml
app/views/organized_mailer/parking_notification.text.haml
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.nl.yml
config/routes.rb
spec/requests/bikes_request_spec.rb
spec/requests/organized/emails_request_spec.rb
spec/requests/organized/graduated_notifications_request_spec.rb
spec/requests/organized/parking_notifications_request_spec.rb

Because email clients can visit the link, and to ensure it actually happens

Use a form submission for marking bike tokens

---

app/assets/javascripts/external_scripts/embed_script.js.coffee
app/assets/stylesheets/embed_styles.css.scss
app/mailers/organized_mailer.rb
app/services/geohelper.rb
app/views/organizations/embed_extended.html.haml
app/views/organized/bikes/new_iframe.html.haml
spec/mailers/organized_mailer_spec.rb
spec/services/geohelper_spec.rb

- Enable email override for hot sheets
- Additional helper text for embed form

Hot sheet email override, parking notification fixes

---

config/locales/.translation_io
config/locales/en.yml

Merge to unblock CI job 11539: https://circleci.com/gh/bikeindex/bike_index/11539

[i18n] Translation update: Build 11539

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 11603: https://circleci.com/gh/bikeindex/bike_index/11603

[i18n] Translation update: Build 11603

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 11676: https://circleci.com/gh/bikeindex/bike_index/11676

[i18n] Translation update: Build 11676

---

app/assets/javascripts/init.coffee
app/controllers/admin/theft_alerts_controller.rb

- Modal close state wasn't being stored (fix for #1641)
- Render theft alert even if bike deleted

Frontend bug fixes

---

app/services/bad_word_cleaner.rb
app/views/organized_mailer/hot_sheet.html.haml
spec/mailers/organized_mailer_spec.rb

... to ensure thumb_path is the most recent available.

Hot sheet email updates all the bikes

---

app/assets/javascripts/init.coffee
app/views/shared/_donation_modal.html.haml
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.nl.yml

Reverts #1641 (also a piece of #1653 that fixed a broken thing)

Midyear fundraiser ends

---

app/javascript/packs/pages/binx_org_bikes.js

Fix organization bikes error

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 11933: https://circleci.com/gh/bikeindex/bike_index/11933

[i18n] Translation update: Build 11933

---

app/decorators/bike_decorator.rb
app/helpers/organized_helper.rb
app/models/bike.rb
app/views/admin/bikes/_bike.html.haml
app/views/admin/bikes/_table.html.haml
app/views/admin/bikes/edit.html.haml
app/views/organized/parking_notifications/_table.html.haml
db/migrate/20200810163704_switch_frame_model_to_text_on_bikes.rb
db/structure.sql
spec/controllers/bikes_controller_spec.rb

- Fix minor issue with parking notifications 
- Admin bike display update

Accept long frame_model strings for bikes

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 12361: https://circleci.com/gh/bikeindex/bike_index/12361

[i18n] Translation update: Build 12361

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 12404: https://circleci.com/gh/bikeindex/bike_index/12404

[i18n] Translation update: Build 12404

---

app/controllers/admin/feedbacks_controller.rb
app/controllers/admin/tweets_controller.rb
app/controllers/admin/twitter_accounts_controller.rb
app/models/feedback.rb
app/models/tweet.rb
app/services/credibility_scorer.rb
app/views/admin/feedbacks/index.html.haml
app/views/admin/feedbacks/show.html.haml
app/views/admin/organizations/show.html.haml
app/views/admin/tweets/index.html.haml
app/views/admin/twitter_accounts/index.html.haml
app/views/stolen/index.html.haml
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.nl.yml
db/migrate/20200901165655_add_kind_to_feedbacks.rb
db/structure.sql
spec/models/feedback_spec.rb
spec/services/credibility_scorer_spec.rb

Also, add `kind` enum to Feedback

Additional user credibility badges

---

app/controllers/organized/bikes_controller.rb
app/javascript/packs/pages/binx_org_bikes.js
app/models/bike.rb
app/views/organized/bikes/_search.html.haml
spec/models/bike_spec.rb
spec/models/organization_spec.rb

Address some performance issues

Avery export updates

---

app/javascript/packs/utils/time_parser.js
app/services/credibility_scorer.rb
spec/services/credibility_scorer_spec.rb

Also, minor time parser spacing fix

Fix credibility scorer deleted organization bug

---

app/controllers/admin/bikes_controller.rb
app/models/bike.rb
app/models/user.rb
app/views/admin/bikes/index.html.haml
spec/models/bike_spec.rb

Follows #1803 - searching users by phone wasn't sufficient :/

Admin search bikes by phone

---

app/views/landing_pages/for_bike_shops.html.haml

New video!

---

app/assets/javascripts/init.coffee
app/assets/javascripts/revised/pages/info/payments.coffee
app/controllers/info_controller.rb
app/views/payments/create.html.haml
spec/requests/info_request_spec.rb

Bug introduced in #1822 - doesn't load the coffeescript

Fix donation bug

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 13249: https://circleci.com/gh/bikeindex/bike_index/13249

[i18n] Translation update: Build 13249

---

app/assets/javascripts/revised/pages/bikes/edit_photos.coffee
app/assets/stylesheets/revised/pages/bikes/stolen_checklist.scss
app/controllers/admin/bulk_imports_controller.rb
app/controllers/bikes_controller.rb
app/controllers/concerns/controller_helpers.rb
app/views/bikes/_edit_primary_menu.html.haml
app/views/bikes/edit_accessories.html.haml
app/views/bikes/edit_bike_details.html.haml
app/views/bikes/edit_drivetrain.html.haml
app/views/bikes/edit_groups.html.haml
app/views/bikes/edit_ownership.html.haml
app/views/bikes/edit_publicize.html.haml
app/views/bikes/edit_remove.html.haml
app/views/bikes/edit_report_recovered.html.haml
app/views/bikes/edit_report_stolen.html.haml
app/views/bikes/edit_theft_details.html.haml
app/views/organized/exports/show.html.haml
spec/requests/bikes_request_spec.rb
spec/support/request_spec_helpers.rb

Extract permitted return to from #1815

Permitted return to in bike edit

---

bin/setup

h/t @joshchernoff https://github.com/bikeindex/bike_index/issues/1846#issuecomment-743820471

uncomment yarn from setup

---

app/services/geohelper.rb
spec/services/geohelper_spec.rb
spec/vcr_cassettes/geohelper-na-formatted_address_hash.yml

Seems to be an issue caused by google now returning an empty value

Fix geocoder issue

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 13341: https://circleci.com/gh/bikeindex/bike_index/13341

[i18n] Translation update: Build 13341

---

app/controllers/admin/impound_records_controller.rb
app/controllers/organized/impound_records_controller.rb
app/models/impound_record.rb
app/models/impound_record_update.rb
app/views/admin/impound_records/index.html.haml
app/views/organized/impound_records/index.html.haml
app/views/organized/manages/locations.html.haml

After shipping, run:
```ruby
ImpoundRecordUpdate.where(kind: "current").update_all(kind: "note")
```

Add resolved search to organized impound records

---

app/controllers/admin/bike_stickers_controller.rb
app/helpers/graphing_helper.rb
app/javascript/scripts/utils/time_parser.js
app/views/admin/bike_stickers/_table.html.haml
app/views/admin/bike_stickers/index.html.haml
app/views/admin/invoices/index.html.haml
spec/helpers/graphing_helper_spec.rb

Improvements for future time periods

Improve time parsing of future periods

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 13509: https://circleci.com/gh/bikeindex/bike_index/13509

[i18n] Translation update: Build 13509

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 13937: https://circleci.com/gh/bikeindex/bike_index/13937

[i18n] Translation update: Build 13937

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 13985: https://circleci.com/gh/bikeindex/bike_index/13985

[i18n] Translation update: Build 13985

---

app/controllers/admin/news_controller.rb
app/views/admin/news/edit.html.haml
db/migrate/20210405200829_remove_blog_tags.rb
db/structure.sql

Follows #1926 - removes the previous `tags` attribute on blogs

Remove blog tags string

---

app/views/admin/graduated_notifications/index.html.haml
app/views/organized/graduated_notifications/_table.html.haml
app/views/organized/graduated_notifications/show.html.haml

Graduated notification language

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 14088: https://circleci.com/gh/bikeindex/bike_index/14088

[i18n] Translation update: Build 14088

---

app/views/info/show.html.haml
app/views/news/index.html.haml
app/views/news/show.html.haml
app/views/stolen_bike_listings/index.html.haml

remove unnecessary div wrapper id

remove #news_display

---

app/assets/javascripts/init.coffee
app/views/bikes/index.html.haml
app/views/layouts/application.html.haml
app/views/my_accounts/show.html.haml
app/views/shared/_donation_form.html.haml
app/views/shared/_donation_modal.html.haml

Caching bug - introduced in #1947

Fix donation modal

---

app/workers/after_bike_save_worker.rb
spec/workers/after_bike_save_worker_spec.rb

Add bike organizations when updating partial registrations

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 14376: https://circleci.com/gh/bikeindex/bike_index/14376

[i18n] Translation update: Build 14376

---

config/locales/.translation_io
config/locales/translation.nl.yml

Merge to unblock CI job 14824: https://circleci.com/gh/bikeindex/bike_index/14824

[i18n] Translation update: Build 14824

---

app/models/bike.rb
app/models/notification.rb
app/workers/update_theft_alert_facebook_worker.rb
db/migrate/20210709164954_add_bike_id_to_notifications_and_reach_to_alerts.rb
db/structure.sql
spec/requests/admin/theft_alerts_request_spec.rb
spec/workers/update_theft_alerft_facebook_worker_spec.rb

Also, temporarily disable `theft_alert_posted` notifications

Add bike association to notifications

---

app/models/mailchimp_datum.rb
spec/vcr_cassettes/update_mailchimp_datum_worker-archived_on_mailchimp.yml
spec/workers/update_mailchimp_datum_worker_spec.rb

Fix https://github.com/bikeindex/bike_index/commit/bf360385b8afd9a855b6394ebc9557896bda8ddc

fix mailchimp archived issue

---

app/assets/javascripts/revised/components/ad_displayer.coffee
app/views/bikes/index.html.haml
app/views/bikes/show.html.haml
app/views/my_accounts/show.html.haml
app/views/shared/_content_skeleton.html.haml
app/views/shared/_google_ad.html.haml
app/views/shared/_google_ad_script.html.haml
app/views/stolen_bike_listings/index.html.haml
app/views/users/show.html.haml

Follows #1996
Also improves google ad handling

Add back in maxtracker ad

---

app/javascript/scripts/pages/binx_org_bikes.js
app/models/bike.rb
app/views/organized/bikes/_search.html.haml
app/workers/migrate_registration_info_worker.rb
config/locales/en.yml

More creation state migration work

---

spec/requests/bikes/recovery_request_spec.rb

Move recoveries controller spec to request spec

recoveries request spec

---

app/controllers/admin/bike_stickers_controller.rb
app/controllers/organized/stickers_controller.rb
app/views/admin/bike_sticker_updates/index.html.haml
app/views/admin/bike_stickers/_table.html.haml
app/views/admin/bike_stickers/index.html.haml
app/views/admin/organizations/show.html.haml
app/views/organized/stickers/edit.html.haml

And some other small sticker frontend improvements

Do better with deleted sticker display

---

.gitignore

Adding a few little bits that other people might wind up with when setting up the project that shouldn't be in source control.

Add a few relevant things to .gitignore

---

app/assets/javascripts/init.coffee
app/views/shared/_google_ad.html.haml

Reverts bikeindex/bike_index#2044
Doesn't seem like it had a big impact on our audience, so reenabling

Turn ads back on

---

app/models/external_registry_bike/project529_bike.rb
app/workers/fetch_project529_bikes_worker.rb
spec/models/external_registry_bike/project529_bike_spec.rb

Enable passing updated_since to 529

---

app/controllers/admin/paints_controller.rb
app/helpers/bike_helper.rb
app/models/paint.rb
app/services/bike_displayer.rb
app/views/admin/bikes/_bike_tabs.html.haml
app/views/bikes/show.html.haml
app/views/shared/_email_bike_box.html.haml
app/workers/bulk_import_worker.rb
spec/models/bike_spec.rb
spec/services/bike_displayer_spec.rb
spec/workers/bulk_import_worker_spec.rb

Fix #679 "Improve bulk imports color parsing"

Use paints for bulk imports

---

spec/workers/bulk_import_worker_spec.rb

This bulk import test is being flaky!
Add a print of the error so we can figure out what's going

add bulk import debug print

---

app/models/creation_state.rb
app/models/ownership.rb
app/services/bike_creator.rb
app/views/admin/bikes/edit.html.haml
app/workers/migrate_creation_state_to_ownership_worker.rb
lib/tasks/rake_tasks.rake
spec/workers/migrate_creation_state_to_ownership_worker_spec.rb

Fix creation state migration bugs

---

Gemfile
Gemfile.lock
Guardfile
app/controllers/api/v2/bikes.rb
app/controllers/api/v2/bikes_search.rb
app/controllers/api/v2/defaults.rb
app/controllers/api/v2/manufacturers.rb
app/controllers/api/v2/me.rb
app/controllers/api/v2/selections.rb
app/controllers/api/v2/users.rb
app/controllers/api/v3/me.rb
app/controllers/api/v3/organizations.rb
app/serializers/application_serializer.rb
app/serializers/bike_v2_serializer.rb
spec/requests/api/v2/bikes_search_request_spec.rb
spec/serializers/bike_v2_serializer_spec.rb
spec/serializers/bike_v2_show_serializer_spec.rb
spec/serializers/ctypes_serializer_spec.rb

`active_model_serializers` after version `0.8` don't actually support caching - see Discourse Gemfile

downgrade active_model_serializers

---

app/controllers/organized/bikes_controller.rb
app/models/bike.rb
app/models/concerns/geocodeable.rb
app/models/export.rb
app/models/stolen_record.rb
app/views/organized/bikes/_search.html.haml
app/views/organized/exports/show.html.haml
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.nl.yml
spec/controllers/organized/bikes_controller_spec.rb
spec/models/bike_spec.rb
spec/requests/organized/bikes_request_spec.rb

- Some minor bike scoping additions
- Organization create export from search

Organizations can export bikes from search

---

app/models/user_registration_organization.rb
app/views/my_accounts/_registration_organizations.html.haml
app/views/welcome/choose_registration.html.haml

- sort organizations alphabetically
- Make sure new bikes don't have to enter information they've already entered

Minor user registration organization fixes

---

app/mailers/customer_mailer.rb
app/views/customer_mailer/recovered_from_link.html.haml
app/views/customer_mailer/recovered_from_link.text.haml
app/views/customer_mailer/stolen_notification_email.html.haml
app/views/customer_mailer/user_alert_email.html.haml
app/views/organized_mailer/finished_registration.html.haml
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.nl.yml

replace inconsistent use of `biketype`

use bike_type everywhere

---

app/controllers/admin/bikes_controller.rb
app/controllers/bikes_controller.rb
app/controllers/organized/bikes_controller.rb
app/models/bike.rb
app/services/bike_updator.rb
app/views/admin/bike_stickers/_table.html.haml
app/views/admin/bikes/_bike_tabs.html.haml
app/views/admin/bikes/_table.html.haml
app/views/organized/bikes/_search.html.haml
app/workers/migrate_update_by_user_at_worker.rb
lib/tasks/rake_tasks.rake
spec/services/bike_updator_spec.rb

Follows #2163 (which was improperly named)

Follow along for bike updated_by_user_at

---

Gemfile
Gemfile.lock

PDF generation has been broken for a while. See https://github.com/bikeindex/bike_index/issues/168
Commenting out these gems until we fix it.

Comment out wicked_pdf gem

---

spec/factories/organization_invitations.rb
spec/mailers/previews/organized_mailer_preview.rb

remove organization_invitation references

---

app/mailers/customer_mailer.rb
app/models/mail_snippet.rb
app/models/notification.rb
app/models/stolen_record.rb
app/workers/scheduled_email_survey_worker.rb
app/workers/scheduled_worker_runner.rb
spec/factories/bikes.rb
spec/mailers/previews/customer_mailer_preview.rb
spec/workers/scheduled_email_survey_worker_spec.rb
spec/workers/scheduled_worker_runner_spec.rb

Add scheduled theft survey worker

---

app/controllers/admin/bike_stickers_controller.rb
app/views/admin/bike_stickers/index.html.haml
app/views/bikes/_organized_access_panel.html.haml
app/views/bikes/scanned.html.haml
app/views/organized/bikes/_list.html.haml
app/views/organized/bikes/_search.html.haml
app/views/organized/bikes/index.html.haml
app/views/organized/exports/new.html.haml
app/views/organized/stickers/edit.html.haml
spec/models/bike_sticker_batch_spec.rb
spec/models/bike_sticker_spec.rb

Sticker display improvements, improve admin sticker load speed

---

.circleci/config.yml
Gemfile
Gemfile.lock

Update circleci cache key

---

app/assets/stylesheets/revised/sections/alerts.scss
app/views/layouts/application.html.haml

This reverts #2291 commit aeb99b0e5a655c9e5e3310910548ff289e7f6293.

Remove add downtime warning alert to the top

---

app/assets/javascripts/revised/components/alerts.coffee
app/assets/stylesheets/revised/sections/alerts.scss

Fix issue where alerts rendered under the donation modal

Alert over modal

---

app/controllers/bikes_controller.rb
app/javascript/scripts/pages/admin/image_uploader.js
app/uploaders/alert_image_uploader.rb
app/uploaders/application_uploader.rb
app/uploaders/avatar_uploader.rb
app/uploaders/circular_image_uploader.rb
app/uploaders/image_uploader.rb
app/uploaders/listicle_image_uploader.rb
app/uploaders/partner_uploader.rb
app/views/admin/ads/edit.html.haml
app/views/admin/bikes/_bike_tabs.html.haml
app/views/admin/ctypes/_form.html.haml
app/views/admin/manufacturers/_form.html.haml
app/views/admin/recovery_displays/_form.html.haml
app/views/admin/tweets/edit.html.haml
app/views/admin/tweets/new.html.haml
app/views/bikes/_organized_access_panel.html.haml
app/views/bikes_edit/photos.html.haml
app/views/my_accounts/_sharing.html.haml
app/views/organizations/embed.html.haml
app/views/organizations/embed_extended.html.haml
app/views/organized/bikes/new_iframe.html.haml
app/views/organized/manages/show.html.haml
app/views/public_images/_admin_new_form.html.haml
app/workers/after_bike_save_worker.rb
spec/uploaders/image_uploader_spec.rb
spec/workers/after_bike_save_worker_spec.rb

- Fix nil organization error in after bike save
- Improve admin serial display
- Restrict file upload types

fix nil organization error, add accepts to image upload fields

---

app/helpers/application_helper.rb
app/helpers/bike_helper.rb
app/helpers/header_tag_helper.rb
app/integrations/twitter_tweeter_integration.rb
app/models/bike.rb
app/models/bike_version.rb
app/models/concerns/bike_attributable.rb
app/serializers/bike_serializer.rb
app/serializers/bike_v2_serializer.rb
app/services/bike_displayer.rb
app/views/admin/recovery_displays/_form.html.haml
app/views/bikes/_main_show_block.html.haml
app/views/bikes/theft_alerts/new.html.haml
spec/controllers/user_embeds_controller_spec.rb
spec/models/bike_spec.rb
spec/serializers/bike_v2_serializer_spec.rb
spec/services/bike_displayer_spec.rb

To make public image displaying more performant and dry out some code.

Add image_url to bikes

---

app/controllers/bikes_controller.rb
app/models/graduated_notification.rb
app/views/organized/graduated_notifications/show.html.haml
db/migrate/20230418192859_add_marked_remaining_by_id_to_graduated_notifications.rb
db/structure.sql
spec/requests/bikes_request_spec.rb

Also add tracking of marked remaining by

Marked remaining button for organizations

---

app/models/cycle_type.rb
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.nl.yml
spec/models/cycle_type_spec.rb
spec/requests/bikes/create_request_spec.rb

Also, switch `personal_mobility` to `personal-mobility` for consistency

Add non-e-scooter cycle type

---

app/views/documentation/api_v2.html.haml
app/views/documentation/api_v3.html.haml
app/views/layouts/application.html.haml
app/views/layouts/application_bikehub.html.haml
app/views/layouts/doorkeeper.html.haml
app/views/layouts/embed_layout.html.haml
app/views/layouts/embed_user_layout.html.haml
app/views/layouts/payments_layout.html.haml
app/views/layouts/reg_embed.html.haml
app/views/shared/_analytics.html

- Create a partial, render the partial everywhere (rather than inlining the code everywhere)
- Add new gtags code (eventually will remove universal analytics)

Update google analytics code

---

app/assets/images/link.svg
app/controllers/admin/bulk_imports_controller.rb
app/helpers/application_helper.rb
app/javascript/packs/application_css.scss
app/mailers/admin_mailer.rb
app/models/bulk_import.rb
app/views/admin/bulk_imports/index.html.haml
app/views/admin/bulk_imports/show.html.haml
app/views/admin_mailer/invalid_extension_for_ascend_import.html.haml
app/views/organized/bulk_imports/_error_display.html.haml
app/views/organized/bulk_imports/show.html.haml
app/views/shared/_admin_current_header.html.haml
app/workers/invalid_extension_for_ascend_import_worker.rb
app/workers/unknown_organization_for_ascend_import_worker.rb
spec/models/bulk_import_spec.rb
spec/requests/organized/bulk_imports_request_spec.rb
spec/workers/invalid_extension_for_ascend_import_worker_spec.rb

Clean up bulk import errors

---

app/workers/approve_stolen_listing_worker.rb
spec/workers/approve_stolen_listing_worker_spec.rb

~Twitter~ X is a dumpster fire. We can't afford their API pricing. Hopefully another solution presents itself soon!
This is to prevent the enormous number of errors that are happening.

Skip tweeting configuration option

---

app/models/notification.rb
app/workers/email_partial_registration_worker.rb
app/workers/email_theft_alert_notification_worker.rb
spec/workers/email_partial_registration_worker_spec.rb

Create notification on partial registration email

---

app/models/bulk_import.rb
app/models/organization.rb
app/views/admin/bulk_imports/index.html.haml
app/views/admin/bulk_imports/show.html.haml
app/views/organized/bulk_imports/_error_display.html.haml
app/views/organized/bulk_imports/_error_type.html.haml
app/views/organized/bulk_imports/_progress_display.html.haml
app/views/organized/bulk_imports/index.html.haml
app/views/organized/bulk_imports/show.html.haml
app/workers/bulk_import_worker.rb
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.nl.yml
spec/models/bulk_import_spec.rb
spec/requests/admin/organizations_request_spec.rb
spec/requests/organized/bulk_imports_request_spec.rb
spec/workers/bulk_import_worker_spec.rb

- Improve bulk import error display (adds on #2363) - particularly line errors and ascend errors
- Improve progress display - to show that the import failed, rather than success, if blocking error

Add ascend error method and improve bulk import error display

---

app/controllers/admin/notifications_controller.rb
app/integrations/twilio_integration.rb
app/models/notification.rb
app/views/admin/notifications/_table.html.haml
app/views/admin/notifications/index.html.haml
app/workers/migrate_message_channel_target_worker.rb
app/workers/scheduled_worker_runner.rb
db/migrate/20230906180600_add_message_channel_target_to_notifications.rb
db/structure.sql
spec/integrations/twilio_integration_spec.rb
spec/models/notification_spec.rb
spec/workers/customer_contact_notification_create_worker_spec.rb
spec/workers/email_partial_registration_worker_spec.rb
spec/workers/email_stolen_notification_worker_spec.rb
spec/workers/migrate_message_channel_target_worker_spec.rb
spec/workers/user_phone_confirmation_worker_spec.rb

- Add `message_channel_target` to `Notification`
- Migrate `MigrateMessageChannelTargetWorker` to backfill `message_channel_target`

Add message_channel_target to notifications

---

app/mailers/customer_mailer.rb
app/models/bike.rb
app/models/notification.rb
app/workers/migrate_message_channel_target_worker.rb
app/workers/scheduled_email_survey_worker.rb
spec/workers/scheduled_email_survey_worker_spec.rb

Follows #2389 
Also, #2394 was added to support this.

Theft survey for unclaimed bikes

---

app/views/shared/_google_ad.html.haml

Google ads are pushing malware :/

Disable google ads

---

app/controllers/admin/bikes_controller.rb
app/javascript/scripts/pages/admin/binx_admin.js
app/views/admin/bikes/_bike_tabs.html.haml
app/views/admin/bikes/_table.html.haml
app/views/admin/bikes/edit.html.haml
app/views/admin/bikes/index.html.haml
app/views/admin/organizations/index.html.haml
app/views/admin/organizations/show.html.haml
app/views/bikes/show.html.haml
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.nl.yml

Better handling for example/spam/deleted/hidden
Also, add admin bike status search

Update admin bike display

---

app/models/organization_feature.rb
app/views/bikes/new.html.haml
config/locales/en.yml
spec/models/organization_spec.rb

Also, minor rename of student affiliation select options

Add organization feature to make student_id a required field

---

app/models/application_record.rb
config/database.yml

Update database.yml to be 3-tier for read replica

---

app/models/application_record.rb
config/database.yml

Follows #2409 - which failed and was reverted. This should fix it up.

Replica deployment

---

app/models/stolen_record.rb
app/views/shared/_user_general_alert.html.haml
app/workers/after_stolen_record_save_worker.rb
spec/requests/admin/dashboard_request_spec.rb
spec/requests/admin/organizations_request_spec.rb
spec/requests/bike_versions/edits_request_spec.rb
spec/requests/bikes/show_request_spec.rb
spec/requests/bikes/update_request_spec.rb
spec/requests/bikes_request_spec.rb
spec/requests/locale_detection_request_spec.rb
spec/requests/my_accounts_request_spec.rb
spec/requests/organizations_request_spec.rb
spec/requests/organized/bulk_imports_request_spec.rb
spec/requests/organized/manages_request_spec.rb

Pull in updates from #2410 and #2412 that should be merged, regardless.

Read replica changes

---

app/controllers/bikes_controller.rb
app/views/bikes/_main_show_block.html.haml

It breaks the bike versions view - and I have no idea why it's necessary.

Remove components ivar

---

app/controllers/bike_versions/edits_controller.rb
app/controllers/bike_versions_controller.rb
config/environments/development.rb
spec/workers/bulk_import_worker_spec.rb

Pull out some useful bits from #2410

Update bike versions controllers

---

Gemfile.lock

Pull out additional gem updates from #2374

Additional gem updates for Ruby 3

---

app/controllers/admin/bikes_controller.rb
app/models/concerns/bike_searchable.rb
app/views/admin/bikes/_bike_tabs.html.haml
app/views/admin/bikes/index.html.haml
app/views/admin/bikes/show.html.haml
app/workers/migrate_normalized_serial_segments_worker.rb
app/workers/scheduled_email_survey_worker.rb

Add serial search to admin bikes and duplicate bike tab

---

app/integrations/file_cache_maintainer.rb
app/models/counts.rb
app/services/autocomplete.rb
app/services/autocomplete/loader.rb
app/services/autocomplete/matcher.rb
app/services/redis_pool.rb
app/workers/scheduled_worker_runner.rb
spec/services/autocomplete/loader_spec.rb
spec/support/scheduled_worker.rb

DRY up the multiple Redis pool methods.

add RedisPool class

---

app/controllers/admin/logged_searches_controller.rb
app/views/admin/logged_searches/index.html.haml
app/workers/scheduled_store_log_searches_worker.rb
db/analytics_migrate/20231027173606_remove_serial_from_logged_searches.rb
db/analytics_structure.sql
spec/workers/scheduled_store_log_searches_worker_spec.rb

Follows #2462 - removes the deprecated column and adds some frontend updates.

Log searcher improvements follow along

---

app/workers/migrate_strip_frame_model_worker.rb

Remove MigrateStripFrameModelWorker

---

app/controllers/organized/base_controller.rb
app/controllers/organized/bulk_imports_controller.rb
app/controllers/organized/exports_controller.rb
app/controllers/organized/graduated_notifications_controller.rb
app/controllers/organized/hot_sheets_controller.rb
app/controllers/organized/manage_impoundings_controller.rb
app/controllers/organized/parking_notifications_controller.rb
app/controllers/organized/stickers_controller.rb
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.nl.yml
spec/requests/organized/exports_request_spec.rb
spec/requests/organized/manage_impoundings_request_spec.rb
spec/requests/organized/parking_notifications_request_spec.rb
spec/requests/organized/stickers_request_spec.rb

DRY up a translation that was duplicated multiple times

Shared org no access translation

---

app/models/model_audit.rb
app/views/organized/model_audits/index.html.haml
app/workers/update_model_audit_worker.rb

Small model audit fixes

---

app/controllers/api/v2/bikes.rb
bin/setup

Fix bin/setup

---

README.markdown
config/routes.rb

Reference translation.io in readme
Also, remove unnecessary duplicate routes from route file

Readme update

---

.circleci/config.yml
.rspec

Circleci again

---

app/helpers/localization_helper.rb
spec/helpers/localization_helper_spec.rb

Norwegian translation/localization files are live/not deleted - assuming tests path what else should we be wary of before this goes live?

Enabling Norwegian on the front-end

---

app/assets/stylesheets/revised/fonts.scss
app/helpers/admin_helper.rb
app/models/bike.rb
app/models/membership.rb
app/models/user.rb
app/views/bikes/_organized_access_panel.html.haml
app/views/organized/users/_membership_role_fields.html.haml
app/views/organized/users/edit.html.haml
app/views/organized/users/index.html.haml
app/views/organized/users/new.html.haml
app/workers/update_organization_associations_worker.rb
config/locales/en.yml
db/migrate/20231212023722_switch_membership_role_to_be_enum.rb
db/primary_replica_structure.sql
db/structure.sql
spec/models/bike_spec.rb
spec/requests/organized/bikes_request_spec.rb

Also, switch membership role to be an enum

add member_no_bikes_edit role

---

config/locales/.translation_io
config/locales/en.yml
config/locales/translation.es.yml
config/locales/translation.nb.yml
config/locales/translation.nl.yml
db/migrate/20231212025929_remove_membership_role_string.rb
db/primary_replica_structure.sql
db/structure.sql

Cleans up after https://github.com/bikeindex/bike_index/pull/2516

Remove membership role_string

---

app/views/bikes/new.html.haml
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.es.yml
config/locales/translation.nb.yml
config/locales/translation.nl.yml

Changed a translation interpolation argument in #2514 without changing the key :/

Bikes new locale bug

---

app/views/my_accounts/_delete_account.html.haml
app/views/my_accounts/edit.html.haml
app/views/shared/_edit_bike_skeleton.html.haml
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.es.yml
config/locales/translation.nb.yml
config/locales/translation.nl.yml

Follows #2539 - improves mobile interface

Delete account follow up

---

app/controllers/admin/logged_searches_controller.rb
app/controllers/organized/hot_sheets_controller.rb
app/helpers/admin_helper.rb
app/models/hot_sheet_configuration.rb
app/models/logged_search.rb
app/views/admin/logged_searches/index.html.haml
spec/factories/logged_searches.rb
spec/models/logged_search_spec.rb
spec/requests/organized/hot_sheets_request_spec.rb
spec/support/custom_expectations.rb

- Add logged searches associations
- Include associations in Admin Logged Search index
- Redirect Org view of Hot Sheets that don't have a location (rather than 500ing)

Add Logged search associations

---

app/controllers/concerns/controller_helpers.rb
app/controllers/discourse_authentication_controller.rb

I'm focusing on solving redirects that where identified as dangerous by Brakeman, ensuring that is no risk of the client do any changes, explicitly marking it as a safe host to avoid breaches.

BIB-41 - Address dangerous redirects

---

.brakeman.yml
.circleci/config.yml
Gemfile
Gemfile.lock

This priority involves configuring the CI/CD pipeline to run Brakeman scans on every pull request. We're set up necessary scripts, integrate them into the existing PR checks, and define acceptable thresholds for warnings.

BIB-22 - Integrate brakeman into pipeline

---

app/helpers/money_helper.rb
app/services/geocode_helper.rb
config/locales/.translation_io
config/locales/localization.es.yml
config/locales/localization.it.yml
config/locales/localization.nb.yml
config/locales/localization.nl.yml
spec/services/geocode_helper_spec.rb
spec/vcr_cassettes/geohelper-boundingbox.yml
spec/vcr_cassettes/geohelper-coordinates-US.yml
spec/vcr_cassettes/geohelper-coordinates.yml
spec/vcr_cassettes/geohelper-formatted_address_hash.yml
spec/vcr_cassettes/geohelper-ip_address.yml
spec/vcr_cassettes/geohelper-us.yml
spec/vcr_cassettes/geohelper-zipcode.yml

Fix GeocoderHelper

---

app/views/info/security.html.haml
spec/vcr_cassettes/geohelper-reverse_geocode.yml

Oops, the PGP key isn't for `admin@bikeindex.org`, it's for `seth@`

Update security email

---

Gemfile
Gemfile.lock
spec/requests/api/v2/bikes_request_spec.rb
spec/requests/api/v3/bikes_request_spec.rb
spec/requests/oauth_authorizations_request_spec.rb

bump doorkeeper

---

app/controllers/info_controller.rb
app/controllers/stolen_controller.rb
spec/requests/info_request_spec.rb
spec/requests/payments_request_spec.rb
spec/requests/stolen_request_spec.rb

More allow_other_host redirects

---

app/controllers/concerns/controller_helpers.rb
app/helpers/bike_helper.rb
app/helpers/organized_helper.rb
app/models/bike.rb
app/models/bike_sticker.rb
app/models/color.rb
app/models/concerns/enumable.rb
app/models/country.rb
app/models/ctype.rb
app/models/exchange_rate.rb
app/models/organization.rb
app/models/stolen_record.rb

Replace i18n_translate_with_args

---

app/helpers/translation_helper.rb
app/mailers/admin_mailer.rb
app/mailers/customer_mailer.rb
app/mailers/donation_mailer.rb
app/mailers/organized_mailer.rb
app/models/blog.rb
app/models/concerns/translatable.rb
app/models/theft_alert_plan.rb
config/locales/.translation_io
config/locales/translation.es.yml
config/locales/translation.it.yml
config/locales/translation.nb.yml
config/locales/translation.nl.yml
docs/translation.markdown
spec/helpers/translation_helper_spec.rb

Rather than as localization in some places
Also, sync the translations

Consistently name things translation (rather than sometimes localization)

---

app/controllers/memberships_controller.rb
app/controllers/webhooks_controller.rb
app/models/stripe_subscription.rb
app/views/admin/stripe_subscriptions/_table.html.haml
app/views/customer_mailer/invoice_email.html.haml
config/routes.rb
spec/models/stripe_event_spec.rb
spec/requests/memberships_request_spec.rb
spec/requests/webhooks_request_spec.rb

Also fix a bug in membership creation from stripe, follow up to #2692

skip_csrf for webhooks

---

app/assets/stylesheets/revised/pages/bikes/edit_photos.scss
app/models/theft_alert.rb
app/views/admin/theft_alerts/_table.html.haml
app/views/bikes/_bike_show_overlays.html.haml
app/views/bikes/show.html.haml
spec/services/facebook_ads_integration_spec.rb

- Fix minor issues caused by the bootstrap wrap update
- Display theft alert facebook objective in admin

Improve bike show

---

.github/workflows/ci.yml
Gemfile.lock
app/jobs/email_reset_password_job.rb
app/models/banned_email_domain.rb
app/models/notification.rb
app/models/user.rb
app/views/admin/notifications/_table.html.haml
config/application.rb
config/environments/production.rb
spec/models/bike_spec.rb
spec/requests/api/v3/bikes_request_spec.rb

Banned domains caused postmark to stop delivering our email 🔥 
This adds a way to swap in SendGrid with environmental variables

Fix email deliverability issues

---

app/controllers/admin/email_domains_controller.rb
app/controllers/admin/memberships_controller.rb
app/jobs/email_confirmation_job.rb
app/jobs/remove_unconfirmed_users_job.rb
app/jobs/scheduled_job_runner.rb
app/jobs/update_email_domain_job.rb
app/models/bike.rb
app/models/email_domain.rb
app/models/user.rb
app/models/user_likely_spam_reason.rb
app/views/admin/email_domains/_form.html.haml
app/views/admin/email_domains/_table.html.haml
app/views/admin/email_domains/index.html.haml
app/views/admin/email_domains/show.html.haml
app/views/admin/users/edit.html.haml
db/analytics_structure.sql
db/migrate/20250312225116_add_user_count_and_data_and_changed_status_at_to_email_domains.rb
db/migrate/20250313035336_create_user_likely_spam_reasons.rb
db/primary_replica_structure.sql
db/structure.sql
spec/factories/user_likely_spam_reasons.rb
spec/jobs/email_confirmation_job_spec.rb
spec/jobs/remove_unconfirmed_users_job_spec.rb
spec/jobs/update_email_domain_job_spec.rb
spec/models/email_domain_spec.rb
spec/models/user_likely_spam_reason_spec.rb
spec/requests/admin/email_domains_request_spec.rb
spec/vcr_cassettes/UpdateEmailDomainJob-bikeindex.yml

- Generate new domains on create
- Test new email domains when created 
- Automatically mark new domains as pending if they are suspicious (ie don't resolve)

Add new email domain functionality

---

app/controllers/admin/email_domains_controller.rb
app/jobs/update_email_domain_job.rb
app/models/email_domain.rb
app/views/admin/email_domains/index.html.haml
spec/jobs/email_confirmation_job_spec.rb
spec/jobs/update_email_domain_job_spec.rb
spec/vcr_cassettes/UpdateEmailDomainJob-gmail.yml

Fix the fact that new domains are always ending up ban pending

Additional email domain functionality

---

app/jobs/update_email_domain_job.rb
app/models/email_domain.rb
app/views/admin/email_domains/_table.html.haml
app/views/admin/email_domains/show.html.haml
spec/jobs/update_email_domain_job_spec.rb

Add number of notifications sent to email domains and display in admin

EmailDomain notifications

---

app/components/pagination/component.html.erb
app/components/pagination/component.rb
app/components/pagination/component_controller.js
app/components/pagination/component_preview.rb
app/components/search/form/component.html.erb
app/views/bikes/_bike.html.haml
app/views/search/registrations/_results.html.erb
app/views/search/registrations/index.html.erb
config/routes.rb
spec/components/pagination/component_spec.rb
spec/requests/search/registrations_request_spec.rb
spec/vcr_cassettes/geohelper-boundingbox.yml
spec/vcr_cassettes/geohelper-coordinates-US.yml
spec/vcr_cassettes/geohelper-coordinates.yml
spec/vcr_cassettes/geohelper-formatted_address_hash.yml
spec/vcr_cassettes/geohelper-ip_address.yml
spec/vcr_cassettes/geohelper-us.yml
spec/vcr_cassettes/geohelper-zipcode.yml

Follows #2744 and fixes a few issues
- Creates a view component that handles Pagination (previously, pagination links didn't scroll to the top of the page)
- Links to bikes rendered an invalid page, this fixes it

Add pagination component for search form

---

app/views/layouts/application.html.haml

Update navbar cache

---

app/components/search/registration_fields/component.html.erb
app/components/search/registration_fields/component.rb
app/components/search/registration_fields/component_controller.js
app/javascript/utils/collapse_utils.js

This was the only place that `collapse_utils.js` was used. I left the file in because I'm confident that it will be used again though!

Search::Registrations always show location, location xs screen improvements

---

app/components/choose_membership/component.html.erb

Make it explicit that it's donation

Choose membership display update

---

app/jobs/scheduled_email_survey_job.rb
app/models/concerns/geocodeable.rb
app/models/country.rb
app/models/location.rb
app/models/state.rb
app/models/stolen_record.rb
app/services/geocode_helper.rb
app/views/admin/bikes/edit.html.haml
app/views/admin/organizations/_location_fields.html.haml
app/views/bikes/_organized_access_panel.html.haml
app/views/bikes/new.html.haml
app/views/bikes_edit/bike_details.html.haml
app/views/bikes_edit/bike_fields/_stolen_location.html.haml
app/views/my_accounts/_root.html.haml
app/views/organizations/embed.html.haml
app/views/organizations/embed_extended.html.haml
app/views/organized/bikes/new_iframe.html.haml
app/views/organized/manages/_location_fields.html.haml
spec/factories/0_factory_traits.rb
spec/factories/countries.rb
spec/factories/states.rb
spec/models/country_spec.rb
spec/models/state_spec.rb
spec/services/geocode_helper_spec.rb
spec/support/shared_examples/geocodeable.rb

- Add `State.united_states` and reference United States id that is constant
- Update all frontend code that references the old method

Make State model handle multiple countries

---

config/locales/.translation_io
config/locales/translation.es.yml
config/locales/translation.it.yml
config/locales/translation.nb.yml
config/locales/translation.nl.yml

translations for address-record

---

app/assets/stylesheets/revised/pages/bikes/edit_alert.scss
app/components/header_tags/component.rb
app/controllers/manufacturers_controller.rb
app/jobs/stolen_bike/update_theft_alert_facebook_job.rb
app/models/bike.rb
app/models/manufacturer.rb
app/models/theft_alert.rb
app/services/spreadsheets/manufacturers.rb
app/views/admin/theft_alerts/edit.html.haml
spec/jobs/stolen_bike/update_theft_alert_facebook_job_spec.rb
spec/models/stripe_event_spec.rb
spec/models/theft_alert_spec.rb
spec/requests/webhooks_request_spec.rb
spec/services/spreadsheets/manufacturers_spec.rb

Small Bug fixes

---

spec/jobs/bike_book_update_job_spec.rb
spec/requests/api/v1/bikes_request_spec.rb
spec/requests/bikes/create_request_spec.rb
spec/services/spreadsheets/manufacturers_spec.rb

Follows #2798 
Hopefully fixes Spreadsheets::Manufacturer flakiness
marks some additional specs as `:flaky`

Fix flaky specs

---

app/controllers/concerns/bike_editable.rb
app/views/bikes_edit/remove.html.haml
spec/requests/bike_versions/edits_request_spec.rb
spec/requests/bikes/edits_request_spec.rb

Bike versions are fully released - remove the feature flag, so that tests accurately reflect the state of the world

Remove bike version feature flag

---

app/assets/stylesheets/revised/sections/primary_header_nav.scss
app/views/layouts/application.html.haml
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.es.yml
config/locales/translation.it.yml
config/locales/translation.nb.yml
config/locales/translation.nl.yml
spec/services/spreadsheets/manufacturers_spec.rb

Also fix a primary menu height bug

Rename "search bikes" to "search" in primary menu

---

app/components/alert/component.html.erb
app/components/card/component.rb
app/components/legacy_form_well/form_group_row/component_preview.rb
app/components/page_section/choose_membership/component.html.erb
app/components/pagination/component.rb
app/javascript/application.js
app/javascript/utils/time_localizer.js
app/views/layouts/component_preview.html.erb
app/views/layouts/component_preview_form_wrap.html.erb

- Reduce border radius on new styles (to more closely align with existing brutalist style)
- Update TimeLocalizer class to add `onlyTodayWithoutDate` as an option - and stop rendering yesterday, tomorrow, etc

Minor frontend cleanup

---

app/controllers/admin/dashboard_controller.rb
app/models/membership.rb
app/views/admin/dashboard/maintenance.html.haml
spec/models/membership_spec.rb
spec/requests/admin/memberships_request_spec.rb

also drive by fixes for `admin/maintenance`

Ensure user exists when creating membership

---

app/controllers/admin/theft_alerts_controller.rb
app/jobs/stolen_bike/remove_orphaned_images_job.rb
config/brakeman.ignore

Load error from insights in `Facebook::AdsIntegration`
Also fix nil error in `StolenBike::RemoveOrphanedImagesJob`

Fix ad integration error

---

app/assets/stylesheets/revised/pages/news/index.scss
app/components/search/form/component_preview.rb
app/components/search/kind_select_fields/component.rb
app/components/search/kind_select_fields/component_controller.js
app/components/search/kind_select_fields/component_preview.rb
app/controllers/search/marketplace_controller.rb
app/models/user.rb
app/views/layouts/application.html.haml
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.es.yml
config/locales/translation.it.yml
config/locales/translation.nb.yml
config/locales/translation.nl.yml
config/routes.rb
spec/components/search/form/component_system_spec.rb
spec/requests/api/v3/bikes_request_spec.rb
spec/requests/search/marketplace_request_spec.rb
spec/vcr_cassettes/search_marketplace-counts.yml

- extend `User::MARKETPLACE_FREE_UNTIL`
- add endpoint and make counts show up for marketplace search
- add marketplace to header

Add counts to marketplace search

---

app/assets/stylesheets/registrations.scss
app/models/user.rb
spec/models/user_spec.rb

Also, remove `MARKETPLACE_FREE_UNTIL`, keep it free indefinitely

Add color for Colorado State

---

app/assets/stylesheets/registrations.scss

Follow up to #2866, to highlight the change where it might be forgotten

Add note about colors to scss

---

.github/copilot-instructions.md
.github/workflows/copilot-setup-steps.yml
claude.md
config/database.yml

Also a basic `claude.md` / `.github/copilot-instructions.md`

Add copilot-setup-steps.yml

---

.gitignore
bin/check_translations

Attempted to fix in #2893 but there was another issue :/

Fix check_translations issue

---

app/components/org/bike_access_panel/component.html.haml
app/components/org/bike_access_panel/component.rb
app/helpers/application_component_helper.rb
app/helpers/application_helper.rb
spec/helpers/application_component_helper_spec.rb
spec/helpers/application_helper_spec.rb

Fix phone link in org access panel

---

spec/services/geocode_helper_spec.rb
spec/vcr_cassettes/StripeEvent-update_bike_index-success.yml
spec/vcr_cassettes/WebhooksController-checkout_session-completed.yml
spec/vcr_cassettes/geohelper-boundingbox.yml
spec/vcr_cassettes/geohelper-coordinates-US.yml
spec/vcr_cassettes/geohelper-coordinates.yml
spec/vcr_cassettes/geohelper-formatted_address_hash.yml
spec/vcr_cassettes/geohelper-ip_address.yml
spec/vcr_cassettes/geohelper-ip_address2.yml
spec/vcr_cassettes/geohelper-us.yml
spec/vcr_cassettes/geohelper-zipcode.yml

... just modified the date of the stripe ones, instead of actually generating a subscription and re-recording

Update VCR cassettes

---

app/jobs/update_organization_pos_kind_job.rb
app/views/admin/organization_statuses/_graphs.html.erb
spec/jobs/update_organization_pos_kind_job_spec.rb

Fix a couple issues in OrganizationStatus

---

app/models/bike_version.rb
app/views/bike_versions/show.html.haml
app/views/bikes/_bike_show_overlays.html.haml
app/views/bikes/_header_row.html.haml
app/views/bikes/_main_show_block.html.haml
app/views/bikes/show.html.haml
config/locales/.translation_io
config/locales/en.yml
config/locales/translation.es.yml
config/locales/translation.it.yml
config/locales/translation.nb.yml
config/locales/translation.nl.yml
spec/factories/bike_versions.rb
spec/models/bike_version_spec.rb
spec/requests/bike_versions_request_spec.rb

- Improve Bike Version listing order
- Fix rendering deleted bike versions

Bike Version minor cleanup
